<link rel="stylesheet" href='js/datatables-plugins/dataTables.bootstrap.css'>


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
<form  ng-submit=""  name="gradeForm" ng-cloak novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="init()">

            <div class="row">
                <div class='col-md-6'>
                    <button  type="button" ng-click="updatePymentGrid()" class="btn btn-danger"  ng-show="isUpdate" ng-disabled="gradeForm.$invalid">Appliquer</button>
                    <button  type="button" ng-click="createPymentGrid()" class="btn btn-danger" ng-show="!isUpdate" ng-disabled="gradeForm.$invalid">Enrégistrer</button>
                    <span> <a href="#!/paymentsgrid">Retour</a></span>
                </div>
                <div class="col-md-4"><button  type="button" ng-click="$ctrl.deleteGrade()" class="btn btn-default"  ng-show="$ctrl.isUpdate" >Supprimer</button></div>
                <div class="col-md-2"></div>

                
            </div>
        </div>

<div class="form-view-main">
    <div class="form-view">


    <md-content layout-padding >

   
    <div layout-gt-sm='row' >
        
        <div class = "col-lg-12">
            
            <div layout-gt-sm='column' style="padding-top: 10px" >
                    <md-input-container >

                            <label>Intitulé:</label>
                            <input name="title" ng-model="pymtGridName" required  />
                                <div ng-messages="stdRegistrationForm.name.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>

                                </div>  
                    <div class="errors" ng-messages="gradeForm.semester.$error">
                      <div ng-message="required">Champ obligatoire</div>
                    </div>
                  </md-input-container>  
            </div> 

            <div layout-gt-sm='column' style="padding-top: 10px" >
                <md-input-container >
                    <label>Critère d'application</label>
                    <md-select name="criteria" ng-model="$ctrl.selectedCriteria"  md-on-open="" ng-change="$ctrl.showElement()"
                                md-no-asterisk  >
                        <md-option ng-disabled="true"><em>---Choix du Semestre---</em></md-option>
                        <md-option value='cycle' >---Par cycle---</md-option>
                        <md-option value='classe'>---Par classe---</md-option>
                      
                        {{sem.name}}
                      </md-option>
                    </md-select>
                    <div class="errors" ng-messages="gradeForm.criteria.$error">
                      <div ng-message="required">Champ obligatoire</div>
                    </div>
                  </md-input-container>  
            </div> 

        </div>
     
        <div class = "col-lg-12" style="background-color: #dfe4ea;" >
            <div class="row" ng-show="$ctrl.showClasseElement">  
            <div class="col-md-10"  style="margin-top:25px;">

                <md-input-container class="column md-block" flex-gt-sm>
                    <label>Classe:</label>
                    <md-autocomplete  md-search-text="$ctrl.searchClasse" 
                                     md-selected-item="$ctrl.selectedClasse"  
                                     md-items="item in $ctrl.query($ctrl.searchClasse)" 
                                     md-item-text="item.code" 
                                     md-min-length="0"
                                     placeholder="Faites le choix de la classe" 
                                     md-selected-item-change="$ctrl.selectedItemChange(item)"
                                     md-input-name="classe"
                                     md-no-asterisk
                                     ng-required='$ctrl.showClasseElement'>
                        <md-item-template>
                          <span md-highlight-text="$ctrl.searchClasse" md-highlight-flags="^i">{{item.code}}</span>

                        </md-item-template>
                        <md-not-found>
                          Aucun élément correspondant à "{{$ctrl.searchClasse}}" n'a été trouvé.

                        </md-not-found>
                    </md-autocomplete>
                        <div ng-messages="gradeForm.classe.$error">
                            <div ng-message="required">Ce champ est obligatoire</div>
                        </div> 
                </md-input-container >

            </div>
            <div class="col-md-2" style="margin-top:40px;" >
                <button class="btn btn-primary" ng-click="$ctrl.addClasse()"><i class="fa fa-plus"></i></button>
            </div>
        </div>
            <table>
               
                <tbody>
                    <tr ng-repeat="classe in $ctrl.classes">
                        <td class="text-primary" ng-bind="classe"></td>&nbsp;<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
                        <td ><button class="btn btn-default" ng-click="$ctrl.removeClasse(classe)"><i class="fa fa-trash"></i></button></td>
                    </tr>
                </tbody>
            </table>
            <div layout-gt-sm='column' style="padding-top: 10px" ng-show="$ctrl.showCycleElement">
                    <md-input-container>
                    <label>Choix du cycle</label>
                    <md-select name="cycle" ng-model="$ctrl.selectedCycle"  md-on-open="" 
                                md-no-asterisk ng-required='$ctrl.showCycleElement' >
                        <md-option ng-disabled="true"><em>---Choix du Semestre---</em></md-option>
                        <md-option value='1' >Premier cycle</md-option>
                        <md-option value='2'>Deuxième cycle</md-option>
                        <md-option value='3'>Troisième cycle</md-option>
                        <md-option value=-1'>Tous les cycles</md-option>
                      
                        {{sem.name}}
                      </md-option>
                    </md-select>
                    <div class="errors" ng-messages="gradeForm.cycle.$error">
                      <div ng-message="required">Champ obligatoire</div>
                    </div>
                  </md-input-container>  
            </div> 
        </div>           
    </div>
        
    <div layout-gt-sm='row' >
        <div class="col-md-12 text-right"><i class="fa fa-cogs" style="font-size: 1.5em; color:lightgrey; cursor: pointer;" ng-click=""></i></div>
        
    </div>
</md-content>


<p>&nbsp;</p>
              <!--tabs widget-->
                <div class="row" >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#"> Liste des plages applicables au grade</a></li>

                    </ul>
    <table class="table table-bordered table-striped table-condensed " >
        <thead>
            <tr class="bg-primary" ><th></th><th >Grade</th><th >Montant</th><th></th></tr>

        </thead>
        <tbody>
            <tr ng-repeat='rg in paymentGrid'>
                <td></td>
                <td ng-bind="rg.grade.name"></td>
                <td ng-bind="rg.amount"></td>

                <td><button class="btn btn-default" ng-click="removePymtItem(rg)"><i class="fa fa-trash bg-warning"></i></button></td>
            </tr>
            <tr><td><a  href="" ng-click="showGradeFeesForm(ev)">Ajouter une plage</a></td></tr>
            
        </tbody>
    </table>


                 </div>
                <!--End tab-->
                
            </div>  
        </div>

  </form>