
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
/*md-dialog{
max-width: 900px;

}*/
.md-dialog-container {

    z-index: 1000;

}

</style>

  

</style>
<div class="row">
                <div class="col-lg-12">
                    <h4 class="page-header">Grilles de payments des frais de vacation</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row" ng-init="init()">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default small">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <button type="button" ng-click="redirect(-1)" class="btn btn-danger" id='newacadyr'>Créer</button>

                        </div>
                  <md-radio-group ng-change="changeDefautlPymtGrid(defaultPymtGridId)"  ng-model="defaultPymtGridId" aria-labelledby="favoriteFruit">      
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                  <table id="tblfilieres" datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs1"  class="table table-striped  table-hover table-condensed datatable">
                                
                                <thead>
                                    <tr>
                                        <th  > #</th>
                                        <th  > Description</th>
                                        <th style="align: center" >[D]</th>
                                        <th ></th>
                                    </tr>
                                </thead>
                                <tbody>
    
                                    <tr ng-repeat="pymt in allPaymentTypes" style="cursor: pointer" ng-dblclick="redirect(pymt.id)">
                                        <td style="width:10%; align: center;">{{$index+1}}</td>
                                        <td ng-bind="pymt.description"></td>
                                      

                                        <td style="width:5%; align: center;">
                                            <md-radio-button    ng-value="pymt.id" class="md-primary"  >  </md-radio-button>
                                        </td>


                                        <td style="width:5%; align: center;">
                                              <div class="btn-group">

                                              <button  type="button" ng-click="deletePymentGrid(pymt.id)" class="btn btn-danger  btn-xs" ><i class="fa fa-trash-o"></i></button>
                                              </div>
                                        </td>
                                              
                                    </tr>

                                </tbody>
                            </table>
                  </md-radio-group>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

