<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ContractFollowUp extends \Application\Entity\ContractFollowUp implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'date', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'startTime', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'endTime', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'totalTime', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'description', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'lectureType', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'paymentStatus', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'classOfStudyHasSemester', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'contract', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'teacherPaymentBill'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'date', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'startTime', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'endTime', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'totalTime', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'description', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'lectureType', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'paymentStatus', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'classOfStudyHasSemester', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'contract', '' . "\0" . 'Application\\Entity\\ContractFollowUp' . "\0" . 'teacherPaymentBill'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ContractFollowUp $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartTime($startTime = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartTime', [$startTime]);

        return parent::setStartTime($startTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartTime', []);

        return parent::getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndTime($endTime = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndTime', [$endTime]);

        return parent::setEndTime($endTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndTime', []);

        return parent::getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalTime($totalTime = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalTime', [$totalTime]);

        return parent::setTotalTime($totalTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalTime', []);

        return parent::getTotalTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setLectureType($lectureType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLectureType', [$lectureType]);

        return parent::setLectureType($lectureType);
    }

    /**
     * {@inheritDoc}
     */
    public function getLectureType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLectureType', []);

        return parent::getLectureType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentStatus($paymentStatus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentStatus', [$paymentStatus]);

        return parent::setPaymentStatus($paymentStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentStatus', []);

        return parent::getPaymentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassOfStudyHasSemester(\Application\Entity\ClassOfStudyHasSemester $classOfStudyHasSemester = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassOfStudyHasSemester', [$classOfStudyHasSemester]);

        return parent::setClassOfStudyHasSemester($classOfStudyHasSemester);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassOfStudyHasSemester()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassOfStudyHasSemester', []);

        return parent::getClassOfStudyHasSemester();
    }

    /**
     * {@inheritDoc}
     */
    public function setContract(\Application\Entity\Contract $contract = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContract', [$contract]);

        return parent::setContract($contract);
    }

    /**
     * {@inheritDoc}
     */
    public function getContract()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContract', []);

        return parent::getContract();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeacherPaymentBill(\Application\Entity\TeacherPaymentBill $teacherPaymentBill = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeacherPaymentBill', [$teacherPaymentBill]);

        return parent::setTeacherPaymentBill($teacherPaymentBill);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeacherPaymentBill()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeacherPaymentBill', []);

        return parent::getTeacherPaymentBill();
    }

}
