
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php

$tblBody = '
<html >
  <head>
    <meta charset="utf-8">
    <title>Example 1</title>
    <link rel="stylesheet" href="style.css" media="all" />
  </head>
  <body>
    <header class="clearfix">
      <div id="logo">
        <img src="logo.png">
      </div>
      <h1>INVOICE 3-2-1</h1>
      <div id="company" class="clearfix">
        <div>Company Name</div>
        <div>455 Foggy Heights,<br /> AZ 85004, US</div>
        <div>(602) 519-0450</div>
        <div><a href="mailto:company@example.com">company@example.com</a></div>
      </div>
      <div id="project">
        <div><span>PROJECT</span> Website development</div>
        <div><span>CLIENT</span> John Doe</div>
        <div><span>ADDRESS</span> 796 Silver Harbour, TX 79273, US</div>
        <div><span>EMAIL</span> <a href="mailto:john@example.com">john@example.com</a></div>
        <div><span>DATE</span> August 17, 2015</div>
        <div><span>DUE DATE</span> September 17, 2015</div>
      </div>
    </header>
    <main>
      <table>
        <thead>
          <tr>
            <th class="service">N°</th>
            <th class="desc">DESCRIPTION</th>
            <th>VOLUME HORAIRE</th>
            <th>MONTANT</th>
          </tr>
        </thead>
        <tbody>';
    $index=1;
     foreach($this->billSumaryItems as $item):

     $tblBody .='<tr>
                <td class="service" >'.$index++.'</td>
                <td class="service" style="text-align:left;">'.$item["paymentDetails"]. ' <br>
                    Volume horaire alloué: '.$item["totalTime"].'<br>
                    Volume horaire réalisé: '.$item["totalTimePreviouslyBilled"]-$item["totalTimeCurrentlyBilled"].' <br>
                    Ecart: '.$item["totalTime"]-($item["totalTimePreviouslyBilled"]).' <td>
                
                <td class="service">'.$item["totalTimeCurrentlyBilled"].'</td>
                <td class="service">'.$item["paymentAmount"].'</td>
              </tr>';
     endforeach;
          
        $tblBody .='</tbody>
      </table>
      <div id="notices">
        <div>NOTICE:</div>
        <div class="notice">A finance charge of 1.5% will be made on unpaid balances after 30 days.</div>
      </div>
    </main>
    <footer>
      Invoice was created on a computer and is valid without the signature and seal.
    </footer>
  </body>
</html>
';




$mpdf = new \Mpdf\Mpdf([
	'margin_left' => 20,
	'margin_right' => 15,
	'margin_top' => 35,
	'margin_bottom' => 25,
	'margin_header' => 2,
	'margin_footer' => 5
]);




$mpdf->SetProtection(array('print')); 
$mpdf->SetTitle("Vacation billing");
$mpdf->SetAuthor("W-TECH"); 
$mpdf->SetWatermarkText("test");
$mpdf->showWatermarkText = true;
$mpdf->watermark_font = 'DejaVuSansCondensed';
$mpdf->watermarkTextAlpha = 0.1;
$mpdf->SetDisplayMode('fullpage');




$stylesheet = file_get_contents($_SERVER["DOCUMENT_ROOT"]."/assets/css/invoice_styles.css");
$mpdf->WriteHTML($stylesheet,1);

$mpdf->WriteHTML($tblBody);





ob_end_clean();
//Close and output PDF document
$mpdf->Output($_SERVER["DOCUMENT_ROOT"].'/impressions/'.preg_replace('/\s+/', '',"facture_enseignant").'-'.date("d-m-Y-H-i").'.pdf', 'F');

?>

        <style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

   <md-dialog style="max-width: 100%;
            max-height: 100%;
    width: 100%;
    height: 100%;
    border-radius: 0;" aria-label="Mango (Fruit)">
  <form ng-cloak>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h2>Impression PV Individuel</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>
      <div  class="md-dialog-content">

          <embed src=<?=$this->serverUrl().'/impressions/'.preg_replace('/\s+/', '',"facture").'-'.date("d-m-Y-H-i").'.pdf';?> type="application/pdf" style="width:100%;height:600px;"  />
                     


      </div>
    </md-dialog-content>

    <md-dialog-actions layout="row">

      <span flex></span>
      <md-button ng-click="cancel()">
       Fermer
      </md-button>

    </md-dialog-actions>
  </form>
</md-dialog>