
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php

use NumberToWords\NumberToWords; 

$mpdf = new \Mpdf\Mpdf([
	'margin_left' => 20,
	'margin_right' => 15,
	'margin_top' => 35,
	'margin_bottom' => 25,
	'margin_header' => 2,
	'margin_footer' => 5
]);



$mpdf->SetProtection(array('print')); 
$mpdf->SetTitle("Vacation billing");
$mpdf->SetAuthor("W-TECH"); 
//$mpdf->SetWatermarkText("test");
$mpdf->showWatermarkText = true;
$mpdf->watermark_font = 'DejaVuSansCondensed';
$mpdf->watermarkTextAlpha = 0.1;
$mpdf->SetDisplayMode('fullpage');




$stylesheet = file_get_contents($_SERVER["DOCUMENT_ROOT"]."/assets/css/invoice_styles.css");
$mpdf->WriteHTML($stylesheet,1);


foreach($this->teachers as $value)
{
$mpdf->SetHTMLHeader('<htmlpageheader name="myheader">
<table width="100%"><tr>
<td></td><td width="50%" style="color:#0000BB;  vertical-align: middle;"><span style="font-weight: bold; font-size: 14pt;"> Université des Montanges</span><br />'.$value["faculty"].'<br /></td>
<td width="50%" style="text-align: right; vertical-align: middle;"><img src="'.$value["logo"].'" width="75px" height="75x"></td>
</tr></table>
<hr>
</htmlpageheader>', $OE, $write);

$mpdf->SetHTMLFooter();    
    
    
$billSumaryItems = $value['bill_items']; 
$tblBody = '
<html >
  <head>
    <meta charset="utf-8">
    <title>Example 1</title>
    <link rel="stylesheet" href="style.css" media="all" />
  </head>
  <body>
    <header class="clearfix">

      <h1>FICHE DE REGLEMENT DES FRAIS DE VACATION <br />
      Année académique: '.$value['acadYr'].$value['bill_sumary']['refNumber'].'</h1>
          
      <div id="company" class="clearfix">
        <div>UdMAcademy</div>
      </div>
      <div id="project">
      <table>
      <tr >
            <td class="header">
                <div><span>NOM DE L\'ENSEIGNANT: </span> '.$value['info']['name'].' '.$value['info']['surname'].'</div>
                <div><span>NUMERO DE TELEPHONE: </span>'.$value['info']['phoneNumber'].'</div>
                <div><span>EMAIL: </span> <a href="'.$value['info']['phoneNumber'].'">'.$value['info']['email'].'</a></div>
                <div><span>DATE: </span>'.date("d-m-Y").'</div>
            </td> 
            <td></td>  
            <td class="header">
            <div><span>GRADE: </span> '.$value['info']['academicRank'].'</div>
            <div><span>VILLE d\'ORIGINE: </span>'.$value['info']['livingCity'].'</div>
            <div><span>EMAIL: </span> <a href="'.$value['info']['phoneNumber'].'">'.$value['info']['email'].'</a></div>
            <div><span>ETABLISSEMENT: </span>'.$value['info']['faculty'].'</div>
            </td> 
       </tr> 
      </table>      
       
      </div>
      
    <div>
        <div><b>Doit:</b> '.$value['info']['school'].' </div>
        <div><b>Contribuable N°:</b> </div> 
        <div><b>RIB:</b> </div>
    </div>
    </header>
    <main>
      <table>
        <thead>
        <tr></tr>
          <tr>
            <th class="service">N°</th>
            <th class="desc">DESCRIPTION</th>
            <th style="text-orientation: upright" class="desc">PREVU</th>
            <th style="width: 15px" class="desc">REAL</th>
            
            <th style="width: 15px" class="desc"> QTE</th>
            <th>PRIX UNITAIRE</th>
            
            <th>MONTANT</th>
          </tr>
        </thead>
        <tbody>';
    $index=1;
     foreach($billSumaryItems as $item):  
     if($item["lectureType"] != "XPORT")
     $tblBody .='<tr>
                <td class="service" >'.$index++.'</td>
                <td class="service" style="text-align:left;">'.$item["paymentDetails"].'</span></td>
                <td class="service" style="width: 15px">'.$item["totalTime"].'</td>
                <td class="service" style="width: 15px">'.$item["totalTimePreviouslyBilled"]+$item["totalTimeCurrentlyBilled"].'</td>
                <td style="width: 15px" class="service">'.$item["totalTimeCurrentlyBilled"].'</td>
                <td class="service">'.$item['paymentRate'].'</td>
                <td class="service">'.$item["paymentAmount"].'</td>
              </tr>';
     
     endforeach;
     
     foreach($billSumaryItems as $item):  
     if($item["lectureType"] == "XPORT" && !$this->isXportSupportingDocsAvalaible)
      $tblBody .='<tr>
                <td class="service" >'.$index++.'</td>
                <td class="service" style="text-align:left;">'.$item["paymentDetails"]. ' </td>
                    <td class="service"></td>
                    <td class="service"></td>
                <td class="service">'.$item["totalTimeCurrentlyBilled"].'</td>
                <td class="service">'.$item['paymentRate'].'</td>
                <td class="service">'.$item["paymentAmount"].'</td>
              </tr>';        
    endforeach;
     
     
          
        $tblBody .='<tr>
                <td class="service" ></td>
                <td class="service" style="text-align:left;"></td>
                <td class="service"></td>
                <td class="service"></td>
                <td class="service"></td>
                <td class="service" style="text-align:right;">HT</td>
                <td class="service" style="text-align:right;">'.$value['bill_sumary']['paymentAmountHt'].'FCFA</td>
              </tr>
              <tr>
                <td class="service" ></td>
                <td class="service" style="text-align:left;"></td>
                <td class="service"></td>
                <td class="service"></td>
                <td class="service"></td>
                <td class="service" style="text-align:right;">IR (5.5%)</td>
                <td class="service" style="text-align:right;">'.$this->ir.'FCFA</td>
              </tr>
              <tr>
                <td class="service" ></td>
                <td class="service" style="text-align:left;"></td>
                <td class="service"></td>
                <td class="service"></td>
                <td class="service"></td>
                <td class="service" style="text-align:right;">Retenu cavation (25%)</td>
                <td class="service" style="text-align:right;">'.$this->vacation.'FCFA</td>
              </tr>';        
     foreach($billSumaryItems as $item):  
     if($item["lectureType"] == "XPORT" && $this->isXportSupportingDocsAvalaible)
      $tblBody .='<tr>
                <td class="service" ></td>
                <td class="service" style="text-align:left;"> Remboursement frais de transport </td>
                <td class="service"></td>
                <td class="service"></td>
                
                <td class="service">'.$item["totalTimeCurrentlyBilled"].'</td>
                <td class="service">'.$item['paymentRate'].'</td>
                <td class="service">'.$item["paymentAmount"].'FCFA</td>
              </tr>';        
    endforeach;             
     $tblBody .='<tr>
                <td class="service" ></td>
                <td class="service" style="text-align:left;"></td>
                <td class="service"></td>
                <td class="service"></td>
                <td class="service"></td>
                <td class="service" style="text-align:right;">NET A PAYER </td>
                <td class="service" style="text-align:right;">'.$value['bill_sumary']['paymentAmount'].'FCFA</td>
              </tr>              

</tbody>
      </table>
      

      <div id="notices">
        <div>Arrêté la présente facture à la somme de:</div>
        <div class="notice"><i> '.NumberToWords::transformNumber('fr', $value['bill_sumary']['paymentAmount']).' FCFA </i></div>
      </div> 
      
   
    
     
       
      </div>
    


    </main>
    
        <table id= "signature" >
        <tr>
            <td >
            Le Chef service des Enseignements et du Personnel
            </td> 
            <td></td>
            <td>
            Bangangté le __________________________  <br/><br/><br/><br/>
            Le Doyen
            </td> 
        </tr> 
      </table>    
    <footer>
      Invoice was created on a computer and is valid without the signature and seal.
    </footer>
  </body>
</html>
';



$mpdf->WriteHTML($tblBody);


//$mpdf->AddPage();


}












ob_end_clean();
//Close and output PDF document
$mpdf->Output($_SERVER["DOCUMENT_ROOT"].'/impressions/'.preg_replace('/\s+/', '',"facture_enseignant").'-'.date("d-m-Y-H-i").'.pdf', 'F');

?>

        <style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

   <md-dialog style="max-width: 100%;
            max-height: 100%;
    width: 100%;
    height: 100%;
    border-radius: 0;" aria-label="Mango (Fruit)">
  <form ng-cloak>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h2>Impression PV Individuel</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>
      <div  class="md-dialog-content">

          <embed src=<?=$this->serverUrl().'/impressions/'.preg_replace('/\s+/', '',"facture_enseignant").'-'.date("d-m-Y-H-i").'.pdf';?> type="application/pdf" style="width:100%;height:600px;"  />
                     


      </div>
    </md-dialog-content>

    <md-dialog-actions layout="row">

      <span flex></span>
      <md-button ng-click="cancel()">
       Fermer
      </md-button>

    </md-dialog-actions>
  </form>
</md-dialog>