
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php

$mpdf = new \Mpdf\Mpdf([
	'margin_left' => 20,
	'margin_right' => 15,
	'margin_top' => 35,
	'margin_bottom' => 25,
	'margin_header' => 2,
	'margin_footer' => 5
]);

$mpdf->SetProtection(array('print')); 
$mpdf->SetTitle("Vacation billing");
$mpdf->SetAuthor("W-TECH"); 
$mpdf->SetWatermarkText("test");
$mpdf->showWatermarkText = true;
$mpdf->watermark_font = 'DejaVuSansCondensed';
$mpdf->watermarkTextAlpha = 0.1;
$mpdf->SetDisplayMode('fullpage');




$stylesheet = file_get_contents($_SERVER["DOCUMENT_ROOT"]."/assets/css/invoice_styles.css");
$mpdf->WriteHTML($stylesheet,1);


foreach($this->teachers as $value)
{
    
$billSumaryItems = $value['bill_items']; 
$tblBody = '
<html >
  <head>
    <meta charset="utf-8">
    <title>Example 1</title>
    <link rel="stylesheet" href="style.css" media="all" />
  </head>
  <body>
    <header class="clearfix">
      <div id="logo">
        <img src="logo.png">
      </div>
      <h1>FACTURE '.$value['bill_sumary']['refNumber'].'</h1>
      <div id="company" class="clearfix">
        <div>Agenla Academy</div>
      </div>
      <div id="project">
        
        <div><span>NOM DE L\'ENSEIGNANT</span> '.$value['info']['name'].' '.$value['info']['surname'].'</div>
        <div><span>NUMERO DE TELEPHONE</span>'.$value['info']['phoneNumber'].'</div>
        <div><span>EMAIL</span> <a href="'.$value['info']['phoneNumber'].'">'.$value['info']['email'].'</a></div>
        <div><span>DATE</span>'.$this->date.'</div>
        
      </div>
    </header>
    <main>
      <table>
        <thead>
          <tr>
            <th class="service">N°</th>
            <th class="desc">DESCRIPTION</th>
            <th>VOLUME HORAIRE</th>
            <th>PRIX UNITAIRE</th>
            
            <th>MONTANT</th>
          </tr>
        </thead>
        <tbody>';
    $index=1;
     foreach($billSumaryItems as $item):  

     $tblBody .='<tr>
                <td class="service" >'.$index++.'</td>
                <td class="service" style="text-align:left;">'.$item["paymentDetails"]. ' <br>
                    Volume horaire alloué: '.$item["totalTime"].'<br>
                    Volume horaire réalisé: '.$item["totalTimePreviouslyBilled"]+$item["totalTimeCurrentlyBilled"].' <br>
                    Ecart: '.$item["totalTime"]-($item["totalTimePreviouslyBilled"]+$item["totalTimeCurrentlyBilled"]).'</td>
                
                <td class="service">'.$item["totalTimeCurrentlyBilled"].'</td>
                <td class="service">'.$paymentRate.'</td>
                <td class="service">'.$item["paymentAmount"].'</td>
              </tr>';
     endforeach;
          
        $tblBody .='<tr>
                <td class="service" ></td>
                <td class="service" style="text-align:left;"></td>
                
                <td class="service"></td>
                <td class="service" style="text-align:right;">HT</td>
                <td class="service" style="text-align:right;">'.$value['bill_sumary']['paymentAmount'].'FCFA</td>
              </tr>
              <tr>
                <td class="service" ></td>
                <td class="service" style="text-align:left;"></td>
                
                <td class="service"></td>
                <td class="service" style="text-align:right;">IR (5.5%)</td>
                <td class="service" style="text-align:right;">'.$value['bill_sumary']['paymentAmount']*0.11.'FCFA</td>
              </tr>
              <tr>
                <td class="service" ></td>
                <td class="service" style="text-align:left;"></td>
                
                <td class="service"></td>
                <td class="service" style="text-align:right;">NAP </td>
                <td class="service" style="text-align:right;">'.$value['bill_sumary']['paymentAmount']-$value['bill_sumary']['paymentAmount']*0.11.'FCFA</td>
              </tr>              

</tbody>
      </table>
      

    


    </main>
    <footer>
      Invoice was created on a computer and is valid without the signature and seal.
    </footer>
  </body>
</html>
';



$mpdf->WriteHTML($tblBody);


$mpdf->AddPage();


}












ob_end_clean();
//Close and output PDF document
$mpdf->Output($_SERVER["DOCUMENT_ROOT"].'/impressions/'.preg_replace('/\s+/', '',"facture_enseignant").'-'.date("d-m-Y-H-i").'.pdf', 'F');

?>

        <style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

   <md-dialog style="max-width: 100%;
            max-height: 100%;
    width: 100%;
    height: 100%;
    border-radius: 0;" aria-label="Mango (Fruit)">
  <form ng-cloak>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h2>Impression PV Individuel</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>
      <div  class="md-dialog-content">

          <embed src=<?=$this->serverUrl().'/impressions/'.preg_replace('/\s+/', '',"facture_enseignant").'-'.date("d-m-Y-H-i").'.pdf';?> type="application/pdf" style="width:100%;height:600px;"  />
                     


      </div>
    </md-dialog-content>

    <md-dialog-actions layout="row">

      <span flex></span>
      <md-button ng-click="cancel()">
       Fermer
      </md-button>

    </md-dialog-actions>
  </form>
</md-dialog>