

<link rel="stylesheet" href="js/calendar/fullcalendar/dist/fullcalendar.css"/>
<?= $this->headScript()
        ->prependFile($this->basePath('js/calendar/fullcalendar/dist/gcal.js'))
        ->prependFile($this->basePath('js/calendar/fullcalendar/dist/fullcalendar.min.js'))
        ->prependFile($this->basePath('js/calendar/angular-ui-calendar/src/calendar.js'))
       // ->prependFile($this->basePath('js/calendar/angular/angular.min.js'))
         ->prependFile($this->basePath('js/calendar/moment/min/moment.min.js'))
        ->prependFile($this->basePath('js/calendar/jquery/dist/jquery.min.js'))
        ?>

<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>


<div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">
        
            <div class="row">
                <div class='col-md-6'>
                    <span> <a href="home">[Retour]</a></span>
                    <div ng-show="$ctrl.schedlingUpdate">
                        <button   ng-show=" <?=($this->access('global.system.admin', null))||($this->access('exam.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="updateSchedule(ev,$ctrl.progressionData.scheduledId)"  class="btn btn-primary" ng-disabled="examForm.$invalid || $ctrl.isScheduleValidated" >Modifier</button>
                        <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('exam.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="deleteSchedule($ctrl.progressionData.scheduledId)" class="btn btn-danger" ng-disabled="examForm.$invalid || $ctrl.isScheduleValidated" >Supprimer</button>
                        <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('exam.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="addEvent()" class="btn btn-danger" ng-disabled="examForm.$invalid || $ctrl.isScheduleValidated" >Repéter</button>
                        <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('exam.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="confirmEvent()" class="btn btn-danger" ng-disabled="examForm.$invalid || $ctrl.isScheduleValidated" >Confirmer</button>
                        <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('exam.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="$ctrl.loadForValidation()" class="btn btn-info" ng-disabled="examForm.$invalid" >Vailder</button>
                        <span> <a href="#!/courseProgramming" ng-click="$ctrl.resetSchedule()">Nouvelle Programmation </a></span>
                    </div>
                    
                </div>
        


                
            </div>
</div>
<div class="row">
<div class="col-md-3"> 
    
     <md-content layout-padding >
        <form   name="examForm">

   
        <div>
            <md-input-container class="md-block" flex-gt-sm flex='100'>
                  <label>Classe:</label>
                  <md-autocomplete  md-search-text="$ctrl.searchClasse" 
                                   md-selected-item="$ctrl.selectedClasse"  
                                   md-items="item in $ctrl.query($ctrl.searchClasse)" 
                                   md-item-text="item.code" 
                                   md-min-length="0"
                                   placeholder="Faites de la classe" 
                                   md-selected-item-change="$ctrl.selectedItemChange(item)"
                                   md-input-name="classe"
                                   md-no-asterisk
                                   required>
                      <md-item-template>
                        <span md-highlight-text="$ctrl.searchClasse" md-highlight-flags="^i">{{item.code}}</span>

                      </md-item-template>
                      <md-not-found>
                        Aucun élément correspondant à "{{$ctrl.searchClasse}}" n'a été trouvé.

                      </md-not-found>
                </md-autocomplete>
                      <div ng-messages="examForm.classe.$error">
                          <div ng-message="required">Ce champ est obligatoire</div>
                      </div> 
            </md-input-container >
        </div>
    <div layout-gt-sm='row'>
        <div layout-gt-sm='column' flex="100" >
        <md-input-container>
        <label>Semestre</label>
        <md-select name="semester" ng-model="$ctrl.selectedSem" ng-model-options="{trackBy: '$value.code'}" md-on-open="$ctrl.asignedSemToClasse($ctrl.selectedClasse.code);" ng-change="$ctrl.activateUeSelect(); $ctrl.loadUE($ctrl.selectedClasse,$ctrl.selectedSem.id)"
                    md-no-asterisk required >
            <md-option ng-disabled="true"><em>---Choix du Semestre---</em></md-option>
          <md-option ng-repeat="sem in $ctrl.semesters" ng-value="sem"  >
            {{sem.name}}
          </md-option>
        </md-select>
        <div class="errors" ng-messages="examForm.semester.$error">
          <div ng-message="required">Champ obligatoire</div>
        </div>
      </md-input-container>  
        </div> 

    </div>
     
            <div layout-gt-sm='row' flex="100" style="margin-top:15px;">
        <md-input-container flex="100">
            <label>Unité d'enseignement</label>
            <md-select   name="ue" ng-disabled="!$ctrl.isActivatedUeSelect" ng-model="$ctrl.selectedUe"  
                       ng-model-options="{trackBy: '$value.id'}"  md-on-open="$ctrl.loadUE($ctrl.selectedClasse,$ctrl.selectedSem.id);" 
                       ng-change="$ctrl.loadPedagogicalRegStd($ctrl.selectedUe,$ctrl.selectedClasse);"  md-no-asterisk ng-required="true">
                <md-option ng-disabled="true" ng-selected="true" ng-value="{id:-1}"><em>Choisissez une UE</em></md-option>
              <md-option ng-repeat="ue in $ctrl.ues" ng-value="ue" >
                {{ue.code}}[{{ue.name}}]
              
              </md-option>
            </md-select>
            <div class="errors" ng-messages="examForm.ue.$error">
                <div ng-message="required">Champ obligatoire</div>
            </div>
        </md-input-container>  
            </div>
        <div layout-gt-sm='row' flex="100" style="margin-top:15px;">
        <md-input-container flex="100">
            <label>Matière</label>
            <md-select ng-disabled="!$ctrl.isActivatedMatiereSelect " name="matiere" ng-model="$ctrl.selectedSubject" 
                       ng-model-options="{trackBy: '$value.id'}"  
                       md-on-open="$ctrl.loadSubjects($ctrl.selectedUe);" md-no-asterisk>
              <md-option ng-disabled="true"><em>---Choix de la Matière---</em></md-option>

              <md-option ng-repeat="subject in $ctrl.subjects" ng-value="subject" >
                {{subject.subjectCode}}[{{subject.subjectName}}]
              </md-option>
            </md-select>
            <div class="errors" ng-messages="examForm.matiere.$error">
              <div ng-message="required">Champ obligatoire</div>
            </div>
        </md-input-container>  
        </div> 
            
        <div layout-gt-sm='row' flex="100" style="margin-top:15px;" ng-show='$ctrl.isUpdate' >
            <md-input-container flex="100">
                
             <div layout-gt-sm='column' >
                 <label>Date de debut</label>
                   <md-datepicker name="dateBegining" ng-model="$ctrl.dateBegining" md-placeholder="Date "  ></md-datepicker>   

            </div> 
            </md-input-container>
        </div>   
            

            
            

        <div layout-gt-sm='row' flex="100" style="margin-top:15px;">
        <md-input-container flex="100">
            <label>Salles de cours {{$ctrl.classroom}}</label>
<select ng-model="selectedChoice">
    <optgroup ng-repeat="group in flattenedItems" label="{{group.name}}">
        <option ng-repeat="choice in group.choices" value="{{choice.id}}">
            {{choice.name}}
        </option>
    </optgroup>
</select>            
            
            
            <ui-select name="classroom"  ng-model="$ctrl.classroom" theme="bootstrap" style="width: 230px;" on-select="handleSelection($select.selected,$select)" ng-required="true">
              <ui-select-match placeholder="Sélectionner...">{{$select.selected.name}}</ui-select-match>
              <ui-select-choices repeat="item in flattenedItems | filter: $select.search" ng-value="$select.selected">
                <div ng-style="{'padding-left': (item.level * 15) + 'px'}"
                     ng-class="{'text-muted': !item.isLeaf || item.level != 2}"
                     >
                  {{item.name}}
                </div>
              </ui-select-choices>
            </ui-select>
            <div class="errors" ng-messages="examForm.classroom.$error">
              <div ng-message="required">Champ obligatoire</div>
            </div>
        </md-input-container>  
        </div>            
        <div layout-gt-sm='row' flex="100" style="margin-top:15px;">
        <md-input-container flex="100">
            <label>Type de cours</label>
            <md-select name="scheduleType" ng-model="$ctrl.scheduleType"  md-no-asterisk ng-required='true'>
              <md-option ng-disabled="true"><em>---Type de programmation---</em></md-option>
              <md-option value="CM">Cours Magistral</md-option>
              <md-option value="TD">Travaux Dirigés</md-option>
              <md-option value="TP">Travaux Pratiques</md-option>
              <md-option value="CC">Controle continnue</md-option>
              <md-option value="EXAM">Examen</md-option>
              <md-option value="STAGE">STAGE</md-option>
              <md-option value="ECN">ECN</md-option>

            </md-select>
            <div class="errors" ng-messages="examForm.scheduleType.$error">
              <div ng-message="required">Champ obligatoire</div>
            </div>
        </md-input-container>  
        </div> 


        <div ng-show="!$ctrl.schedlingUpdate" layout-gt-sm='row' flex="100" style="margin-top:30px">
            <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('programing.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="$ctrl.courseSchedulingDialog($ctrl.times)" class="btn btn-danger" ng-disabled="examForm.$invalid" >Enrégistrer</button>
        
        </div>            
                 
        <div ng-show="!$ctrl.schedlingUpdate" layout-gt-sm='row' flex="100" style="margin-top:30px">
            <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('programing.create', null))?true:false?> && $ctrl.isUpdate" type="button" ng-click="updateSchedule(ev,$ctrl.progressionData.scheduledId)" class="btn btn-danger" ng-disabled="examForm.$invalid" >Modifier</button>
        
        </div>  
</form>
  </md-content>   
    
    <!-- comment --></div>

<div class=" col-md-9 ">
    <div class="form-view">
        <div   ng-cloak class="md-inline-form">



</div>
        

        
<p>&nbsp;</p>
              <!--tabs widget-->
                <div class="row" >
                    <ul class="nav nav-tabs">
                        <li class="active"><a href=""> Calendrier de planification  &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i title='Calendrier de planification' style="color:lightgrey;  font-size: 22px; cursor: pointer;" class="fa fa-refresh"   ng-click="$ctrl.selectedItemChange($ctrl.selectedClasse)"></i></a></li>
                       
                            
                            
                            <div class="pull-right" style="color:lightgrey; margin-left: 10px; margin-right: 2px; margin-top: 10px;">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                                   --- Actions ---
                                                    <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu pull-right" role="menu">
                                                    <li><a href="" ng-click="printSchedule()"><span>Imprimer le planing</span></a>
                                                    </li>
                                                    <li><a href="" ng-click="saveChoices($ctrl.registeredStd)"><span>Visualiser</span></a>
                                                    </li>
                                                    <!--<li><a href="" ng-click="$ctrl.clotureCalculNotes($ctrl.selectedUe.ue_class_id)"><span>Imprimer liste étudiants</span></a>
                                                    </li> -->
                                                </ul>
                                            </div>
                            </div>                            

                    </ul>

                    <div ui-calendar="uiConfig.calendar" ng-model="eventSources" calendar="calendar" class="span8 calendar" id="calendar"></div>
                 </div>
                <!--End tab-->
                
            </div>  
        </div>
</div>
