


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}

li.active a.ng-binding {
  color: #000 !important;
	background-color: #eeeeee !important;
	text-decoration: none;
}

</style>
    
<div ng-cloak novalidate> 
    <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init();"> 
        <a ng-show= "$ctrl.showbillDetails" href="#!/subjectBilling">[Retrour]</a>
        <a ng-show= "!$ctrl.showbillDetails" href="#!/teacher-follow-up">[Retrour]</a>
            <div class="row text-align-center"> Facturation des frais de vacation</div>
            <div class="row">
                <div class='col-md-4'>

                </div>
                <div class="col-md-2"></div>

                
                <div class="pul-middle" >
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Autres options 
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <li><a href="" ng-click="$ctrl.showPrintTeacherBill(1)"><span>Imprimer la facture</span></a>
                                        </li>
                                        <li><a href="" ng-click=""><span></span></a>
                                        </li>
                                        <!--<li><a href="" ng-click="$ctrl.clotureCalculNotes($ctrl.selectedUe.ue_class_id)"><span>Imprimer liste étudiants</span></a>
                                        </li> -->
                                    </ul>
                                </div>
                </div>
                
               
            </div>
        </div>

<div class="form-view-main">
    <div class="form-view">


<md-content layout-padding >

    <form   name="examForm" >
        <div layout-gt-sm='row'ng-hide="$ctrl.isBulkBilling" >

            <div class = "col-xs-6" >
                <div layout-gt-sm='row' >
                    <md-input-container class="md-block" flex-gt-sm>
                        <label>Enseignant:</label>
                        <md-autocomplete  md-search-text="$ctrl.searchTeacher" 
                                         md-selected-item="$ctrl.selectedTeacher"  
                                         md-items="item in $ctrl.queryTeacher($ctrl.searchTeacher)" 
                                         md-item-text="item.name" 
                                         md-min-length="0"
                                         placeholder="" 
                                         md-selected-item-change="$ctrl.loadBills($ctrl.selectedTeacher,$ctrl.isBulkBilling)"
                                         md-input-name="Teacher"
                                         md-no-asterisk
                                         ng-disabled="$ctrl.showbillDetails"
                                         ng-required="!$ctrl.isBulkBilling">
                            <md-item-template>
                              <span md-highlight-text="$ctrl.searchTeacher" md-highlight-flags="^i">{{item.name}}</span>

                            </md-item-template>
                            <md-not-found>
                              Aucun élément correspondant à "{{$ctrl.searchTeacher}}" n'a été trouvé.

                            </md-not-found>
                        </md-autocomplete>
                            <div ng-messages="examForm.classe.$error">
                                <div ng-message="required">Ce champ est obligatoire</div>
                            </div> 
                    </md-input-container >
                </div>

          
  
            <div layout layout-sm="row">
                
                <md-input-container flex="flex" style="width: 20%; margin-top: 15px;" >
                  
                    <label>Cout du transport:</label>
                    <input type='text'  name="transport_rate" ng-model="$ctrl.xport.amount" width='80%'  md-no-asterisk required />
                        <div ng-messages="examForm.transport_rate.$error">
                            <div ng-message="required">le champ montant  est obligatoire</div>
                           
                        </div>
                    </md-input-container>                 
                
                
                    <md-input-container flex="flex" style="width: 20%; margin-top: 15px;">
                    
                    <label>Nombre de séjours </label>
                    <md-select name="stay"  ng-model="$ctrl.xport.nbStay;" md-no-asterisk ng-required="true">
                        <md-option  ng-repeat="nbStay in $ctrl.nbStays" ng-value="nbStay.id" >
                        {{nbStay.id}}
                       </md-option>


                    </md-select>
                    <div class="errors" ng-messages="examForm.stay.$error">
                        <div ng-message="required">Champ obligatoire</div>
                      </div>
                    </md-input-container> 

            </div> 
                
            <div layout layout-sm="row">
                <div >
                   
                    <md-checkbox  ng-model="$ctrl.xport.isXportSupportingDocsAvailable" ng-disabled="" aria-label="Checkbox Indeterminate" ng-
                                   
                        ng-true-value="1"
                        ng-false-value="0"             
                        class="md-primary">

                    </md-checkbox> 
                    <i>Pièces justificatives de transport disponible</i>

                </div>                    
                    
            </div>
           
            </div>

            <div class = "col-xs-6"  >
                <!-- Display examlis on a table -->
              <div class="row">

                </div>
                
               
            </div>           
        </div>

        <div layout-gt-sm='row'>
            <div class="col-md-2 pull-left">
                

            </div>
            <div class="col-md-10 text-right">
                <i>Générer toutes les factures en attente</i>
                <md-checkbox  ng-model="$ctrl.isBulkBilling" ng-disabled="" aria-label="Checkbox Indeterminate" ng-
                              ng-change="$ctrl.loadBills($ctrl.selectedTeacher,$ctrl.isBulkBilling)" 
                    ng-true-value="1"
                    ng-false-value="0"             
                    class="md-primary">

                </md-checkbox> 
                
                <button class="btn btn-danger" ng-click="$ctrl.loadTeacherBill($ctrl.selectedTeacher,$ctrl.isBulkBilling)" ng-hide = "$ctrl.showbillDetails" ng-disabled="examForm.$invalid"><i class="fa fa-refresh" ></i>&nbsp;Générer la facture</button>&nbsp;&nbsp;&nbsp;
                <button class="btn btn-danger" ng-click="$ctrl.deliberation()" ><i class="fa fa-save" ></i>&nbsp;Valider le paiement</button>
            </div>
        </div>
      

    </form>
    </md-content>
<!----------------------------------------------------------------------------------------------->


<p></p>
    <uib-tabset>
      <uib-tab > 
                    <uib-tab-heading>
                        <span>Liste factures</span>
                                               
                    </uib-tab-heading>
                    <div id =" tab1">
                        <table class="table" style="font-size:1em; background-color: #dfe4ea; color: #0c2461;" ng-show="tableBillsShow===1">
                        <thead>

                            <tr class="bg-primary">
                                <th class="col-xs-1 align-middle" ></th>
                                <th class=" align-middle" >N° </th>
                                <th class=" align-middle">Volume Alloué</th>
                                <th class=" align-middle">Volume Réalisé</th>
                                <th class=" align-middle">Montant</th>
                                <th class=" align-middle">Date</th>
                                <th class=" align-middle">statut</th>
                                <th></th>

                            </tr>
                       </thead>
                        <tbody>

                            <tr ng-repeat="bill in bills" style="font-size:0.8em;">
                              <td  class="col-xs-1"> 
                                    <md-checkbox  ng-model="bills.selected" ng-disabled="isDisabledCheckbox" aria-label="Checkbox Indeterminate" 
                                                  ng-true-value="'P'"
                                                  ng-false-value="'A'"             
                                                  class="md-primary">

                                    </md-checkbox>                              

                              </td>
                              <td nclass="col-xs-1"><a ng-href="home#!/subjectBilling/{{bill.refNumber}}" ng-bind="bill.refNumber"></a></td>
                              <td ng-bind="bill.totalTimeScheduled +'H'" class="col-xs-3"></td>
                              <td ng-bind="bill.totalTimePaid +'H'" class="col-xs-3"></td>
                              <td ng-bind="bill.paymentAmount" class="col-xs-1" ng-class="{'zf-red': (exam.isMarkRegistered!==1)}"></td>
                              <td ng-bind="$ctrl.formatDate(bill.date.date) | date:'dd/MM/yyyy'" class="col-xs-2"></td>
                              <td ng-bind="bill.status===1?'Payé':'En cours...'"></td>
                              <td>  
                                    <div class="btn-group">

                                        <button  type="button" ng-click="$ctrl.deleteBill(bill.id)" class="btn btn-warning  btn-xs" ><i class="fa fa-trash-o"></i></button>
                                    </div>
                              </td>
                            </tr>

                        </tbody>

                        </table>
                    </div>
      </uib-tab>
           
              <uib-tab>
                <uib-tab-heading>
                    <span>Imprimer les factures</span>
                </uib-tab-heading>
                <div class="tab-container"> 
                    
    <div layout-gt-sm='column' >
        <fieldset class="standard">
            <legend>Choisir une période</legend>
            <div layout-gt-sm="row">   
                <h4 id="datepicker-header">Date de début</h4>
                  <md-datepicker ng-model="$ctrl.billingDate" md-min-date="acadyr.startingDate" md-max-date="acadyr.endingDate" md-placeholder="Date de début">

                  </md-datepicker>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <h4 id="datepicker-header">Date de fin</h4>
                  <md-datepicker ng-model="$ctrl.billingEndingDate" md-min-date="acadyr.startingDate" md-max-date="acadyr.endingDate" md-placeholder="Date de fin">

                  </md-datepicker>
                
               
               
            </div>
            <div layout-gt-sm="row" class=""">
                 <button class="btn btn-inverse" ng-click="$ctrl.deliberation()" ><i class="fa fa-save" ></i>&nbsp;Imprimer</button>
            </div>
        </fieldset>
    </div>                    
                </div>
            </uib-tab>        
    </uib-tabset>
                    <div id="tab2"></div>
                 </div>
                <!--End tab-->
                
              
                
            </div>  
        </div>

</div>