<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<style>
* {
	margin: 0;
	padding: 0
}

html {
	height: 100%
}

h2{
	color: #2F8D46;
}
#form {
	text-align: left;
	position: relative;
	margin-top: 20px
}

#form fieldset {
	background: white;
	border: 0 none;
	border-radius: 0.5rem;
	box-sizing: border-box;
	width: 100%;
	margin: 0;
	padding-bottom: 20px;
	position: relative
}

.finish {
	text-align: center
}

#form fieldset:not(:first-of-type) {
	display: none
}

#form .previous-step, .next-step {
	width: 100px;
	font-weight: bold;
	color: white;
	border: 0 none;
	border-radius: 0px;
	cursor: pointer;
	padding: 10px 5px;
	margin: 10px 5px 10px 0px;
	float: right
}

.form, .previous-step {
	background: #616161;
}

.form, .next-step {
	background: #2F8D46;
}

#form .previous-step:hover,
#form .previous-step:focus {
	background-color: #000000
}

#form .next-step:hover,
#form .next-step:focus {
	background-color: #581845;
}

.text {
	color: #2F8D46;
	font-weight: normal
}

#progressbar {
	margin-bottom: 10px;
	overflow: hidden;
	color: lightgrey
}

#progressbar .active {
	color: #581845;
}

#progressbar li {
	list-style-type: none;
	font-size: 15px;
	width: 25%;
	float: left;
	position: relative;
	font-weight: 400
}

#progressbar #step1:before {
	content: "1"
}

#progressbar #step2:before {
	content: "2"
}

#progressbar #step3:before {
	content: "3"
}

#progressbar #step4:before {
	content: "4"
}

#progressbar li:before {
	width: 25px;
	height: 25px;
	line-height: 22px;
	display: block;
	font-size: 10px;
	color: #ffffff;
	background: lightgray;
	border-radius: 50%;
	margin: 0 auto 0px auto;
	padding: 2px
}

#progressbar li:after {
	content: '';
	width: 100%;
	height: 2px;
	background: lightgray;
	position: absolute;
	left: 0;
	top: 25px;
	z-index: -1
}

#progressbar li.active:before,
#progressbar li.active:after {
	background: #581845;
}

.progress {
	height: 1px;
            margin-top:-43px;
}

.progress-bar {
	background-color: #581845;
}

</style>
<div class=" bg-light  rounded-3 "      );
            background-size: cover;
            color: #581845;
">
    <br /><br />
<!DOCTYPE html>

	<div class="container">
            <div class="row">
            <div class="col-8">

		<div class="row justify-content-center">
			<div class="col-11  text-center p-0 mt-1 mb-1">
				<div class="px-0 pt-1 pb-0 mt-1 mb-1">
					<form id="form">
						<ul id="progressbar">
							<li class="active" id="step1">
								<strong>Step 1</strong>
							</li>
							<li id="step2"><strong>Step 2</strong></li>
							<li id="step3"><strong>Step 3</strong></li>
							<li id="step4"><strong>Step 4</strong></li>
						</ul>
						<div class="progress">
							<div class="progress-bar"></div>
						</div> <br>
						<fieldset>
							<h2>Identification du candidat</h2>
            <div class="row p-3" style=' color:#636e72;'>

                <div class="col-md-9">

                          <div layout-gt-sm="row"  style='margin-top: 0px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Nom:</label>
                            <input name="nom" ng-model="$ctrl.student.nom" required />
                                <div ng-messages="stdRegistrationForm.nom.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>

                                </div>   
                          </md-input-container>
                        </div>
                    <div layout-gt-sm="row"  style='margin-top: -35px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Prénom:</label>
                            <input name="prenom" ng-model="$ctrl.student.prenom"   />
                                <div ng-messages="stdRegistrationForm.prenom.$error">
                                    <div ng-message="required">le champ Prénom est obligatoire</div>
                                    
                                </div> 
                          </md-input-container>
                        </div>
                        <div layout-gt-sm="row" style='margin-top: -35px;'>
                            <md-input-container class="md-block" flex-gt-sm>
                              <label>Date de naissance</label>
                              <md-datepicker   ng-model="$ctrl.student.dateOfBirth" ng-change="dateChanged()"  required ></md-datepicker>
                              <input type="hidden" name="dateOfBirth"  value={{$ctrl.student.dateOfBirth}}   />
                              <div ng-messages="stdRegistrationForm.dateOfBirth.$error">
                                <div ng-message="valid">Format de date invalide</div>
                                <div ng-message="required">le champ date de naissance est obligatoire</div>

                              </div>
                            </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Ville de naissance:</label>
                            <input name="bornAt" ng-model="$ctrl.student.bornAt" required />
                                <div ng-messages="stdRegistrationForm.bornAt.$error">
                                    <div ng-message="required">le champ Prénom est obligatoire</div>
                                    
                                </div> 
                          </md-input-container>
                        </div>
                          <div layout-gt-sm="row" style='margin-top: -35px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Sexe</label>
                                    <md-select name='gender' ng-model="$ctrl.student.gender" required  >
                                        <md-option value="M">Masculin</md-option>
                                        <md-option value="F">Féminin</md-option>
                                    </md-select>
                                    <div ng-messages="stdRegistrationForm.gender.$error">
                                        <div ng-message="required">le champ Sexe est obligatoire</div>

                                    </div>                                    
                                </md-input-container>
                          
     
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Numéro de téléphone</label>
                                    <input name="phoneNumber" ng-model="$ctrl.student.phoneNumber" ng-pattern="/^[0-9]{9}$/" required />
                                    <div ng-messages="stdRegistrationForm.phoneNumber.$error">
                                        <div ng-message="required">le champ numéro de téléphone est obligatoire</div>
                                        <div ng-message="pattern">Numéro de téléphone invalid</div>
                         
                                    </div>
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Email</label>
                                    <input name="email" ng-model="$ctrl.student.email"  type="email" required  minlength="10" maxlength="100" ng-pattern="/^.+@.+\..+$/"  />
                                    <div ng-messages="stdRegistrationForm.email.$error" role="alert">
                                       <div ng-message-exp="['required', 'minlength', 'maxlength', 'pattern']">
                                          votre email doit contenir au moins 10 et être semblable à un email.
                                        </div>
                                    </div>
                                </md-input-container>
   
                        </div>


                          <div layout-gt-sm="row" style='margin-top: -35px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Langue</label>
                                    <md-select name ='language' ng-model="$ctrl.student.language" required >
                                        <md-option value="FR">Français</md-option>
                                        <md-option value="ANG">Anglais</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.language.$error">
                                        <div ng-message="required">le champ Langue est obligatoire</div>
                                    </div> 
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Nationalité</label>
                                    <md-select name='nationality' ng-model="$ctrl.student.nationality" required  >
                                        <md-option ng-repeat="country in $ctrl.countries" ng-value="country.sortname" >
                                          {{country.name}}
                                        </md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.nationality.$error">
                                        <div ng-message="required">le champ Nationalité est obligatoire</div>
                                    </div>                                     
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Région d'origine</label>
                                    <md-select name='regionOfOrigin' ng-model="$ctrl.student.regionOfOrigin" md-on-open="$ctrl.getRegions($ctrl.student.nationality)" required >
                                        <md-option ng-repeat="region in $ctrl.regions" ng-value="region.name" >
                                          {{region.name}}
                                        </md-select>
                                    <div ng-messages="stdRegistrationForm.regionOfOrigin.$error">
                                        <div ng-message="required">le champ Religion est obligatoire</div>
                                    </div> 
                                </md-input-container>

                          </div>
   
                          <div layout-gt-sm="row" style='margin-top: -15px;'>

                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Réligion</label>
                                    <md-select name='religion' ng-model="$ctrl.student.religion" required >
                                        <md-option value="CATHOLIQUE">Catholique</md-option>
                                        <md-option value="PROTESTANT">Protestant</md-option>
                                        <md-option value="MUSULMAN">Musulman</md-option>
                                        <md-option value="AUTRE">Autres</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.religion.$error">
                                        <div ng-message="required">le champ Religion est obligatoire</div>
                                    </div> 
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Situation matrimoniale</label>
                                    <md-select name='maritalStatus' ng-model="$ctrl.student.maritalStatus" required >
                                        <md-option value="CELIBATAIRE">Célibataire</md-option>
                                        <md-option value="MARIÉ(E)">Marié(e)</md-option>
                                        <md-option value="DIVORCÉ(E)">Divorcé(e)</md-option>
                                        <md-option value="VEUF">Veuf</md-option>
                                        <md-option value="VEUVE">Veuve</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.maritalStatus.$error">
                                        <div ng-message="required">le champ Situation matrimoniale est obligatoire</div>
                                    </div> 
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Situation d'emploi</label>
                                    <md-select name='workingStatus' ng-model="$ctrl.student.workingStatus" required >
                                        <md-option value="EMPLOYÉ(E)">Employé</md-option>
                                        <md-option value="SANS EMPLOI">Sans emploi</md-option>

                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.workingStatus.$error">
                                        <div ng-message="required">le champ Situation d'emploi est obligatoire</div>
                                    </div> 
                                </md-input-container>                              

                          </div>                        

                        </div>                        
                        <div class="col-md-3">
                          <span class="small text-danger">Taille limite de la photo:65KO </span>
                          <img style="width:150px; height:150px;" ng-src="{{$ctrl.student.imageSrc;}}" />      
                          <md-input-container class="md-block" flex-gt-sm>
                            
                              <input  type ="file" name="imageSrc" ng-file-select="onFileSelect($files)" ng-model="$ctrl.student.imageSrc" accept="image/*"   />
                                <div ng-messages="stdRegistrationForm.imageSrc.$error">
                                    <div ng-message="required">le champ photo est obligatoire</div>
                                    <div ng-message="extension">Format de fichier invalid</div>
                                    
                                </div> 
                          </md-input-container>                            
   
                        </div>
                                                            

                    </div>

                                                                                
							<input type="button" name="next-step"
								class="next-step" value="Next Step" />
						</fieldset>
						<fieldset>
							<h2>Welcome To GFG Step 2</h2>
							<input type="button" name="next-step"
								class="next-step" value="Next Step" />
							<input type="button" name="previous-step"
								class="previous-step"
								value="Previous Step" />
						</fieldset>
						<fieldset>
							<h2>Welcome To GFG Step 3</h2>
							<input type="button" name="next-step"
								class="next-step" value="Final Step" />
							<input type="button" name="previous-step"
								class="previous-step"
								value="Previous Step" />
						</fieldset>
						<fieldset>
							<div class="finish">
								<h2 class="text text-center">
									<strong>FINISHED</strong>
								</h2>
							</div>
							<input type="button" name="previous-step"
								class="previous-step"
								value="Previous Step" />
						</fieldset>
					</form>
				</div>
			</div>
		</div>
            </div><!-- comment -->
            <div class="col-4">
                <div class="alert alert-danger">
                    <p><i class="fa-solid fa-bell"></i> &nbsp; Vous avez soumis un dossier de candidature et vous souhaitez avoir des information concernant son état de traitement. utiliser votre code d'accès pour vous connecter. </p>
                </div>
                
                
            </div>
            </div>
	</div>


</div>

        <?= $this->inlineScript()

        ->prependFile($this->basePath('js/jquery-3.7.0.min.js'))
        ?>
<script type="text/javascript">
$(document).ready(function () {
	var currentGfgStep, nextGfgStep, previousGfgStep;
	var opacity;
	var current = 1;
	var steps = $("fieldset").length;

	setProgressBar(current);

	$(".next-step").click(function () {

		currentGfgStep = $(this).parent();
		nextGfgStep = $(this).parent().next();

		$("#progressbar li").eq($("fieldset")
			.index(nextGfgStep)).addClass("active");

		nextGfgStep.show();
		currentGfgStep.animate({ opacity: 0 }, {
			step: function (now) {
				opacity = 1 - now;

				currentGfgStep.css({
					'display': 'none',
					'position': 'relative'
				});
				nextGfgStep.css({ 'opacity': opacity });
			},
			duration: 500
		});
		setProgressBar(++current);
	});

	$(".previous-step").click(function () {

		currentGfgStep = $(this).parent();
		previousGfgStep = $(this).parent().prev();

		$("#progressbar li").eq($("fieldset")
			.index(currentGfgStep)).removeClass("active");

		previousGfgStep.show();

		currentGfgStep.animate({ opacity: 0 }, {
			step: function (now) {
				opacity = 1 - now;

				currentGfgStep.css({
					'display': 'none',
					'position': 'relative'
				});
				previousGfgStep.css({ 'opacity': opacity });
			},
			duration: 500
		});
		setProgressBar(--current);
	});

	function setProgressBar(currentStep) {
		var percent = parseFloat(100 / steps) * current;
		percent = percent.toFixed();
		$(".progress-bar")
			.css("width", percent + "%")
	}

	$(".submit").click(function () {
		return false;
	})
});

</script>

