<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<style>
[ng\:cloak], [ng-cloak], .ng-cloak {
    display: none;
}

.submitForm {
	width: 100%;
}

.validation{
	padding-top: 5px;
	display: none;
	color: red;
}

.input-error {
  display: block;
  font-size: 12px;
}

</style>
<div class=" bg-light  rounded-3 "      );
            background-size: cover;
            color: #581845;
" ng-controller="formCtrl as $ctrl">
    <br /><br />
<!DOCTYPE html>

	<div class="container">
            <div class="row">
            <div class="col-8">
					
            <div class="row p-3" style=' color:#636e72;'>
                

		<md-progress-linear md-mode="determinate" class="md-accent" value="{{progressValue}}"></md-progress-linear>                

                <div class="col-md-9">
        <md-content class="md-padding" layout-xs="column" >
            <form name="stdRegistrationForm" id="submitForm" class="submitForm form-validation" role="form" novalidate>
                <div class="animate-switch-container" ng-switch on="stage" ng-class="{forward: direction, backward:!direction}">
<!--|==========================================================================
					| Stag0
|==========================================================================   -->                 
	    <md-card  class="card-40-center animate-switch stepCard" md-theme-watch ng-switch-default ng-class="{forward: direction, backward:!direction}">
		<md-card-title>
		  <md-card-title-text>
			<span class="md-headline">Identification du candidat</span>                
								<!-- first name -->
                <md-card-content>
                    <div layout="row">                
                <div class="animate-switch-container" ng-switch on="stage" ng-class="{forward: direction, backward:!direction}">

                          <div layout-gt-sm="row"  style='margin-top: 0px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Nom:</label>
                            <input name="nom" ng-model="$ctrl.student.nom" required />
                              <div ng-messages="stdRegistrationForm.nom.$error">
                                <div ng-message="required">le champ nom est obligatoire</div>
                              </div>                            
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.nom.$error.required}">
                                    Le champ nom est obligatoire
                                </div>   
                          </md-input-container>
                        </div>
                    <div layout-gt-sm="row"  style='margin-top: -35px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Prénom:</label>
                            <input name="prenom" ng-model="$ctrl.student.prenom"   />

                          </md-input-container>
                    </div>
                        <div layout-gt-sm="row" style='margin-top: -35px;'>
                            <md-input-container class="md-block" flex-gt-sm>
                              <label>Date de naissance</label>
                              <md-datepicker   ng-model="$ctrl.student.dateOfBirth" ng-change="dateChanged()" required ></md-datepicker>
                              <input type="hidden" name="dateOfBirth"  value={{$ctrl.student.dateOfBirth}}   />
                              <div ng-messages="stdRegistrationForm.dateOfBirth.$error">
                                <div ng-message="valid">Format de date invalide</div>
                                <div ng-message="required">le champ date de naissance est obligatoire</div>
                              </div>
                                <div class="validation" ng-class="{'input-error': formValidation && !$ctrl.student.dateOfBirth}">
                                    Le champ date de naissance est obligatoire
                                </div>                              
                            </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Ville de naissance:</label>
                            <input name="bornAt" ng-model="$ctrl.student.bornAt" required />
                                <div ng-messages="stdRegistrationForm.bornAt.$error">
                                    <div ng-message="required">le champ Prénom est obligatoire</div>
                                </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.bornAt.$error.required}">
                                    Le champ lieu de naissance est obligatoire
                                </div>                            
                          </md-input-container>
                        </div>
                          <div layout-gt-sm="row" style='margin-top: -35px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Sexe</label>
                                    <md-select name='gender' ng-model="$ctrl.student.gender" required  >
                                        <md-option value="M">Masculin</md-option>
                                        <md-option value="F">Féminin</md-option>
                                    </md-select>
                                    <div ng-messages="stdRegistrationForm.gender.$error">
                                        <div ng-message="required">le champ Sexe est obligatoire</div>

                                    </div>    
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.gender.$error.required}">
                                    Le champ genre est obligatoire
                                </div>                                    
                                </md-input-container>
                          
     
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Numéro de téléphone</label>
                                    <input name="phoneNumber" ng-model="$ctrl.student.phoneNumber" ng-pattern="/^[0-9]{9}$/" required />
                                    <div ng-messages="stdRegistrationForm.phoneNumber.$error">
                                        <div ng-message="required">le champ numéro de téléphone est obligatoire</div>
                                        <div ng-message="pattern">Numéro de téléphone invalid</div>
                                    </div>
                                <div class="validation" ng-class="{'input-error': formValidation &&  stdRegistrationForm.phoneNumber.$error.required }">
                                    Numéro de téléphone obligatoire
                                </div>                                    
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.phoneNumber.$dirty && stdRegistrationForm.phoneNumber.$error.pattern }">
                                    format du numéro de téléphone incorrect
                                </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Email</label>
                                    <input name="email" ng-model="$ctrl.student.email"  type="email" required  minlength="10" maxlength="100" ng-pattern="/^.+@.+\..+$/"  />
                                    <div ng-messages="stdRegistrationForm.email.$error" role="alert">
                                       <div ng-message-exp="['required', 'minlength', 'maxlength', 'pattern']">
                                          votre email doit contenir au moins 10 et être semblable à un email.
                                        </div>
                                    </div>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.email.$error.required}">
                                    email est obligatoire
                                </div>   
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.email.$dirty&& stdRegistrationForm.email.$error.pattern}">
                                    format email incorrect
                                </div>                                     
                                </md-input-container>
   
                        </div>


                          <div layout-gt-sm="row" style='margin-top: -35px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Langue</label>
                                    <md-select name ='language' ng-model="$ctrl.student.language" required >
                                        <md-option value="FR">Français</md-option>
                                        <md-option value="ANG">Anglais</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.language.$error">
                                        <div ng-message="required">le champ Langue est obligatoire</div>
                                    </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.language.$error.required}">
                                    langue obligatoire
                                </div>                                     
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Nationalité</label>
                                    <md-select name='nationality' ng-model="$ctrl.student.nationality"   >
                                        <md-option ng-repeat="country in $ctrl.countries" ng-value="country.sortname" >
                                          {{country.name}}
                                        </md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.nationality.$error">
                                        <div ng-message="required">le champ Nationalité est obligatoire</div>
                                    </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.nationality.$error.required}">
                                    nationalité obligatoire
                                </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Région d'origine</label>
                                    <md-select name='regionOfOrigin' ng-model="$ctrl.student.regionOfOrigin" md-on-open="$ctrl.getRegions($ctrl.student.nationality)"  >
                                        <md-option ng-repeat="region in $ctrl.regions" ng-value="region.name" >
                                          {{region.name}}
                                        </md-select>
                                    <div ng-messages="stdRegistrationForm.regionOfOrigin.$error">
                                        <div ng-message="required">le champ Religion est obligatoire</div>
                                    </div>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.regionOfOrigin.$error.required}">
                                    region d'aorigine obligatoire
                                </div>                                    
                                </md-input-container>

                          </div>
   
                          <div layout-gt-sm="row" style='margin-top: -15px;'>

                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Réligion</label>
                                    <md-select name='religion' ng-model="$ctrl.student.religion" required >
                                        <md-option value="CATHOLIQUE">Catholique</md-option>
                                        <md-option value="PROTESTANT">Protestant</md-option>
                                        <md-option value="MUSULMAN">Musulman</md-option>
                                        <md-option value="AUTRE">Autres</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.religion.$error">
                                        <div ng-message="required">le champ Religion est obligatoire</div>
                                    </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.religion.$error.required}">
                                    religion obligatoire
                                </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Situation matrimoniale</label>
                                    <md-select name='maritalStatus' ng-model="$ctrl.student.maritalStatus" required >
                                        <md-option value="CELIBATAIRE">Célibataire</md-option>
                                        <md-option value="MARIÉ(E)">Marié(e)</md-option>
                                        <md-option value="DIVORCÉ(E)">Divorcé(e)</md-option>
                                        <md-option value="VEUF">Veuf</md-option>
                                        <md-option value="VEUVE">Veuve</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.maritalStatus.$error">
                                        <div ng-message="required">le champ Situation matrimoniale est obligatoire</div>
                                    </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.maritalStatus.$error.required}">
                                    situation matrimoniale obligatoire
                                </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Situation d'emploi</label>
                                    <md-select name='workingStatus' ng-model="$ctrl.student.workingStatus" required >
                                        <md-option value="EMPLOYÉ(E)">Employé</md-option>
                                        <md-option value="SANS EMPLOI">Sans emploi</md-option>

                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.workingStatus.$error">
                                        <div ng-message="required">le champ Situation d'emploi est obligatoire</div>
                                    </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.workingStatus.$error.required}">
                                    situation d'emploi obligatoire
                                </div>                                    
                                </md-input-container>                              

                          </div> 
                    </div>
                    </div>
                    <!-- comment --></md-card-content>
                    <!-- navigation -->
                        <md-card-title-media></md-card-title-media>   
                    </md-card-title>
                                <!-- buttons -->
                        <md-card-actions layout="row" layout-align="end center">
                                <button type="button" class="md-raised md-warn md-button md-ink-ripple" ng-click="back('')">
                                        Back
                                </button>
                                <button type="button" class="md-raised md-warn md-button md-ink-ripple" ng-click="next('stage1')">		Next
                                </button>
                        </md-card-actions>  
                                </md-card>
                    
					<!--
					|==========================================================================
					| Stage 1
					|==========================================================================
					-->
					<md-card  class="card-40-center animate-switch stepCard" md-theme-watch ng-switch-when="stage1">
						<md-card-title>
							<md-card-title-text>
								<span class="md-headline">Enter your personal details</span>

								<!-- first name -->
								<md-card-content>
									<div layout="row">

										<!-- First Name -->
										<md-input-container flex="50" >
											<label>First Name</label>
											<input required name="firstName" ng-model="formParams.firstName">
											<div class="validation" ng-class="{'input-error': formValidation && multiStepForm.firstName.$error.required}">This is required.</div>
										</md-input-container>

										<!-- Last Name -->
										<md-input-container flex="50" >
											<label>Last Name</label>
											<input required name="lastName" ng-model="formParams.lastName">
											<div class="validation" ng-class="{'input-error': formValidation && multiStepForm.lastName.$error.required}">This is required.</div>
										</md-input-container>

									</div>

									<div layout="row">
										<!-- Gender -->
										<md-input-container flex="100">
								          <label>Gender </label>

								          	<md-select name="genderValue" ng-model="formParams.genderValue" required>
									            <md-option><em>None</em></md-option>
									            <md-option ng-repeat="sexe in genders" ng-value="sexe">
									              {{sexe}}
									            </md-option>
									        </md-select>
									        <div class="validation" ng-class="{'input-error': formValidation && multiStepForm.genderValue.$error.required}">This is required.</div>
								        </md-input-container>
									</div>
								</md-card-content>

								<!-- navigation -->
								<md-card-title-media></md-card-title-media>

						</md-card-title>

						<!-- buttons -->
						<md-card-actions layout="row" layout-align="end center">
				        	<button type="button" class="md-raised md-warn md-button md-ink-ripple" ng-click="back('')">
				        		Back
				        	</button>
				        	<button type="button" class="md-raised md-warn md-button md-ink-ripple" ng-click="next('stage2')">		Next
				        	</button>
				        </md-card-actions>

					</md-card>                    
                </div>
                </form>
                </md-content>

                        </div>                        
                        <div class="col-md-3">
                          <span class="small text-danger">Taille limite de la photo:65KO </span>
                          <img style="width:150px; height:150px;" ng-src="{{$ctrl.student.imageSrc;}}" />      
                          <md-input-container class="md-block" flex-gt-sm>
                            
                              <input  type ="file" name="imageSrc" ng-file-select="onFileSelect($files)" ng-model="$ctrl.student.imageSrc" accept="image/*"   />
                                <div ng-messages="stdRegistrationForm.imageSrc.$error">
                                    <div ng-message="required">le champ photo est obligatoire</div>
                                    <div ng-message="extension">Format de fichier invalid</div>
                                    
                                </div> 
                          </md-input-container>                            
   
        
                                                            
              
                    </div>


					
				</div>
                </div>
<!-- comment -->
            <div class="col-4">
                <div class="alert alert-danger">
                    <p><i class="fa-solid fa-bell"></i> &nbsp; Vous avez soumis un dossier de candidature et vous souhaitez avoir des information concernant son état de traitement. utiliser votre code d'accès pour vous connecter. </p>
                </div>
                
                
            </div>
            </div>
	</div>


</div>

        <?= $this->inlineScript()

        ->prependFile($this->basePath('js/jquery-3.7.0.min.js'))
        ?>
<script type="text/javascript">
$(document).ready(function () {
	var currentGfgStep, nextGfgStep, previousGfgStep;
	var opacity;
	var current = 1;
	var steps = $("fieldset").length;

	setProgressBar(current);

	$(".next-step").click(function () {

		currentGfgStep = $(this).parent();
		nextGfgStep = $(this).parent().next();

		$("#progressbar li").eq($("fieldset")
			.index(nextGfgStep)).addClass("active");

		nextGfgStep.show();
		currentGfgStep.animate({ opacity: 0 }, {
			step: function (now) {
				opacity = 1 - now;

				currentGfgStep.css({
					'display': 'none',
					'position': 'relative'
				});
				nextGfgStep.css({ 'opacity': opacity });
			},
			duration: 500
		});
		setProgressBar(++current);
	});

	$(".previous-step").click(function () {

		currentGfgStep = $(this).parent();
		previousGfgStep = $(this).parent().prev();

		$("#progressbar li").eq($("fieldset")
			.index(currentGfgStep)).removeClass("active");

		previousGfgStep.show();

		currentGfgStep.animate({ opacity: 0 }, {
			step: function (now) {
				opacity = 1 - now;

				currentGfgStep.css({
					'display': 'none',
					'position': 'relative'
				});
				previousGfgStep.css({ 'opacity': opacity });
			},
			duration: 500
		});
		setProgressBar(--current);
	});

	function setProgressBar(currentStep) {
		var percent = parseFloat(100 / steps) * current;
		percent = percent.toFixed();
		$(".progress-bar")
			.css("width", percent + "%")
	}

	$(".submit").click(function () {
		return false;
	})
});

</script>

