

 <p>
 <div  style="margin-top: 55px;">
    
   
<a href='accueil'>[Retour]</a>
        
<div class='row'>
    
    <div class="col-md-4" >
      

    </div>
    <div class="col-md-4">
        <p>
    </p>
    <br /><br /><br /><br /><br />
    <div class='jumbotron' style='border: 1px #9d9d9d solid; padding: 25px;'>
        <form class="" method="POST" action="">
                <h4 class="form-signin-heading">Connectez vous ici</h2>
                <?php if ( $isLoginError): ?>
                <div class="alert alert-danger" role="alert">
                    Matricule ou date de naissance incorrect
                    <!--<a href="">Forgot password?</a> -->
                </div>
                <?php endif; ?>
                <?php if ( $isPvNotAvailable): ?>
                <div class="alert alert-danger" role="alert">
                    Procès verbal d'admission non encore disponible.
                    <!--<a href="">Forgot password?</a> -->
                </div>
                <?php endif; ?>

              <div class="form-group">
                <?= $this->formElement($form->get('matricule')->setAttributes([
                    'class'=>'form-control', 
                    'placeholder'=>'Votre numéro de maticule',
                    'required' => true,
                    'autofocus' => true
                    ])
                    ->setLabelAttributes([
                        'class' => 'sr-only'
                    ])); ?>

              </div>
              <div class="form-group">
                <?= $this->formElement($form->get('birthdate')->setAttributes([
                    'class'=>'form-control', 
                    'placeholder'=>'date de naissance jjmmyyyy',
                    'required' => true,
                    ])
                    ->setLabelAttributes([
                        'class' => 'sr-only'
                    ])); ?>
                  <span class="text-primary" style='font-size: 0.75em; font-weight: bolder;'> EX: 18041999 <br /></span>
                <?= $this->formLabel($form->get('remember_me')); ?>
                <?= $this->formElement($form->get('remember_me')); ?>

                <?= $this->formElement($form->get('redirect_url')); ?>

                <?php //$this->formElement($form->get('csrf')) ?>
               <!-- <label>Numéro du Dossier :</label>
                <input type="text" name='num-dossier' class="form-control"/>
                <input type="hidden" name='redirectUrl' class="form-control"/> -->
               <?= $this->formElement($form->get('csrf')) ?>
                <button type="submit" name="login-btn" id='login-btn' class="btn btn-primary btn-md btn-block">Suivant</button>
              </di>

            </div>
        </form>
    </div>
    </div>
</div>
    </div>
