
<!------ Include the above in your HEAD tag ---------->

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="js/jquery-3.7.0.min.js" type="text/javascript"></script>
        <script src="js/bootstrap-4.1.0.min.js" type="text/javascript"></script>
        <link href="css/bootstrap-4.1.0.css" rel="stylesheet" type="text/css"/>
        <link href="css/login.css" rel="stylesheet" type="text/css"/>
        <title></title>
    </head>
    <body>
 <a href="home" class="btnForgetPwd" value="Login">[Retour]</a>
        <div class="container register">
            <div class="row">
                <div class="col-md-12">
                    <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#student" role="tab" aria-controls="student" aria-selected="true">Je suis étudiant</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#lecturer" role="tab" aria-controls="lecturer" aria-selected="false">Je suis enseignant</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active text-align form-new" id="student" role="tabpanel" aria-labelledby="home-tab">
                            <h3 class="register-heading">Login étudiant</h3>
                            <div class="row register-form">
                                <div class="col-md-12">
                                    <form class="" method="POST" action="#student">
                                          
                                            <?php if ( $isLoginError): ?>
                                            <div class="alert alert-danger" role="alert">
                                                Matricule ou date de naissance incorrect
                                                <!--<a href="">Forgot password?</a> -->
                                            </div>
                                            <?php endif; ?>


                                          <div class="form-group">
                                            <?= $this->formElement($sForm->get('matricule')->setAttributes([
                                                'class'=>'form-control', 
                                                'placeholder'=>'Votre numéro de maticule',
                                                'required' => true,
                                                'autofocus' => true
                                                ])
                                                ->setLabelAttributes([
                                                    'class' => 'sr-only'
                                                ])); ?>

                                          </div>
                                          <div class="form-group mt-3">
                                            <?= $this->formElement($sForm->get('birthdate')->setAttributes([
                                                'class'=>'form-control', 
                                                'placeholder'=>'date de naissance jjmmyyyy',
                                                'required' => true,
                                                ])
                                                ->setLabelAttributes([
                                                    'class' => 'sr-only'
                                                ])); ?>
                                              <span class="text-primary" style='font-size: 0.75em; font-weight: bolder;'> EX: 18041999 <br /></span>
                                            <?= $this->formLabel($sForm->get('remember_me')); ?>
                                            <?= $this->formElement($sForm->get('remember_me')); ?>

                                            <?= $this->formElement($sForm->get('redirect_url')); ?>
                                            <?= $this->formElement($sForm->get('loginFrom')->setAttributes(["value"=>"studentSpace"])); ?>
                                            <?php //$this->formElement($form->get('csrf')) ?>
                                           <!-- <label>Numéro du Dossier :</label>
                                            <input type="text" name='num-dossier' class="form-control"/>
                                            <input type="hidden" name='redirectUrl' class="form-control"/> -->
                                           <?= $this->formElement($sForm->get('csrf')) ?>
                                            <button type="submit" name="login-btn" id='login-btn' class="form-control btn btn-primary btn-md btn-block btnContactSubmit">Suivant</button>
                                          </div>
                                            </form>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show text-align form-new" id="lecturer" role="tabpanel" aria-labelledby="profile-tab">
                            <h3  class="register-heading">Login enseignant</h3>
                            <div class="row register-form">
                                <div class="col-md-12">
                                   <form class="" method="POST" action="#lecturer">
                                          
                                            <?php if ( $isLoginError): ?>
                                            <div class="alert alert-danger" role="alert">
                                                Numéro de téléphone ou mot depasse incorrect
                                                <!--<a href="">Forgot password?</a> -->
                                            </div>
                                            <?php endif; ?>


                                          <div class="form-group">
                                            <?= $this->formElement($lForm->get('phoneNumber')->setAttributes([
                                                'class'=>'form-control', 
                                                'placeholder'=>'Votre adresse email  ou numéro de téléphone',
                                                'required' => true,
                                                'autofocus' => true
                                                ])
                                                ->setLabelAttributes([
                                                    'class' => 'sr-only'
                                                ])); ?>

                                          </div>
                                          <div class="form-group mt-3">
                                            <?= $this->formElement($lForm->get('password')->setAttributes([
                                                'class'=>'form-control', 
                                                'placeholder'=>'Mot de passe',
                                               // 'required' => true,
                                                ])
                                                ->setLabelAttributes([
                                                    'class' => 'sr-only'
                                                ])); ?>
                                            


                                            <?= $this->formElement($lForm->get('redirect_url')); ?>
                                            <?= $this->formElement($sForm->get('loginFrom')->setAttributes(["value"=>"lecturerSpace"])); ?>
                                            <?php //$this->formElement($lForm->get('csrf')) ?>
                                           <!-- <label>Numéro du Dossier :</label>
                                            <input type="text" name='num-dossier' class="form-control"/>
                                            <input type="hidden" name='redirectUrl' class="form-control"/> -->
                                           <?= $this->formElement($lForm->get('csrf')) ?>
                                            <button type="submit" name="login-btn" id='login-btn' class="form-control btn btn-primary btn-md btn-block btnContactSubmit">Suivant</button>
                                          </div>
                                            </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

<script>
    $(document).ready(function(){
    
//window.location.replace("#lecturer");
var id = window.location.hash; console.log(id);            
//window.location.href = '#lecturer';
            if(id==="#lecturer")
            {
		$('#home-tab').removeClass('active');
		$('#profile-tab').addClass('active'); 
		$('#student').removeClass('active');
		$('#lecturer').addClass('active'); 
            }
            else if(id==="#student")
            {
		$('#home-tab').addClass('active');
		$('#profile-tab').removeClass('active'); 
		$('#student').addClass('active');
		$('#lecturer').removeClass('active');                
            }
    })

</script>