
 <p>
 <div  style="margin-top: 55px;">
    
   
<a href='accueil'>[Retour]</a>
        
<div class='row'>
    
    <div class="col-md-4" >
      

    </div>
    <div class="col-md-4">
        <p>
    </p>
    <br /><br /><br /><br /><br />
    <div class='jumbotron' style='border: 1px #9d9d9d solid; padding: 25px;'>
        <form class="" method="POST" action="">
                <h4 class="form-signin-heading">Connectez vous ici</h2>
                <?php if ( $isLoginError): ?>
                <div class="alert alert-danger" role="alert">
                    Numéro d'admission incorrect
                    <!--<a href="">Forgot password?</a> -->
                </div>
                <?php endif; ?>


              <div class="form-group">
                <?= $this->formElement($form->get('numDossier')->setAttributes([
                    'class'=>'form-control', 
                    'placeholder'=>'Votre numéro d\'admission',
                    'required' => true,
                    'autofocus' => true
                    ])
                    ->setLabelAttributes([
                        'class' => 'sr-only'
                    ])); ?>

              </div>
              <div class="form-group">




                <?php //$this->formElement($form->get('csrf')) ?>
               <!-- <label>Numéro du Dossier :</label>
                <input type="text" name='num-dossier' class="form-control"/>
                <input type="hidden" name='redirectUrl' class="form-control"/> -->
               
                <button type="submit" name="login-btn" id='login-btn' class="btn btn-primary btn-md btn-block">Suivant</button>
              </div>
                <div class="form-group small">
                    <a href="preRegistration">Cliquer ici</a> pour effectuer votre préinscription  et obtenir un numéro d'admission.
                </div>

            </div>
        </form>
    </div>
    </div>
</div>
    </div>


 