<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<style>
[ng\:cloak], [ng-cloak], .ng-cloak {
    display: none;
}

.submitForm {
	width: 100%;
}

.validation{
	padding-top: 5px;
	display: none;
	color: red;
}

.input-error {
  display: block;
  font-size: 12px;
}

</style>
<div class=" bg-light  rounded-3 "
        ng-controller="formCtrl as $ctrl" ng-init="init()">
    <br />
<!DOCTYPE html>


   
<div cg-busy="{promise:myPromise,minDuration:700}"> 					
         
    <div class="row">             
    <div >
		<md-progress-linear md-mode="determinate" class="md-accent" value="{{progressValue}}"></md-progress-linear>                

              
        <md-content class="md-padding" layout-xs="column" >
            <form ng-submit="submitRegistrationForm()" name="stdRegistrationForm" id="submitForm" class="submitForm form-validation" role="form" novalidate>
         <div class="animate-switch-container" ng-switch on="stage" ng-class="{forward: direction, backward:!direction}">
             
<!--|==========================================================================
					| Stag0
|==========================================================================   -->                
<md-card  class="card-40-center animate-switch stepCard" md-theme-watch ng-switch-default  ng-class="{forward: direction, backward:!direction}">
    <md-card-title>
        <md-card-title-text>
            <h1>Admission à l'Institut Supérieure Agenla Academy</h1> 
            <md-card-title-media></md-card-title-media>
        </md-card-title-text>
    </md-card-title> 
    <md-card-content>
    <div >
        <p>
        L’admission est ouverte aux titulaires d’un Baccalauréat d’Enseignement Général, Technique Industriel ou
        Commercial, d’un Brevet de Technicien, d’un G.C.E. A-Level, ou de tout autre diplôme reconnu en équivalence par le
        Ministère en charge de l’Enseignement Supérieur au Cameroun.
        </p>
        <p>
            L’admission en première année se fait sur concours d’entrée.
        </p>
        <p>
            Le Jury d’admission prend en compte les trois éléments suivants :
        </p>
        <p>

        Elément 1 : Etude du dossier, sur la base d’une grille d’évaluation interne unique pour tous les candidats <br />

        Elément 2 : Résultats obtenus aux épreuves écrites du concours d’entrée <br />
        <ul>

            <li>Epreuve de connaissances générales</li>
            <li>Epreuve de compréhension de texte et synthèse</li>
            <li>Epreuve de langue : compréhension, grammaire, vocabulaire</li>
            <li>Epreuve de raisonnement logique et calculs élémentaires</li>
        </ul>
    </p>
    <p>
        Elément 3 : Résultats obtenus aux épreuves orales du concours d’entrée <be />
    <ul>
        <li> Entretien individuel de motivation</li>
        <li> Entretien de groupe</li>
    </ul>
    <p>    
        L’admission en première année est prononcée sous réserve de l’obtention par le candidat d’un baccalauréat, général ou professionnel, ou d’un diplôme de niveau équivalent.
     </p>

    </div>          
    </md-card-content>
    <md-card-actions layout="row" layout-align="end center">
 
        <button type="button" class="btn btn-secondary m-1" ng-click="next('stage1')"><i class="fa-solid fa-circle-play"></i>&nbsp;Cliquer ici pour démarrer&nbsp;</button>
    </md-card-actions>    
</md-card>            
             
<!--|==========================================================================
					| Stag1
|==========================================================================   -->                 
<md-card  class="card-40-center animate-switch stepCard" md-theme-watch md-theme-watch ng-switch-when="stage1">
            <md-card-title>
                <md-card-title-text>
                    <span class="md-headline">Identification du candidat</span> 
                    <md-card-title-media></md-card-title-media>
                </md-card-title-text>
            </md-card-title>                        
								<!-- first name -->
            <md-card-content>
                
                
                <div class="row">
                    <div  class="col-md-8">
                        <input valid-file1 ng-model="photo"class="file" type="file" accept="image/*" image="image1" ng-file='image1.compressed.dataURL' name="photo" resize-max-height="150" resize-max-width="150" resize-quality="0.7" resize-type="image/jpg" ng-image-compress />  
                        <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.photo.$error.validFile1}">
                            Vous devez charger une photo
                        </div>                           
                        <div class="input-group my-3">
                            <input type="text" class="form-control" disabled placeholder="Chargez une photo" id="file">
                            <div class="input-group-append">
                              <button type="button" class="browse btn btn-primary">Cliquez ici...</button>
                            </div>
                        </div>

                    </div>
                    <div  class="col-md-4">
                        <img ng-src="{{image1.compressed.dataURL}}" class="img-thumbnail" style="width:150px; height: 150px;" />
                    </div>
                </div>
                <div class='row'>
                    <md-input-container class="md-block" flex-gt-sm>
                      <label>Nom:</label>
                      <input name="nom" ng-model="$ctrl.student.nom" required />
                        <div ng-messages="stdRegistrationForm.nom.$error">
                          <div ng-message="required">le champ nom est obligatoire</div>
                        </div>                            
                        <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.nom.$error.required}">
                            Le champ nom est obligatoire
                        </div>   
                    </md-input-container>
           
                   
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Prénom:</label>
                            <input name="prenom" ng-model="$ctrl.student.prenom"   />

                          </md-input-container>

                        <div layout-gt-sm="row" style='margin-top: -35px;'>
                            <md-input-container class="md-block" flex-gt-sm>
                                <label>Date de naissance</label>
                                <md-datepicker   ng-model="$ctrl.student.dateOfBirth" ng-change="dateChanged()" required ></md-datepicker>
                                <input type="hidden" name="dateOfBirth"  value={{$ctrl.student.dateOfBirth}}   />
                                <div ng-messages="stdRegistrationForm.dateOfBirth.$error">
                                  <div ng-message="valid">Format de date invalide</div>
                                  <div ng-message="required">le champ date de naissance est obligatoire</div>
                                </div>
                                <div class="validation" ng-class="{'input-error': formValidation && !$ctrl.student.dateOfBirth}">
                                    Le champ date de naissance est obligatoire
                                </div>                              
                            </md-input-container>

                            <md-input-container class="md-block" flex-gt-sm>
                                <label>Ville de naissance:</label>
                                <input name="bornAt" ng-model="$ctrl.student.bornAt" required />
                                <div ng-messages="stdRegistrationForm.bornAt.$error">
                                    <div ng-message="required">le champ Prénom est obligatoire</div>
                                </div> 
                                  <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.bornAt.$error.required}">
                                      Le champ lieu de naissance est obligatoire
                                  </div>                            
                            </md-input-container>
                        </div>
                          <div layout-gt-sm="row" style='margin-top: -35px;' >
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Sexe</label>
                                    <md-select name='gender' ng-model="$ctrl.student.gender" required  >
                                        <md-option value="M">Masculin</md-option>
                                        <md-option value="F">Féminin</md-option>
                                    </md-select>
                                    <div ng-messages="stdRegistrationForm.gender.$error">
                                        <div ng-message="required">le champ Sexe est obligatoire</div>

                                    </div>    
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.gender.$error.required}">
                                    Le champ genre est obligatoire
                                </div>                                    
                                </md-input-container>
                          
     
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Numéro de téléphone</label>
                                    <input name="phoneNumber" ng-model="$ctrl.student.phoneNumber" ng-pattern="/^[0-9]{9}$/" required />
                                    <div ng-messages="stdRegistrationForm.phoneNumber.$error">
                                        <div ng-message="required">le champ numéro de téléphone est obligatoire</div>
                                        <div ng-message="pattern">Numéro de téléphone invalid</div>
                                    </div>
                                <div class="validation" ng-class="{'input-error': formValidation &&  stdRegistrationForm.phoneNumber.$error.required }">
                                    Numéro de téléphone obligatoire
                                </div>                                    
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.phoneNumber.$dirty && stdRegistrationForm.phoneNumber.$error.pattern }">
                                    format du numéro de téléphone incorrect
                                </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Email</label>
                                    <input name="email" ng-model="$ctrl.student.email"  type="email" required  minlength="10" maxlength="100" ng-pattern="/^.+@.+\..+$/"  />
                                    <div ng-messages="stdRegistrationForm.email.$error" role="alert">
                                       <div ng-message-exp="['required', 'minlength', 'maxlength', 'pattern']">
                                          votre email doit contenir au moins 10 et être semblable à un email.
                                        </div>
                                    </div>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.email.$error.required}">
                                    email est obligatoire
                                </div>   
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.email.$dirty&& stdRegistrationForm.email.$error.pattern}">
                                    format email incorrect
                                </div>                                     
                                </md-input-container>
   
                        </div>
                          <div layout-gt-sm="row" style='margin-top: -35px;' >
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Adresse</label>
                                    <input name="adresse" ng-model="$ctrl.student.adresse"       />
                                    <div ng-messages="stdRegistrationForm.adresse.$error">
                                        <div ng-message="required">le champ adresse est obligatoire</div>
      
                                    </div> 
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Numéro CNI/Passeport</label>
                                    <input name="identite" ng-model="$ctrl.student.idNumber"    required   />
                                    <div ng-messages="stdRegistrationForm.identite.$error">
                                        <div ng-message="required">le champ adresse est obligatoire</div>
                                        <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.identite.$error.required}">
                                            le chmap adresse est obligatoire
                                        </div> 
                                    </div> 
                                </md-input-container>                              
                          </div>

                          <div layout-gt-sm="row" style='margin-top: -35px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Langue</label>
                                    <md-select name ='language' ng-model="$ctrl.student.language" required >
                                        <md-option value="FR">Français</md-option>
                                        <md-option value="ANG">Anglais</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.language.$error">
                                        <div ng-message="required">le champ Langue est obligatoire</div>
                                    </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.language.$error.required}">
                                    langue obligatoire
                                </div>                                     
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Nationalité</label>
                                    <md-select name='nationality' ng-model="$ctrl.student.nationality"   >
                                        <md-option ng-repeat="country in $ctrl.countries" ng-value="country.sortname" >
                                          {{country.name}}
                                        </md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.nationality.$error">
                                        <div ng-message="required">le champ Nationalité est obligatoire</div>
                                    </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.nationality.$error.required}">
                                    nationalité obligatoire
                                </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Région d'origine</label>
                                    <md-select name='regionOfOrigin' ng-model="$ctrl.student.regionOfOrigin" md-on-open="$ctrl.getRegions($ctrl.student.nationality)"  >
                                        <md-option ng-repeat="region in $ctrl.regions" ng-value="region.name" >
                                          {{region.name}}
                                        </md-select>
                                    <div ng-messages="stdRegistrationForm.regionOfOrigin.$error">
                                        <div ng-message="required">le champ Religion est obligatoire</div>
                                    </div>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.regionOfOrigin.$error.required}">
                                    region d'aorigine obligatoire
                                </div>                                    
                                </md-input-container>

                          </div>
   
                          <div layout-gt-sm="row" style='margin-top: -15px;'>
                              
                                <md-input-container class="md-block" flex-gt-sm >
                                    <label>Réligion</label>
                                    <md-select name='religion' ng-model="$ctrl.student.religion" required '>
                                        <md-option value="CATHOLIQUE">Catholique</md-option>
                                        <md-option value="PROTESTANT">Protestant</md-option>
                                        <md-option value="MUSULMAN">Musulman</md-option>
                                        <md-option value="AUTRE">Autres</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.religion.$error">
                                        <div ng-message="required">le champ Religion est obligatoire</div>
                                    </div> 
                                    <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.religion.$error.required}">
                                        religion obligatoire
                                    </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm >
                                    <label>Situation matrimoniale</label>
                                    <md-select name='maritalStatus' ng-model="$ctrl.student.maritalStatus" style='width:100%' required >
                                        <md-option value="CELIBATAIRE">Célibataire</md-option>
                                        <md-option value="MARIÉ(E)">Marié(e)</md-option>
                                        <md-option value="DIVORCÉ(E)">Divorcé(e)</md-option>
                                        <md-option value="VEUF">Veuf</md-option>
                                        <md-option value="VEUVE">Veuve</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.maritalStatus.$error">
                                        <div ng-message="required">le champ Situation matrimoniale est obligatoire</div>
                                    </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.maritalStatus.$error.required}">
                                    situation matrimoniale obligatoire
                                </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm >
                                    <label>Situation d'emploi</label>
                                    <md-select name='workingStatus' ng-model="$ctrl.student.workingStatus" style='width:100%' required >
                                        <md-option value="EMPLOYÉ(E)">Employé</md-option>
                                        <md-option value="SANS EMPLOI">Sans emploi</md-option>

                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.workingStatus.$error">
                                        <div ng-message="required">le champ Situation d'emploi est obligatoire</div>
                                    </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.workingStatus.$error.required}">
                                    situation d'emploi obligatoire
                                </div>                                    
                                </md-input-container>                              

                          </div> 
                    </div>
              
            </md-card-content>        <!-- comment -->
                    <!-- navigation -->

                    <!-- buttons -->
            <md-card-actions layout="row" layout-align="end center">
                <button type="button" class="btn btn-danger m-1" ng-click="back('')"><i class="fa-solid fa-backward"></i>&nbsp; Retour &nbsp;</button>
                <button type="button" class="btn btn-danger m-1" ng-click="next('stage2')">&nbsp;Suivant&nbsp;<i class="fa-solid fa-forward"></i> </button>
            </md-card-actions>  
        </md-card>
                    
<!--
|==========================================================================
| Stage 2
|==========================================================================
-->
            <md-card  class="card-40-center animate-switch stepCard" md-theme-watch ng-switch-when="stage2">
                <md-card-title>
                        <md-card-title-text>
                                <span class="md-headline">Information sur les parents</span>
                                <!-- navigation -->
                                <md-card-title-media></md-card-title-media>

                </md-card-title>                                                                

								<!-- first name -->
                <md-card-content>
 <!-- identification du père -->
                            <md-toolbar>
                            <div class="md-toolbar-tools text-white">
                              <h2>Identifcation du père</h2>
                            </div>
                          </md-toolbar>
                         
                           <div layout-gt-sm="row" style='margin-top: 15px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Nom et Prénoms:</label>
                            <input name="fatherName" ng-model="$ctrl.student.fatherName" required />
                                <div ng-messages="stdRegistrationForm.fatherName.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>

                                </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.fatherName.$error.required}">
                                    Champ obligatoire
                                </div>                            
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Profession</label>
                            <input name="fatherProfession" ng-model="$ctrl.student.fatherProfession" />
                                <div ng-messages="stdRegistrationForm.fatherProfession.$error">
                                    <div ng-message="required">le champ Profession est obligatoire</div>
                                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                </div> 
                            
                          </md-input-container>
                        </div> 
                           <div layout-gt-sm="row" style='margin-top: 5px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Pays de Résidence</label>
                                    <md-select name='fatherCountry' ng-model="$ctrl.student.fatherCountry" required >
                                        <md-option ng-repeat="country in $ctrl.countries" ng-value="country.sortname" >
                                          {{country.name}}
                                        </md-option>
                                    </md-select>
                                    <div ng-messages="stdRegistrationForm.fatherCountry.$error">
                                        <div ng-message="required">le champ Pays de résidence est obligatoire</div>
                                    </div> 
                                </md-input-container>

                                <md-input-container class="md-block" flex-gt-sm>
                                <label>Ville de résidence</label>
                                    <md-select name="fatherCity" ng-model="$ctrl.student.fatherCity" md-on-open="$ctrl.getCities($ctrl.student.fatherCountry)"  required>
                                    
                                        <md-option ng-repeat="city in $ctrl.cities" ng-value="city.name" >
                                          {{city.name}}
                                        </md-option>
                                    </md-select>
                                    
                                    <div ng-messages="stdRegistrationForm.fatherCity.$error">
                                        <div ng-message="required">le champ Région de résidence est obligatoire</div>
                                    </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.fatherCity.$error.required}">
                                    champ obligatoire
                                </div>                                
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>

                                </md-input-container>
                          </div>
                           <div layout-gt-sm="row" style='margin-top: 10px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Numéro de téléphone:</label>
                            <input name="fatherPhoneNumber" ng-model="$ctrl.student.fatherPhoneNumber" ng-pattern="/^[0-9]{9}$/" required  />
                                <div ng-messages="stdRegistrationForm.fatherPhoneNumber.$error">
                                    <div ng-message="pattern">Numéro de téléphone invalid</div>

                                </div>  
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.fatherPhoneNumber.$error.required}">
                                    champ obligatoire
                                </div>                            
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Email:</label>
                            <input name="fatherEmail" type="email" ng-model="$ctrl.student.fatherEmail" minlength="10" maxlength="100" ng-pattern="/^.+@.+\..+$/" />
                                <div ng-messages="stdRegistrationForm.fatherEmail.$error">
                                       <div ng-message-exp="['required', 'minlength', 'maxlength', 'pattern']">
                                          votre email doit contenir au moins 10 et être semblable à un email.
                                        </div>
                                </div> 
                          </md-input-container>
                        </div>
                        <div layout-gt-sm="row" style='margin-top: -35px;' >
                             <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                 <label>Adresse</label>
                                 <input name="fatherAdress" ng-model="$ctrl.student.fatherAdress"       />
                                 <div ng-messages="stdRegistrationForm.fatherAdress.$error">
                                     <div ng-message="required">le champ adresse est obligatoire</div>
                             <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.fatherAdress.$error.required}">
                                 le chmap adresse est obligatoire
                             </div> 
                                 </div>  
                       </div>
           
 <!-- FIn identification du père -->
 
  <!-- identification de la mère -->
                            <md-toolbar>
                            <div class="md-toolbar-tools text-white">
                              <h2>Identifcation de la mère</h2>
                            </div>
                          </md-toolbar>
                             <div layout-gt-sm="row" style='margin-top: 15px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Nom et Prénoms de la mère:</label>
                            <input name="motherName" ng-model="$ctrl.student.motherName" required />  
                                <div ng-messages="stdRegistrationForm.motherName.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>

                                </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.motherName.$error.required}">
                                    champ obligatoire
                                </div>                            
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Profession</label>
                            <input name="motherProfession" ng-model="$ctrl.student.motherProfession"  />
                                <div ng-messages="stdRegistrationForm.motherProfession.$error">
                                    <div ng-message="required">le champ Prénom est obligatoire</div>
                                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                </div> 
                            
                          </md-input-container>
                        </div> 
                           <div layout-gt-sm="row" style='margin-top: 5px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Pays de Résidence</label>
                                    <md-select name="motherCountry" ng-model="$ctrl.student.motherCountry" required >
                                        <md-option ng-repeat="country in $ctrl.countries_1" ng-value="country.sortname" >
                                          {{country.name}}
                                        </md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.motherCountry.$error">
                                        <div ng-message="required">le champ Ville  de résidence est obligatoire</div>
                                    </div>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.motherCountry.$error.required}">
                                    Champ obligatoire
                                </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Ville de résidence</label>
                                    <md-select name="motherCity" ng-model="$ctrl.student.motherCity" md-on-open="$ctrl.getCities_1($ctrl.student.motherCountry)"  required>
                                    
                                        <md-option ng-repeat="city in $ctrl.cities_1" ng-value="city.name" >
                                          {{city.name}}
                                        </md-option>
                                    </md-select>
                                    <div ng-messages="stdRegistrationForm.motherCity.$error">
                                        <div ng-message="required">le champ Région de résidence est obligatoire</div>
                                    </div>  
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.motherCity.$error.required}">
                                    Champ obligatoire
                                </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                            
                               
                                </md-input-container>

                          </div>
                           <div layout-gt-sm="row" style='margin-top: 15px;' >
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Numéro de téléphone:</label>
                            <input name="motherPhoneNumber" ng-model="$ctrl.student.motherPhoneNumber" ng-pattern="/^[0-9]{9}$/"  required />
                                <div ng-messages="stdRegistrationForm.motherPhoneNumber.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>
                                    <div ng-message="pattern">Numéro de téléphone invalid</div>

                                </div> 
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.motherPhoneNumber.$error.required}">
                                    situation d'emploi obligatoire
                                </div>                            
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Email:</label>
                            <input name="motherEmail" type="email" ng-model="$ctrl.student.motherEmail" minlength="10" maxlength="100" ng-pattern="/^.+@.+\..+$/" />
                                <div ng-messages="stdRegistrationForm.motherEmail.$error">
                                       <div ng-message-exp="['required', 'minlength', 'maxlength', 'pattern']">
                                          votre email doit contenir au moins 10 et être semblable à un email.
                                        </div>
                                </div> 
                          </md-input-container>
                        </div> 
                          <div layout-gt-sm="row" style='margin-top: -35px;' >
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Adresse</label>
                                    <input name="motherAdress" ng-model="$ctrl.student.motherAdress"       />
                                    <div ng-messages="stdRegistrationForm.motherAdress.$error">
                                        <div ng-message="required">le champ adresse est obligatoire</div>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.motherAdress.$rror.required}">
                                    le chmap adresse est obligatoire
                                </div> 
                                    </div>  
                          </div>  
 <!-- FIn identification de la mère -->
 
   <!-- identification du tuteur -->
                          <md-toolbar>
                            <div class="md-toolbar-tools text-white ">
                                <h2>Identifcation du Sponsor/Tuteur</h2> 
                            </div>
                          </md-toolbar>
                             <div layout-gt-sm="row" style='margin-top: 15px;' >
                                 <p>Votre sponsor c'est votre:</p>
                            <md-input-container class="md-block" flex-gt-sm>
                               <md-radio-group ng-model="$ctrl.sponsor">

                                 <md-radio-button  value="PERE" class="md-primary">Père</md-radio-button>
                                 <md-radio-button value="MERE" class="md-primary">Mère </md-radio-button>
                                 <md-radio-button value="AUTRE" class="md-primary">Autre</md-radio-button>

                               </md-radio-group> 
                            </md-input-container>
                        </div>
   
                <div ng-hide="$ctrl.chkSponsor($ctrl.sponsor)">                    
                        <div layout-gt-sm="row" style='margin-top: 15px;'  >
                            <md-input-container class="md-block" flex-gt-sm>
                              <label>Nom et Prénoms:</label>
                              <input name="sponsorName" ng-model="$ctrl.student.sponsorName" ng-required='!$ctrl.chkSponsor($ctrl.sponsor)'  />
                                  <div ng-messages="stdRegistrationForm.sponsorName.$error">
                                      <div ng-message="required">le champ nom est obligatoire</div>

                                  </div> 
                                  <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.sponsorname.$error.required}">
                                      Champ obligatoire
                                  </div>                            
                            </md-input-container>

                            <md-input-container class="md-block" flex-gt-sm>
                              <label>Profession</label>
                              <input name="sponsorProfession" ng-model="$ctrl.student.sponsorProfession"  />
                                  <div ng-messages="stdRegistrationForm.sponsorProfession.$error">
                                      <div ng-message="required">le champ Prénom est obligatoire</div>
                                      <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                  </div> 

                            </md-input-container>
                        </div> 
                        <div layout-gt-sm="row" style='margin-top: 15px;'  >
                            <md-input-container class="md-block" flex-gt-sm>
                              <label>Relation avec l'étudiant:</label>
                                        <md-select name="studyLevel"  ng-model="$ctrl.student.sponsorRelationShipWithStd"    ng-required='!$ctrl.chkSponsor($ctrl.sponsor)' >
                                            <md-option value="ONCLE">Oncle</md-option>
                                            <md-option value="TANTE">Tante</md-option>
                                            <md-option value="AMI">Ami(e)</md-option>
                                            <md-option value="CONNAISSANCE">Connaissance</md-option>  
                                            <md-option value="FIANCE">Fiancé(e)</md-option>
                                            <md-option value="CONJOINT">Conjoint</md-option>
                                            
                                        </md-select>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.studyLevel.$error.required}">
                                    Choix du niveau d'étude obligatoire
                                </div>                            
                            </md-input-container>


                        </div>                     
                        <div layout-gt-sm="row" style='margin-top: 5px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Pays de Résidence</label>
                                    <md-select name="sponsorCountry" ng-model="$ctrl.student.sponsorCountry" ng-required='!$ctrl.chkSponsor($ctrl.sponsor)'>
                                        <md-option ng-repeat="country in $ctrl.countries_2" ng-value="country.sortname" >
                                          {{country.name}}
                                        </md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.sponsorCountry.$error">
                                        <div ng-message="required">le champ Région de résidence est obligatoire</div>
                                    </div> 
                                    <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.sponsorCountry.$error.required}">
                                        Champ obligatoire
                                    </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Ville de résidence</label>
                                    <md-select name="sponsorCity" ng-model="$ctrl.student.sponsorCity" md-on-open="$ctrl.getCities_2($ctrl.student.sponsorCountry)" ng-required='!$ctrl.chkSponsor($ctrl.sponsor)' >
                                    
                                        <md-option ng-repeat="city in $ctrl.cities_2" ng-value="city.name" >
                                          {{city.name}}
                                        </md-option>
                                    </md-select>
                                    <div ng-messages="stdRegistrationForm.sponsorCity.$error">
                                        <div ng-message="required">le champ Région de résidence est obligatoire</div>
                                    </div> 
                                    <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.sponsorCity.$error.required}">
                                        Champ obligatoire
                                    </div>                                    
                                </md-input-container>


                    </div>
                    <div layout-gt-sm="row" style='margin-top: 15px;' >
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Numéro de téléphone:</label>
                            <input name="sponsorPhoneNumber" ng-model="$ctrl.student.sponsorPhoneNumber" ng-pattern="/^[0-9]{9}$/" ng-required='!$ctrl.chkSponsor($ctrl.sponsor)' />
                                <div ng-messages="stdRegistrationForm.sponsorPhoneNumber.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>
                                    <div ng-message="pattern">Numéro de téléphone invalid</div>

                                </div>   
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.sponsorPhoneNumber.$error.required}">
                                    Champ obligatoire
                                </div>                            
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Email:</label>
                            <input name="sponsorEmail" ng-model="$ctrl.student.sponsorEmail" minlength="10" maxlength="100" ng-pattern="/^.+@.+\..+$/" />
                                <div ng-messages="stdRegistrationForm.sponsorEmail.$error">
                                       <div ng-message-exp="['required', 'minlength', 'maxlength', 'pattern']">
                                          votre email doit contenir au moins 10 et être semblable à un email.
                                        </div>
                                </div> 
                          </md-input-container>
                    </div>
                          <div layout-gt-sm="row" style='margin-top: -35px;' >
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Adresse</label>
                                    <input name="sponsorAdress" ng-model="$ctrl.student.sponsorAdress"       />
                                    <div ng-messages="stdRegistrationForm.sponsorAdress.$error">
                                        <div ng-message="required">le champ adresse est obligatoire</div>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.sponsorAdress.$rror.required}">
                                    le chmap adresse est obligatoire
                                </div> 
                                    </div>  
                          </div>                      
                </div>
 <!-- FIn identification du tuteur -->
            </md-card-content>



            <!-- buttons -->
            <md-card-actions layout="row" layout-align="end center">
                <md-card-actions layout="row" layout-align="end center">
                    <button type="button" class="btn btn-danger m-1" ng-click="back('stage1')"><i class="fa-solid fa-backward"></i>&nbsp; Retour &nbsp;</button>
                    <button type="button" class="btn btn-danger m-1" ng-click="next('stage3')">&nbsp;Suivant&nbsp;<i class="fa-solid fa-forward"></i> </button>
                </md-card-actions>
            </md-card-actions>

    </md-card>  
                                        
<!--
        |==========================================================================
        | Stage 3
        |==========================================================================
-->

<md-card  class="card-40-center animate-switch stepCard" md-theme-watch ng-switch-when="stage3" >
                <md-card-title>
                        <md-card-title-text>
                                <span class="md-headline">Choix de la formation</span>
                </md-card-title>

                                <!-- first name -->
                <md-card-content>
 <!-- identification du père -->
                            <md-toolbar>
                            <div class="md-toolbar-tools text-white">
                              <h2></h2>
                            </div>
                          </md-toolbar>
                            <md-input-container class="md-block" flex-gt-sm>
                                 <div layout layout-sm="column">
                                    <md-input-container flex="flex" style="" >
                                        <label>Cycle de formation sollicité:</label>
                                        <md-select name="cycle" placeholder="Choisir le cycle de formation" ng-model="$ctrl.student.cycle_id" ng-change="$ctrl.searchDegree($ctrl.student.cycle_id)"    required >
                                           <md-option  ng-repeat="cycle in cycles" ng-value="cycle.id">{{cycle.name}} </md-option>
                                        </md-select>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.cycle.$error.required}">
                                    Choix du cycle obligatoire
                                </div>                                       
                                   </md-input-container>
                                </div> 
                            </md-input-container>
 
                            <md-input-container class="md-block" flex-gt-sm> 
                                 <div layout layout-sm="column">
                                    <md-input-container flex="flex" style="" >
                                        <label>Premier choix de formation:</label>
                                        <md-select name="choix1" placeholder="Premier choix de" ng-model="$ctrl.student.choixDeg1"    required >
                                           <md-option  ng-repeat="deg in degrees" ng-value="deg.id">{{deg.name}} </md-option>
                                        </md-select>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.choix1.$error.required}">
                                    Premier chix oblgatoire
                                </div>                                         
                                   </md-input-container>
                                </div>
                            </md-input-container>
 
                            <md-input-container class="md-block" flex-gt-sm> 
                                 <div layout layout-sm="column">
                                    <md-input-container flex="flex" style="" >
                                        <label>Deuxième choix de formation:</label>
                                        <md-select name="choix2" placeholder="Deuxième choix" ng-model="$ctrl.student.choixDeg2"    required >
                                           <md-option  ng-repeat="deg in degrees" ng-value="deg.id">{{deg.name}} </md-option>
                                        </md-select>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.choix2.$error.required}">
                                    Deuxhième choix obligatoire
                                </div>                                         
                                   </md-input-container>
                                </div>
                            </md-input-container>
 
                            <md-input-container class="md-block" flex-gt-sm> 
                                 <div layout layout-sm="column">
                                    <md-input-container flex="flex" style="" >
                                        <label>Troisième choix de formation:</label>
                                        <md-select name="choix3" placeholder="Troisième choix" ng-model="$ctrl.student.choixDeg3"    required >
                                           <md-option  ng-repeat="deg in degrees" ng-value="deg.id">{{deg.name}} </md-option>
                                        </md-select>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.choix3.$error.required}">
                                    Troisème choix obligatoire
                                </div>                                        
                                   </md-input-container>
                                </div>
                            </md-input-container>
 


                                <div layout layout-sm="column">
                                    <md-input-container flex="flex" style="" >
                                        <label>Niveau d'étude:</label>
                                        <md-select name="studyLevel" placeholder="Choisir le niveau d'étude" ng-model="$ctrl.student.study_level"    required >
                                            <md-option value="1">Niveau 1</md-option>
                                            <md-option value="2">Niveau 2</md-option>
                                            <md-option value="3">Niveau 3</md-option>
                                            <md-option value="4">Niveau 4</md-option>  
                                            <md-option value="5">Niveau 5</md-option>
                                            
                                        </md-select>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.studyLevel.$error.required}">
                                    Choix du niveau d'étude obligatoire
                                </div>                                         
                                   </md-input-container>
                                </div>
						<!-- buttons -->
        <md-card-actions layout="row" layout-align="end center">
            <md-card-actions layout="row" layout-align="end center">
                <button type="button" class="btn btn-danger m-1" ng-click="back('stage2')"><i class="fa-solid fa-backward"></i>&nbsp; Retour &nbsp;</button>
                <button type="button" class="btn btn-danger m-1" ng-click="next('stage4')">&nbsp;Suivant&nbsp;<i class="fa-solid fa-forward"></i> </button>
            </md-card-actions>
        </md-card-actions>
                </md-card-content>

                </md-card>                                          
                                        
 <!--
        |==========================================================================
        | Stage 4
        |==========================================================================
-->

<md-card  class="card-40-center animate-switch stepCard" md-theme-watch ng-switch-when="stage4" >
                <md-card-title>
                        <md-card-title-text>
                                <span class="md-headline">Cursus académique</span>
                </md-card-title>

                                <!-- first name -->
            <md-card-content>
 <!-- identification du père -->
            <md-toolbar>
                <div class="md-toolbar-tools text-white">
                  <h2></h2>
                </div>
            </md-toolbar>

    <div layout-gt-sm="row" class="mt-3" >        
     <ul style='list-style-type:none'>
         <li class="row" ng-repeat="cursus in $ctrl.student.cursus">
             <div class="row"> 
          
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Année  d'obtention</label>
                                        <md-select name="cursusAnnee"  ng-model="cursus.annee"    required >
                                        <md-option  ng-repeat="yr in annee" ng-value="yr.annee">{{yr.annee}} </md-option>
                                            
                                        </md-select>
                                <div class="validation" ng-class="{'input-error': formValidation &&  stdRegistrationForm.cursusAnnee.$error.required }">
                                    Champ est obligatoire
                                </div>                                    
                                  
                                </md-input-container>
     
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Etablissement</label>
                                    <input name="cursusEtab" ng-model="cursus.etablissement"  required />
                                    <div ng-messages="stdRegistrationForm.cursusEtab.$error">
                                        <div ng-message="required">Champ obligatoire</div>
                                  
                                    </div>
                                <div class="validation" ng-class="{'input-error': formValidation &&  stdRegistrationForm.cursusEtab.$error.required }">
                                    Champ obligatoire
                                </div>                                    
                                  
                                </md-input-container>
                          
     
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Diplôme obtenu</label>
                                        <md-select name="cursusDiplome"  ng-model="cursus.diplome"    required >
                                        <md-option  ng-repeat="bacc in baccalaureat" ng-value="bacc.code">{{bacc.name}} </md-option>
                                            
                                        </md-select>
                                <div class="validation" ng-class="{'input-error': formValidation &&  stdRegistrationForm.cursusDiplome.$error.required }">
                                    Champ obligatoire
                                </div>                                    
                                   
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <label>Mention</label>
                                        <md-select name="cursusMention"  ng-model="cursus.mention"    required >
                                            <md-option value="TB">Très bien</md-option>
                                            <md-option value="B">Bien</md-option>
                                            <md-option value="AB">Assez Bien</md-option>
                                            <md-option value="P">Passable</md-option>  
                                       
                                            
                                        </md-select>
                                    <div ng-messages="stdRegistrationForm.cursusMention.$error" role="alert">
                                       <div ng-message-exp="['required']">
                                          Champ oblogatoire
                                        </div>
                                    </div>
                                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.cursusMention.$error.required}">
                                   Champ obligatoire
                                </div> 
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm layout-sm="column">
                                    <button  type="button"class="btn btn-danger btn-sm" title="supprimer" ng-click="$ctrl.student.cursus.length>1?$ctrl.student.cursus.splice($index, 1):''" ><i class="fa-solid fa-trash"></i></button>
                                </md-input-container>
            </div>         
                                    </li>
                                    
                                    <li>
                                        <button type="button" class="btn btn-success" ng-click="$ctrl.addCursus()"> Ajouter un Cursus</button>  
                                    </li>
                    
        </ul>
                             
        </div>
                       


                            <!-- buttons -->
            <md-card-actions layout="row" layout-align="end center">
                <md-card-actions layout="row" layout-align="end center">
                    <button type="button" class="btn btn-danger m-1" ng-click="back('stage3')"><i class="fa-solid fa-backward"></i>&nbsp; Retour &nbsp;</button>
                    <button type="button" class="btn btn-danger m-1" ng-click="next('stage5')">&nbsp;Suivant&nbsp;<i class="fa-solid fa-forward"></i> </button>
                </md-card-actions>
            </md-card-actions>
            </md-card-content>
        </md-card> 
<!--
        |==========================================================================
        | Stage 5
        |==========================================================================
-->

<md-card  class="card-40-center animate-switch stepCard" md-theme-watch ng-switch-when="stage5" >
                <md-card-title>
                        <md-card-title-text>
                                <span class="md-headline">Joindre la preuve paiement des frais d'étude de dossier</span>
                </md-card-title>

                                <!-- first name -->
            <md-card-content>
 <!-- identification du père -->


            
            <div class="alert alert-warning mt-2" style="font-size: 0.75em;">
                <p>
                    Tout dossier de candidature doit être accompagné du paiement de la somme de 150000 FCFA corespondant aux frais d'étude de dossier.
                    Le paiement de ces frais se fait dans le compte N° ------------------ Domicilié à ------------------- <br />
                    Une fois le Paiement effectué bien vouloir scanner au format PDF la preuve de paiement et le transmettrre pour validation.
                </p>
            </div>

    <div layout-gt-sm="row" class="mt-3" >
            <div class="mb-3">
              <label for="formFile" class="form-label ">Preuve de règlement des frais de dossier</label>
              <input  class="form-control form-control-sm" name='financialProof' type="file"  accept=".pdf" ng-file='$ctrl.student.uploadFinancialProof' id="formFile" required>
                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.financialProof.$error}">
                   Champ obligatoire
                </div> 
            </div>




            </div>


                            <!-- buttons -->
            <md-card-actions layout="row" layout-align="end center">
                    <button type="button" class="btn btn-danger m-1" ng-click="back('stage4')"><i class="fa-solid fa-backward"></i>&nbsp; Retour &nbsp;</button>
                    <button type="button" class="btn btn-danger m-1" ng-disabled="$ctrl.student.uploadFinancialProof.length<1" ng-click="next('stage6')">&nbsp;Suivant&nbsp;<i class="fa-solid fa-forward"></i> </button>
            </md-card-actions>
            </md-card-content>
        </md-card> 




<!--
        |==========================================================================
        | Stage 6
        |==========================================================================
-->

<md-card  class="card-40-center animate-switch stepCard" md-theme-watch ng-switch-when="stage6" >

                <md-card-title>
                        <md-card-title-text>
                                <span class="md-headline">Joindre les documents</span>
                </md-card-title>

                                <!-- first name -->
            <md-card-content>
            <div class="alert alert-warning mt-1" style="font-size: 0.75em;">
                <p>
                    Vous êtes priés de bien vouloir Joindre les documents suivants pour faciliter l'étude de votre dossier:
                <ul>
                    <li> Curriculum vitae</li>
                    <li> Copie du dernier diplôme</li>
                    <li> Copie des bulletins trimestriels des trois dernières années</li>
                    <li> Copie d'acte de de n'aissance</li>
                    <li> Copie de la carte d'identité</li>
                </ul>
                </p>
            </div>                
 <!-- identification du père -->



    <div layout-gt-sm="row" class="mt-3" >
        <ul style='list-style-type:none'>
            <li>
            <div class="mb-3">
              <label for="formFile" class="form-label ">Curriculum vitae</label>
              <input  class="form-control form-control-sm" name='uploadCv' type="file"  accept=".pdf" ng-file='$ctrl.student.uploadCv' id="formFile" required>
                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.uploadCv.$error}">
                   Champ obligatoire
                </div> 
            </div>
            </li>
            <li>
            <div class="mb-3">
              <label for="formFile" class="form-label ">Copie du dernier diplôme</label>
              <input  class="form-control form-control-sm" name='uploadLastDegree' type="file"  accept=".pdf" ng-file='$ctrl.student.uploadLastDegree' id="formFile" required>
                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.financialProof.$error}">
                   Champ obligatoire
                </div> 
            </div>
            </li>            
            <li>
            <div class="mb-3">
              <label for="formFile" class="form-label ">Bulletins trimestriels des deux dernières</label>
              <input  class="form-control form-control-sm" name='financialProof' type="file"  accept=".pdf" ng-file='$ctrl.student.uploadTranscript' id="formFile" required>
                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.financialProof.$error}">
                   Champ obligatoire
                </div> 
            </div>
            </li> 
            <li>
            <div class="mb-3">
              <label for="formFile" class="form-label ">Copie d'acte de naissance</label>
              <input  class="form-control form-control-sm" name='financialProof' type="file"  accept=".pdf" ng-file='$ctrl.student.uploadBirthCertificate' id="formFile" required>
                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.financialProof.$error}">
                   Champ obligatoire
                </div> 
            </div>
            </li> 
            <li>
            <div class="mb-3">
              <label for="formFile" class="form-label ">Copie de la carte d'indentité</label>
              <input  class="form-control form-control-sm" name='financialProof' type="file"  accept=".pdf" ng-file='$ctrl.student.uploadIdentity' id="formFile" required>
                <div class="validation" ng-class="{'input-error': formValidation && stdRegistrationForm.financialProof.$error}">
                   Champ obligatoire
                </div> 
            </div>
            </li>             
        </ul>

            </div>


                            <!-- buttons -->
            <md-card-actions layout="row" layout-align="end center">
                    <button type="button" class="btn btn-danger m-1" ng-click="back('stage5')"><i class="fa-solid fa-backward"></i>&nbsp; Retour &nbsp;</button>
                    <button type="button" class="btn btn-danger m-1" ng-disabled="" ng-click="next('stage7')">&nbsp;Suivant&nbsp;<i class="fa-solid fa-forward"></i> </button>
            </md-card-actions>
            </md-card-content>
        </md-card> 


<!--
        |==========================================================================
        | Stage 7
        |==========================================================================
-->

<md-card  class="card-40-center animate-switch stepCard" md-theme-watch ng-switch-when="stage7" >
                <md-card-title>
                        <md-card-title-text>
                                <span class="md-headline">Fin du processus</span>
                </md-card-title>

                                <!-- first name -->
            <md-card-content>
 <!-- identification du père -->


           
            <div class="alert alert-warning mt-2" style="font-size: 0.75em;">

                Vous êtes parvenus au terme du processus de soumission de votre candidature.
                Veuillez cliquer sur le boutton enregistrer pour clôturer le processus
            </div>
           

    <div  class="container mt-3" >
            <div class="col-md-12 mb-3">
             
               

            </div>




    </div>


                            <!-- buttons -->
            <md-card-actions layout="row" layout-align="end center">
                    <button type="button" class="btn btn-danger btn-block" ng-click="back('stage6')">
                        <i class="fa-solid fa-backward"></i>  Retour 
                    </button>&nbsp;
                    <button type="submit" class="btn btn-success  btn-block "   >
                     <i class="fa-solid fa-paper-plane"></i> Enregistrer
                 </button>

            </md-card-actions>
            </md-card-content>
        </md-card> 


                </div>
                </form>
                </md-content>

        </div>
        <!-- comment -->

        
    </div>

</div>
</div>


        <?= $this->inlineScript()

        ->prependFile($this->basePath('js/jquery-3.7.0.min.js'))
        ?>
<script type="text/javascript">
$(document).on("click", ".browse", function() {
  var file = $(this).parents().find(".file");
  file.trigger("click");
});
$('input[type="file"]').change(function(e) {
  var fileName = e.target.files[0].name;
  $("#file").val(fileName);

  var reader = new FileReader();
  reader.onload = function(e) {
    // get loaded data and render thumbnail.
    document.getElementById("preview").src = e.target.result;
  };
  // read the image file as a data URL.
  reader.readAsDataURL(this.files[0]);
});


</script>

