<?php


($this->student['photo'])? $photo = stream_get_contents($this->student['photo']):$photo ='';

$defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();
$fontDirs = $defaultConfig['fontDir'];

$defaultFontConfig = (new Mpdf\Config\FontVariables())->getDefaults();
$fontData = $defaultFontConfig['fontdata'];

$mpdf = new \Mpdf\Mpdf([
    'fontDir' => array_merge($fontDirs, [
        $_SERVER["DOCUMENT_ROOT"]. '/font/Roboto',
    ]),
    'fontdata' => $fontData + [ // lowercase letters only in font key
        'roboto' => [
            'R' => 'Roboto-Regular.ttf',
            'I' => 'Roboto-Italic.ttf',
        ]
    ],
    'default_font' => 'roboto',
    'margin_left' => 18,
    'margin_right' => 18,
    'margin_top' => 45,
    'margin_bottom' => 16,
    'margin_header' => 9,
    'margin_footer' => 9    
]);


$mpdf->SetDocTemplate(__DIR__.'/template_header.pdf',1);	// 1|0 to continue after end of document or not - used on matching page numbers

//===================================================
$mpdf->AddPage();
$mpdf->WriteHTML('<div style="font-family: roboto; text-align:center; font-weight: bold; font-size:1.25em; ">REGISTRATION AND ACCEPTANCE TO OUR CONDITIONAL OFFER TO STUDY</div> ');
$mpdf->WriteHTML('<div style="text-align:center; font-style: italic; font-size:1.25em;">FICHE D’INSCRIPTION ET D’ACCEPTION DE L’OFFRE DE FORMATION SOUS CONDITION</div> ');
$mpdf->WriteHTML('<br /><table style="font-family: roboto; vertical-align:left; font-weight: bold; font-size:1.25em; "><tr ><td>Année académique: '.$this->academicYear.'</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>Numéro de dossier: '.$registrationDetails["numDossier"].'</td></tr></table></div> ');

$mpdf->WriteHTML('<br /><table style="font-family: roboto; vertical-align:left;"><tr ><td> Choix_1: '.$registrationDetails["choixFormation1"].'</td><td>&nbsp;&nbsp;&nbsp;&nbsp; Choix_2: '.$registrationDetails["choixFormation2"].'</td><td>&nbsp;&nbsp;&nbsp;&nbsp;Choix_3: '.$registrationDetails["choixFormation3"].'</td></tr></table></div> ');
$mpdf->WriteHTML('<br /><div style="height: 25px; padding-top:5px; background-color: #7393B3; font-size:1em;"><strong>IDENTIFICATION OF CANDIDATE</strong>/<i>IDENTIFICATION DU CANDIDAT</Stron></div> ');



$htmlEtudiant ='<div id="stp" ><table><tbody>'
        . '<tr><td></td><td></td><td rowspan="7"><img width="150" height="150"   src="data:image/jpeg;base64,'. $photo .'" /></></tr>'  
        . '<tr><td colspan="2"><span style="font-weight: bold">Nom(s) et Prénom(s):</span> '.$this->student["nom"].' '.$this->student["prenom"].'</td></tr>'
        . '<tr><td ><strong>Sexe:</strong> '.$this->student["gender"].'</td> <td><strong>CNI/PASSPORT</strong>'.$this->student["idNumber"].'</td>'
 
        . '</tr>'
        . '<tr><td><span style="font-weight: bold">Date de naissance:</span> '.$this->student["dateOfBirth"]->format('d/m/Y').' </td> <td><span style="font-weight: bold">Lieu de naissance:</span> '.$this->student["bornAt"].'</td></tr>'
        
          . '<tr>'
        . '<td ><span style="font-weight: bold">Nationalité:</span> '.$this->student["nationality"].'</td>'
        . '<td  ><span style="font-weight: bold">Région d\'origine:</span> '.$this->student["regionOfOrigin"]
        //. '&nbsp;&nbsp;<span style="font-weight: bold">Langue:</span> '.$this->student["language"].'</td>'
        . '</tr>'

        . '<tr>'
        . '<td ><span style="font-weight: bold">Email:</span> '.$this->student["email"].'</td>'
        . '<td ><span style="font-weight: bold">N° Téléphone:</span> '.$this->student["phoneNumber"].'</td>'
       // . '<td ></td>'
        . '</tr>'
        

        
        . '<tr>'
        . '<td><span style="font-weight: bold">Religion:</span> '.$this->student["religion"].'</td>'
        . '<td><span style="font-weight: bold">Langue:</span> '.$this->student["language"].'</td>' 
       // . '<td></td>  '     
        . '</tr>'     

        .'<tr>'
        . '<td><span style="font-weight: bold">Situation d\'emploi:</span> '.$this->student["workingStatus"].'</td>'
        . '<td ><span style="font-weight: bold">Situation matrimoniale:</span> '.$this->student["maritalStatus"].'</td>'
       // . '<td></td>  '
        . '</tr>'
        
                    
        . '</tbody></table></div>';
$mpdf->WriteHTML($htmlEtudiant);

$mpdf->WriteHTML('<br /><div style="height: 25px; padding-top:5px; background-color: #7393B3; font-size:1em;"><strong>CANDIDATES’S PARENTS’GUARDIAN’S/SPONSOR’S /INFORMATION</strong><br />'
        . ' <i>INFORMATIONS SUR LES PARENTS/TUTEURS/SPONSORS DU CANDIDAT</i></div> ');
foreach ($this->stdParent as $parent):
    if($parent["parentTye"]=="PERE"):
$htmlStdParent ='<div id="stp" ><table><tbody>'
        . '<tr><td colspan="2"> <strong>INFORMATION SUR LE PERE</strong></td></tr>'
        . '<tr><td style="width: 350px;"><span style="font-weight: bold">Nom(s) du père:</span>  </td><td>'.$parent["name"].'</td></tr>'
        . '<tr><td ><strong>Adresse:</strong> </td> <td>'.$parent["adresse"].'</td>'
        . '<tr><td ><strong>Numéro de téléphone:</strong> </td> <td>'.$parent["phoneNumber"].'</td>'
        . '<tr><td ><strong>Profession:</strong> </td> <td>'.$parent["profession"].'</td>'
        . '<tr><td ><strong>Ville de résidence:</strong> </td> <td>'.$parent["city"].'</td>'
        . '</tbody></table></div>'; 
    $mpdf->WriteHTML($htmlStdParent);
    endif;
    if($parent["parentTye"]=="MERE"):
$htmlStdParent ='<div id="stp" ><table><tbody>'
        . '<tr><td colspan="2"> <strong>INFORMATION SUR LA MERE</strong></td></tr>'
        . '<tr><td style="width: 350px;"><span style="font-weight: bold">Nom(s) de la mère:</span>  </td><td>'.$parent["name"].'</td></tr>'
        . '<tr><td ><strong>Adresse:</strong> </td> <td>'.$parent["adresse"].'</td>'
        . '<tr><td ><strong>Numéro de téléphone:</strong> </td> <td>'.$parent["phoneNumber"].'</td>'
        . '<tr><td ><strong>Profession:</strong> </td> <td>'.$parent["profession"].'</td>'
        . '<tr><td ><strong>Ville de résidence:</strong> </td> <td>'.$parent["city"].'</td>'
        . '</tbody></table></div>'; 
    $mpdf->WriteHTML($htmlStdParent);
    endif;    
    if($parent["parentTye"]=="TUTOR"):
$htmlStdParent ='<div id="stp" ><table><tbody>'
        . '<tr><td colspan="2"> <strong>INFORMATION SUR LE TUTEUR/SPONSOR</strong></td></tr>'
        . '<tr><td style="width: 350px;"><span style="font-weight: bold">Nom(s) du tuteur:</span>  </td><td>'.$parent["name"].'</td></tr>'
        . '<tr><td ><strong>Adresse:</strong> </td> <td>'.$parent["adresse"].'</td>'
        . '<tr><td ><strong>Numéro de téléphone:</strong> </td> <td>'.$parent["phoneNumber"].'</td>'
        . '<tr><td ><strong>Profession:</strong> </td> <td>'.$parent["profession"].'</td>'
        . '<tr><td ><strong>Ville de résidence:</strong> </td> <td>'.$parent["city"].'</td>'
        . '</tbody></table></div>'; 
    $mpdf->WriteHTML($htmlStdParent);
    endif;       
endforeach;

$mpdf->AddPage();

$mpdf->WriteHTML('<br /><div style="height: 25px; padding-top:5px; background-color: #7393B3; font-size:1em;"><strong>EDUCATIONNAL HISTORY</strong>/<i>CURSUS SCOLAIRE</Stron></div> ');   
$htmlCursus ='<div id="stp" ><table><tbody>'
        . '<tr><th style="width:25%;"> <strong>Année</strong></th><th style="width:25%;"> <strong>Etablissemnt</strong></th><th style="width:25%;"> <strong>Diplôme</strong></th><th style="width:25%;"> <strong>Mention</strong></th></tr>';
foreach ($cursusAcademic as $cursus):

$htmlCursus  .='<tr><td style="width:25%;">'.$cursus["annee"].'</td><td style="width:25%;"> '.$cursus["etablissement"].'</td><td >'.$cursus["diplome"].'</td><td >'.$cursus["mention"].'</td></tr>';

endforeach;
$htmlCursus  .='</tbody></table></div>';

$mpdf->WriteHTML($htmlCursus );
//===================================================

$mpdf->RestartDocTemplate();

//===================================================
/*$mpdf->AddPage();
$mpdf->WriteHTML('Hello World');
$mpdf->AddPage();
$mpdf->WriteHTML('Hello World');
$mpdf->AddPage();
$mpdf->WriteHTML('Hello World');

$mpdf->SetDisplayMode('fullpage');*/

$mpdf->list_indent_first_level = 0; // 1 or 0 - whether to indent the first level of a list

// Load a stylesheet
//$stylesheet = file_get_contents('assets/mpdfstyletables.css');

//$mpdf->WriteHTML($stylesheet, 1); // The parameter 1 tells that this is css/style only and no body/html/text
//$mpdf->WriteHTML($html,2);
//$mpdf->WriteHTML($htmlEtudiant,2);

$mpdf->Output($_SERVER["DOCUMENT_ROOT"].'/impressions/'.'mpdf.pdf', 'F');



?>


<style>
[ng\:cloak], [ng-cloak], .ng-cloak {
    display: none;
}

.submitForm {
	width: 100%;
}

.validation{
	padding-top: 5px;
	display: none;
	color: red;
}

.input-error {
  display: block;
  font-size: 12px;
}

</style>
<div class="container bg-light  rounded-3 "      );
            background-size: cover;
            color: #581845;
            " ng-controller="formCtrl as $ctrl" ng-init="init()">
    <br /><br />
<!DOCTYPE html>

   
   
<div cg-busy="{promise:myPromise,minDuration:700}"> 					
         
    <div class="row">             

        <br /><br /><br />
        Votre numéro de dossier:<h1><?=$this->registrationDetails["numDossier"]?></h1>
        <div class="alert alert-success">
            Vous êtes parvenus au terme du processus d'inscription. veuillez <a href='<?='../../impressions/'.'mpdf.pdf'?>'  download>télécharger votre fiche d'inscription ici</a>
            <br />
            Vous êtes priés de bien vouloir conserver soigneusement  votre numéro de dossier. Il vous permettra de vérifier son état d'avancement.
            
                       
        </div>
        
        <div class="alert alert-info">
        <?php if($this->registrationDetails["status"] ==0): 
        
            echo" Votre dossier est bien reçu et  en cours de traitement par nos soins. \n".'</ br>'; 
        ?>
            <br />
            <?php
            echo "Dans un delai d'au plus  tard  48H, vous récevrer la réponse à votre demande de candidature  par mail et par SMS";
        endif;
            ?>
        <?php if($this->registrationDetails["status"]==1) :
            
            echo"Félicitations!!!! Votre candidature a été acceptée . \n"; 
            echo "Vous êtes priès de procéder à votre inscription en ligne ";
            
           endif; ?>   
            
        <?php if($this->registrationDetails["status"] ==2) 
            
            echo"Désolé votre demande candidature a été rejetée"; 
            
            
            ?>             
        </div>
        
     

 <br /><br /><br />
                    
 
                                        











 
        <!-- comment -->
 
        
    </div>

</div>
</div>

        <?= $this->inlineScript()

        ->prependFile($this->basePath('js/jquery-3.7.0.min.js'))
        ?>
<script type="text/javascript">
$(document).on("click", ".browse", function() {
  var file = $(this).parents().find(".file");
  file.trigger("click");
});
$('input[type="file"]').change(function(e) {
  var fileName = e.target.files[0].name;
  $("#file").val(fileName);

  var reader = new FileReader();
  reader.onload = function(e) {
    // get loaded data and render thumbnail.
    document.getElementById("preview").src = e.target.result;
  };
  // read the image file as a data URL.
  reader.readAsDataURL(this.files[0]);
});


</script>

