


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
<div ng-cloak novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init();$ctrl.isModularComputation=0">

            <div class="row">
                <div class='col-md-4'>

                    <span> <a href="#!/examlist">Retour</a></span>
                </div>
                <div class="col-md-2"></div>

                
                <div class="pul-middle" ng-hide="$ctrl.isModularComputation===1">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Autres options
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <li><a href="" ng-click="$ctrl.printNotes()"><span>Imprimer PV complet</span></a>
                                        </li>
                                        <li><a href="" ng-click="$ctrl.printNotesFailures()"><span>Imprimer PV des échecs</span></a>
                                        </li>
                                        <!--<li><a href="" ng-click="$ctrl.clotureCalculNotes($ctrl.selectedUe.ue_class_id)"><span>Imprimer liste étudiants</span></a>
                                        </li> -->
                                    </ul>
                                </div>
                </div>
                
                
                <div class="pul-middle" ng-show="$ctrl.isModularComputation===1">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Autres options
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <li><a href="" ng-click="$ctrl.printSubjectMarkReport()"><span>Imprimer le PV de la  Matière</span></a>
                                        </li>
                                        <li><a href="" ng-click="$ctrl.printModuleMarkReport()"><span>Imprimer le PV du Module</span></a>
                                        </li>
                                        <!--<li><a href="" ng-click="$ctrl.clotureCalculNotes($ctrl.selectedUe.ue_class_id)"><span>Imprimer liste étudiants</span></a>
                                        </li> -->
                                    </ul>
                                </div>
                </div>                
            </div>
        </div>

<div class="form-view-main">
    <div class="form-view">


<md-content layout-padding   ng-show="$ctrl.isModularComputation===0">

    <form   name="examForm" >
        <div layout-gt-sm='row' >

            <div class = "col-xs-6">
                <div layout-gt-sm='column' style="padding-top: 15px"
                        <md-input-container>            
                            <md-radio-group ng-model="$ctrl.typePV"  layout="row">
                              <md-radio-button value="SESSION" class="md-primary">PV de session</md-radio-button>
                              <md-radio-button value="FINAL" class="md-primary">PV Définitif</md-radio-button>
                              
                            </md-radio-group>
                        </md-input-container>
                </div>                
                <div layout-gt-sm='row' style="margin-top: 30px;">
                    <md-input-container class="md-block" flex-gt-sm>
                        <label>Classe:</label>
                        <md-autocomplete  md-search-text="$ctrl.searchClasse" 
                                         md-selected-item="$ctrl.selectedClasse"  
                                         md-items="item in $ctrl.query($ctrl.searchClasse)" 
                                         md-item-text="item.code" 
                                         md-min-length="0"
                                         placeholder="Faites de la classe" 
                                         md-selected-item-change="$ctrl.selectedItemChange(item)"
                                         md-input-name="classe"
                                         md-no-asterisk
                                         required>
                            <md-item-template>
                              <span md-highlight-text="$ctrl.searchClasse" md-highlight-flags="^i">{{item.code}}</span>

                            </md-item-template>
                            <md-not-found>
                              Aucun élément correspondant à "{{$ctrl.searchClasse}}" n'a été trouvé.

                            </md-not-found>
                        </md-autocomplete>
                            <div ng-messages="examForm.classe.$error">
                                <div ng-message="required">Ce champ est obligatoire</div>
                            </div> 
                    </md-input-container >
                </div>

                <div layout-gt-sm="column" style="padding-top: 0px; margin-top: -5px;">
                    <md-input-container>
                        <md-checkbox ng-model="$ctrl.isModularComputation"  class="md-primary"              
                            aria-label="Actif?"
                            ng-true-value="1"
                            ng-false-value="0"> 
                            Calcul par module?
                        </md-checkbox>
                    </md-input-container>

                </div>            


                <div layout-gt-sm='column' style="margin-top: -10px;" >
                    <md-input-container>
                        <label>Semestre</label>
                        <md-select name="semester" ng-model="$ctrl.selectedSem" ng-model-options="{trackBy: '$value.id'}" md-on-open="$ctrl.asignedSemToClasse($ctrl.selectedClasse.code);" ng-change="$ctrl.asignedExamSession($ctrl.selectedSem.id);$ctrl.activateUeSelect(); $ctrl.loadUE($ctrl.selectedClasse);"
                                    md-no-asterisk required >
                            <md-option ng-disabled="true"><em>---Choix du Semestre---</em></md-option>
                          <md-option ng-repeat="sem in $ctrl.semesters" ng-value="sem"  >
                            {{sem.name}}
                          </md-option>
                        </md-select>
                        <div class="errors" ng-messages="examForm.semester.$error">
                          <div ng-message="required">Champ obligatoire</div>
                        </div>
                    </md-input-container>  
                </div> 
                
                <md-input-container ng-show="$ctrl.typePV==='SESSION'?true:false" style="margin-top:20px;">
                    <label>Session d'evaluation</label>
                    <md-select name="session1"   ng-model="$ctrl.selectedExamSession" ng-model-options="{trackBy: '$value.id'}" md-on-open="$ctrl.asignedExamSession($ctrl.selectedSem.id);" 
                               ng-change="$ctrl.resetSubject();"  md-no-asterisk ng-required='$ctrl.isExamSessionRequired'>
                        <md-option ng-disabled="true"  ><em>---Choix de la session d'evaluation---</em></md-option>
                       <md-option ng-repeat="examSession in $ctrl.examSessions" ng-value="examSession"  >
                        {{examSession.sessionName}}
                      </md-option>

                    </md-select>
                    <div class="errors" ng-messages="examForm.session1.$error">
                      <div ng-message="required">Champ obligatoire</div>
                    </div>
                </md-input-container> 
                
                <div layout-gt-sm='column' style="padding-top: 15px">
                    <md-input-container>
                    <label>Unité d'enseignement</label>
                    
                    <md-select name="ue" ng-disabled="!$ctrl.isActivatedUeSelect" ng-model="$ctrl.selectedUe;" 
                               ng-model-options="{trackBy: '$value.id'}"  md-on-open="$ctrl.loadUE($ctrl.selectedClasse)" 
                               ng-change="$ctrl.loadExams($ctrl.selectedUe.id,-1); $ctrl.loadSubjects($ctrl.selectedUe.id,$ctrl.selectedClasse.id);$ctrl.isModuleComputation=0;" md-no-asterisk ng-required="true">
                        <md-option ng-disabled="true"  ng-value="{id:-1,code:-1}">
                            <em >Choisissez une UE</em>
                         
                        </md-option>
                      <md-option ng-repeat="ue in $ctrl.ues" ng-value="ue" >
                        {{ue.code}}[{{ue.name}}]

                      </md-option>


                    </md-select>
                    <div class="errors" ng-messages="examForm.ue.$error">
                        <div ng-message="required">Champ obligatoire</div>
                      </div>
                    </md-input-container> 
                    </div>

            </div>

            <div class = "col-xs-6"  >
                <!-- Display examlis on a table -->
                <div class="row">

                <table class="table table-fixed" style="font-size:0.8em; background-color: #dfe4ea; color: #0c2461;" ng-show="tableExamShow===1">
                    <thead>

                        <tr class="bg-primary">
                            <th class="col-xs-1 align-middle" >Num</th>
                            <th class="col-xs-4 align-middle" >Code examen</th>
                            <th class="col-xs-1 align-middle">Type</th>
                            <th class="col-xs-3 align-middle">Matière</th>
                            <th class="col-xs-1 align-middle">Note</th>
                            <th class="col-xs-2 align-middle">Date</th>
                        </tr>
                   </thead>
                    <tbody>

                        <tr ng-repeat="exam in $ctrl.exams" style="font-size:0.8em;">
                          <td ng-bind="exam.num" class="col-xs-1"> </td>
                          <td  class="col-xs-4" ><a ng-href="home#!/newexam/{{exam.id}}" ng-bind="exam.code"></a></td>
                          <td ng-bind="exam.type" class="col-xs-1"></td>
                          <td ng-bind="exam.subject" class="col-xs-3"></td>
                          <td ng-bind="exam.isMarkRegistered===1?'OK':'ND'" class="col-xs-1" ng-class="{'zf-red': (exam.isMarkRegistered!==1)}"></td>
                          <td ng-bind="$ctrl.formatDate(exam.date) | date:'dd/MM/yyyy'" class="col-xs-2"></td>
                        </tr>

                    </tbody>

                    </table>
               
                </div>
            </div>           
        </div>

        <div layout-gt-sm='row'>
            <div class="col-md-6 pull-left">
                <button class="btn btn-inverse" ng-click="$ctrl.clotureCalculNotes($ctrl.selectedUe.ue_class_id)" ng-disabled="examForm.$invalid||$ctrl.selectedUe.mark_calculation_status===1"><i class="fa fa-lock" ></i>&nbsp;Clôture</button>&nbsp;&nbsp;

            </div>
            <div class="col-md-6 text-right">
                <button class="btn btn-danger" ng-click="$ctrl.calculNotes()" ng-disabled="examForm.$invalid||$ctrl.selectedUe.mark_calculation_status===1"><i class="fa fa-refresh" ></i>&nbsp;Générer le PV</button>&nbsp;&nbsp;&nbsp;
                <button class="btn btn-primary" ng-click="$ctrl.deliberation()" ng-disabled="examForm.$invalid||$ctrl.selectedUe.mark_calculation_status===1"><i class="fa fa-refresh" ></i>&nbsp;Délibération</button>
            </div>
        </div>
      

    </form>
    </md-content>
<!----------------------------------------------------------------------------------------------->
<!----------------------------------------------------------------------------------------------->
<!-------In case of modular calculation show up the following form ------------------------------>
<!----------------------------------------------------------------------------------------------->
<!----------------------------------------------------------------------------------------------->
    <md-content layout-padding  ng-show="$ctrl.isModularComputation===1" >

    <form   name="examFormModule" >
        <div layout-gt-sm='row' >

            <div class = "col-xs-6">
                <div layout-gt-sm='column' style="padding-top: 15px"
                        <md-input-container>            
                            <md-radio-group ng-model="$ctrl.typePV"  layout="row">
                              <md-radio-button value="SESSION" class="md-primary">PV de session</md-radio-button>
                              <md-radio-button value="FINAL" class="md-primary">PV Définitif</md-radio-button>
                              
                            </md-radio-group>
                        </md-input-container>
                </div>
                <div layout-gt-sm='row' >
                    <md-input-container class="md-block" flex-gt-sm>
                        <label>Classe:</label>
                        <md-autocomplete  md-search-text="$ctrl.searchClasse" 
                                         md-selected-item="$ctrl.selectedClasse"  
                                         md-items="item in $ctrl.query($ctrl.searchClasse)" 
                                         md-item-text="item.code" 
                                         md-min-length="0"
                                         placeholder="Faites de la classe" 
                                         md-selected-item-change="$ctrl.selectedItemChange(item)"
                                         md-input-name="classe"
                                         md-no-asterisk
                                         required>
                            <md-item-template>
                              <span md-highlight-text="$ctrl.searchClasse" md-highlight-flags="^i">{{item.code}}</span>

                            </md-item-template>
                            <md-not-found>
                              Aucun élément correspondant à "{{$ctrl.searchClasse}}" n'a été trouvé.

                            </md-not-found>
                        </md-autocomplete>
                            <div ng-messages="examFormModule.classe.$error">
                                <div ng-message="required">Ce champ est obligatoire</div>
                            </div> 
                    </md-input-container >
                </div>

                <div layout-gt-sm="column" style="padding-top: 0px; margin-top: -5px;">
                    <md-input-container>
                        <md-checkbox ng-model="$ctrl.isModularComputation"  class="md-primary"              
                            aria-label="Actif?"
                            ng-true-value="1"
                            ng-false-value="0"> 
                            Calcul par module?
                        </md-checkbox>
                    </md-input-container>

                </div>            


                <div layout-gt-sm='column' style="margin-top: -10px;" >
                    <md-input-container>
                        <label>Semestre</label>
                        <md-select name="semester" ng-model="$ctrl.selectedSem" ng-model-options="{trackBy: '$value.id'}" md-on-open="$ctrl.asignedSemToClasse($ctrl.selectedClasse.code);" ng-change="$ctrl.activateUeSelect(); $ctrl.loadUE($ctrl.selectedClasse);"
                                    md-no-asterisk required >
                            <md-option ng-disabled="true"><em>---Choix du Semestre---</em></md-option>
                          <md-option ng-repeat="sem in $ctrl.semesters" ng-value="sem"  >
                            {{sem.name}}
                          </md-option>
                        </md-select>
                        <div class="errors" ng-messages="examFormModule.semester.$error">
                          <div ng-message="required">Champ obligatoire</div>
                        </div>
                    </md-input-container>  
                </div> 

                <md-input-container ng-show="$ctrl.typePV==='SESSION'?true:false" style="margin-top:20px;">
                    <label>Session d'evaluation</label>
                    <md-select name="session1"   ng-model="$ctrl.selectedExamSession" ng-model-options="{trackBy: '$value.id'}" md-on-open="$ctrl.asignedExamSession($ctrl.selectedSem.id);" 
                                ng-change="$ctrl.resetSubject()" md-no-asterisk ng-required='$ctrl.isExamSessionRequired'>
                        <md-option ng-disabled="true"  ><em>---Choix de la session d'evaluation---</em></md-option>
                       <md-option ng-repeat="examSession in $ctrl.examSessions" ng-value="examSession"  >
                        {{examSession.sessionName}}
                      </md-option>

                    </md-select>
                    <div class="errors" ng-messages="examForm.session1.$error">
                      <div ng-message="required">Champ obligatoire</div>
                    </div>
                </md-input-container> 
                <div layout-gt-sm='column' style="padding-top: 15px"  >
                    <md-input-container>
              
                    <label>Module</label>
                    <md-select name="ue" ng-disabled="!$ctrl.isActivatedUeSelect" ng-model="$ctrl.selectedUe;" 
                               ng-model-options="{trackBy: '$value.id'}"  md-on-open="$ctrl.loadUE($ctrl.selectedClasse)" 
                               ng-change="$ctrl.loadExamsPerModuleStatus($ctrl.selectedUe.id); $ctrl.loadSubjects($ctrl.selectedUe.id,$ctrl.selectedClasse.id);$ctrl.isModuleComputation=1;" md-no-asterisk ng-required="true">
                        <md-option ng-disabled="true"  ng-value="{id:-1,code:-1}">
                            <em>Choisissez un module</em>
                        </md-option>
                      <md-option ng-repeat="ue in $ctrl.ues" ng-value="ue" >
                        {{ue.code}}[{{ue.name}}]

                      </md-option>


                    </md-select>
                    <div class="errors" ng-messages="examFormModule.ue.$error">
                        <div ng-message="required">Champ obligatoire</div>
                      </div>
                    </md-input-container> 
                </div>            
                <div layout-gt-sm='column' style="padding-top: 15px"  >
                    <md-input-container>
                    <label>Unité d'enseignement</label>
                    <md-select name="subject" ng-disabled="!$ctrl.isActivatedMatiereSelect" ng-model="$ctrl.selectedSubject;" 
                               ng-model-options="{trackBy: '$value.id'}"   
                               ng-change=" $ctrl.loadExams($ctrl.selectedUe.id,$ctrl.selectedSubject.id); $ctrl.isModuleComputation=0;" md-no-asterisk ng-required="true">
                        <md-option ng-disabled="true"  ng-value="{id:-1,code:-1}"><em>Choisissez une UE</em></md-option>
                      <md-option ng-repeat="subject in $ctrl.subjects" ng-value="subject" >
                        {{subject.subjectCode}}[{{subject.subjectName}}]

                      </md-option>


                    </md-select>
                    <div class="errors" ng-messages="examFormModule.subject.$error">
                        <div ng-message="required">Champ obligatoire</div>
                      </div>
                    </md-input-container> 
                </div> 
                

                
                
                
            </div>

            <div class = "col-xs-6"  >
                <!-- Display examlis on a table -->
                <div>

                <table class="table table-fixed" style="font-size:0.8em; background-color: #dfe4ea; color: #0c2461;" ng-show="tableExamShow===1">
                    <thead>

                        <tr class="bg-primary">
                            <th class="col-xs-1 align-middle" >Num</th>
                            <th class="col-xs-4 align-middle" >Code examen</th>
                            <th class="col-xs-1 align-middle">Type</th>
                            <th class="col-xs-3 align-middle">Matière</th>
                            <th class="col-xs-1 align-middle">Note</th>
                            <th class="col-xs-2 align-middle">Date</th>
                        </tr>
                   </thead>
                    <tbody>

                        <tr ng-repeat="exam in $ctrl.exams" style="font-size:0.8em;">
                          <td ng-bind="exam.num" class="col-xs-1"> </td>
                          <td  class="col-xs-4" ><a ng-href="home#!/newexam/{{exam.id}}" ng-bind="exam.code"></a></td>
                          <td ng-bind="exam.type" class="col-xs-1"></td>
                          <td ng-bind="exam.subject" class="col-xs-3"></td>
                          <td ng-bind="exam.isMarkRegistered===1?'OK':'ND'" class="col-xs-1" ng-class="{'zf-red': (exam.isMarkRegistered!==1)}"></td>
                          <td ng-bind="$ctrl.formatDate(exam.date) | date:'dd/MM/yyyy'" class="col-xs-2"></td>
                        </tr>

                    </tbody>

                    </table>

                <table class="table table-fixed" style="font-size:0.8em; background-color: #dfe4ea; color: #0c2461;" ng-show="tableModuleShow===1">
                    <thead>

                        <tr class="bg-primary">
                            <th class="col-xs-2 align-middle" >Num</th>

                            <th class="col-xs-4 align-middle">Matière</th>
                            <th class="col-xs-3 align-middle">Poids</th>
                            <th class="col-xs-3 align-middle">Note</th>

                        </tr>
                   </thead>
                    <tbody>

                        <tr ng-repeat="exam in $ctrl.exams" style="font-size:0.8em;">
                          <td ng-bind="exam.num" class="col-xs-2"> </td>
                          <td ng-bind="exam.subjectCode" class="col-xs-4"></td>
                          <td ng-bind="exam.subjectWeight" class="col-xs-3"></td>
                          <td ng-bind="exam.moduleConsolidationStatus===1?'OK':'ND'" class="col-xs-3" ng-class="{'zf-red': (exam.isMarkRegistered!==1)}"></td>
                        </tr>

                    </tbody>

                    </table>                
                </div>
                
                <div layout-gt-sm="column" style="padding-top: 0px; margin-top: -5px;">
                <md-input-container>
                    <md-checkbox ng-model="$ctrl.generatePvConsolide"  class="md-primary"              
                        aria-label="Actif?"
                        ng-true-value="1"
                        ng-false-value="0"> 
                        PV consolidé?
                    </md-checkbox>
                </md-input-container>

            </div> 
            </div> 
            
        </div>

        <div layout-gt-sm='row' >
            <div class="col-md-3 pull-left">
                <button class="btn btn-inverse" ng-click="$ctrl.clotureCalculNotes($ctrl.selectedUe.ue_class_id)" ng-disabled="examFormModule.$invalid||$ctrl.selectedUe.mark_calculation_status===1"><i class="fa fa-lock" ></i>&nbsp;Clôture</button>&nbsp;&nbsp;

            </div>
            
             
            <div class="col-md-9 text-right">
                <button class="btn btn-danger" ng-click="$ctrl.calculNotes($ctrl.generatePvConsolide)" ng-disabled="$ctrl.generatePvConsolide===0"><i class="fa fa-refresh" ></i>&nbsp;Générer le PV consolidé</button>&nbsp;&nbsp;&nbsp;
                <button class="btn btn-danger" ng-click="$ctrl.calculNotes($ctrl.generatePvConsolide)" ng-disabled="examFormModule.$invalid||$ctrl.selectedUe.mark_calculation_status===1"><i class="fa fa-refresh" ></i>&nbsp;Générer le PV </button>&nbsp;&nbsp;&nbsp;
                <button class="btn btn-primary" ng-click="$ctrl.deliberation()" ng-disabled="$ctrl.selectedUe.mark_calculation_status===1"><i class="fa fa-refresh" ></i>&nbsp;Délibération</button>
            </div>
        </div>        

    </form>
    </md-content>

<p></p>
             <!--tabs widget-->
              <div class="row" ng-hide="$ctrl.isModuleComputation===1"> 
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="">Liste des étudiants inscrits àl'unité d'enseignement</a>
                        </li>
                    </ul>
                    <div id =" tab1">

                        
                        <table class="table table-striped table-condensed">
                            <thead>
                                <tr class="bg-primary">
                                    <th></th><th style="vertical-align: middle; align: center" ng-repeat="(key, val) in $ctrl.report[0]">{{ key }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="row in $ctrl.report" >
                                    <td>{{$index+1}}</td>
                                    <td style="vertical-align: middle; align: center;"  ng-repeat="(key,column) in row" 
                                        ng-class="{
                                            'zf-red': ((column.isFromDeliberation===1)&& (key==='Note Finale')) || ((column!='PASSED')&& (key==='Statut')),        
                                            'text-primary':((key==='Grade') ||(key==='Points'))}"
                                        ng-style="{'font-weight': ((key==='Grade') ||(key==='Points'))?'bold':'normal',
                                            'background-color': ((column!='PASSED')&& (key==='Statut'))?'#FF0000':(key==='Statut')?'#32CD32':''}"
                                        >
                                      {{ (key==='Note Finale')?column.note:(key==='Statut')?'':column }}
                                      {{ (key==='Note Finale')&&(column.isFromDeliberation===1)?'[D]':'' }}
                                    
                                    </td>
                                </tr>
                            </tbody>
                        </table>                        
                    </div>
                    <div id="tab2"></div>
                 </div>
                <!--End tab-->
                
                
             <!--tabs widget-->
             <div class="row" ng-show="$ctrl.isModuleComputation===1"> 
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="">Liste des étudiants inscrits àl'unité d'enseignement</a>
                        </li>
                    </ul>
                    <div id =" tab1">
                                        <table class="table table-striped table-condensed">
                                            <thead>
                                                <tr class="bg-primary"><th></th>
                                                  <th style="vertical-align: middle; align: center" ng-repeat="(key, val) in $ctrl.regStd[0]">{{ key }}</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="row in $ctrl.regStd" >
                                    <td>{{$index+1}}</td>
                                    <td style="vertical-align: middle; align: center;"  ng-repeat="(key,column) in row" 
                                        ng-class="{
                                            'zf-red': ((column.isFromDeliberation===1)&& (key==='Note Finale')) || ((column!='PASSED')&& (key==='Statut')),        
                                            'text-primary':((key==='Grade') ||(key==='Points'))}"
                                        ng-style="{'font-weight': ((key==='Grade') ||(key==='Points'))?'bold':'normal',
                                            'background-color': ((column!='PASSED')&& (key==='Statut'))?'#FF0000':(key==='Statut')?'#32CD32':''}"
                                        >
                                      {{ (key==='Note Finale')?column.note:(key==='Statut')?'':column }}
                                      {{ (key==='Note Finale')&&(column.isFromDeliberation===1)?'[D]':'' }}
                                    
                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                    </div>
                    <div id="tab2"></div>
                 </div>
                <!--End tab-->                
                
            </div>  
        </div>

</div>