
    
<form  ng-submit="saveAcadYear()" name="acadForm" novalidate ng-cloak>
        <div class="well" style="margin-left: -30px; margin-right: -30px;">

            <div class="row"  ng-init="init()">
                <div class='col-lg-2'>

                    <button  type="submit" class="btn btn-danger" ng-hide="isUpdate" ng-disabled="acadForm.$invalid">Enrégistrer</button>
                    <button  type="button" ng-click="updateAcadYear()"class="btn btn-danger" ng-show="isUpdate" ng-disabled="acadForm.$invalid">Modifier</button>
                    <span> <a href="#!/acadyr-list">Retour</a></span>
                </div>
                <div class="col-lg-3"></div>
                <div >
                    <button  type="button" ng-click="deleteAcadYear()"class="btn btn-default" ng-disabled="acadForm.$invalid||!isUpdate"><i class="fa fa-trash-o"></i>&nbsp;Supprimer</button>
                    <button  type="button" class="btn btn-primary" ng-disabled="acadForm.$invalid||!isUpdate"><i class="fa fa-lock"></i>&nbsp;Clôturer</button>
                    <button  type="button" ng-click="activeYrDataMigration()" class=" btn btn-primary" ng-disabled="acadForm.$invalid||!isUpdate"><i class="fa fa-exchange"></i>&nbsp;Migrer les données</button>
                </div>
            </div>
        </div>
        <div class="form-view-main">
            <div class="form-view">
<div   ng-cloak class="md-inline-form">


    <md-content layout-padding >

    <div layout-gt-sm layout-gt-xs layout-xs='row' >
        <md-input-container class="md-block"  flex='40'>

            <label>Code</label>
            <input type="text" name="code" ng-model="acadyr.code" ng-required="true" md-no-asterisk /> 
            <div ng-messages="acadForm.code.$error">
                    <div ng-message="required">le champ code est obligatoire</div>
            </div> 
        </md-input-container>
        <md-input-container class="md-block"  flex='60'>
            <label>Intitulé</label>
            <input type="text"  name="name" ng-model="acadyr.name" ng-required="true" md-no-asterisk  /> 
            <div ng-messages="acadForm.name.$error">
                    <div ng-message="required">le champ nom est obligatoire</div>
            </div>
        </md-input-container>
    </div>

      <md-datepicker ng-model="acadyr.startingDate"  md-placeholder="Date de début">
                        
      </md-datepicker>
   
      <md-datepicker ng-model="acadyr.endingDate"  md-placeholder="Date de fin">
                         
      </md-datepicker>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Année en cours? 
      <md-checkbox
             ng-model="acadyr.isDefault"
            aria-label="Checkbox 2"
            ng-true-value="true"
            ng-false-value="false"
            class="md-warn md-align-top-left" flex>
          

    </md-checkbox>
  
   <div layout-gt-sm layout-gt-xs layout-xs='row' >
            
    <div layout-gt-sm='column' >
        <fieldset class="standard">
            <legend>Admission</legend>
            <div layout-gt-sm="row">   
        
                  <md-datepicker ng-model="acadyr.admissionStartingDate" md-min-date="acadyr.startingDate" md-max-date="acadyr.endingDate" md-placeholder="Date de début">

                  </md-datepicker>
               
                  <md-datepicker ng-model="acadyr.admissionEndingDate" md-min-date="acadyr.startingDate" md-max-date="acadyr.endingDate" md-placeholder="Date de fin">

                  </md-datepicker>
               
            </div>
        </fieldset>
    </div>
    <div layout-gt-sm='column' >
        <fieldset>
            <legend>Inscription</legend>
            <div layout-gt-sm="row" class="md-block" >   
               
               
                  <md-datepicker ng-model="acadyr.adminRegistrationStartingDate" md-min-date="acadyr.startingDate" md-max-date="acadyr.endingDate" md-placeholder="Date de début">

                  </md-datepicker>
               
              
                 
                  <md-datepicker ng-model="acadyr.adminRegistrationEndingDate" md-min-date="acadyr.startingDate" md-max-date="acadyr.endingDate" md-placeholder="Date de fin">

                  </md-datepicker>
               
            </div>
        </fieldset>
    </div>            
            

        </div>
                        </div>


                </form>


                <!--tabs widget-->
                <div class="row" >
                    <uib-tabset>
                        <uib-tab >
                            <uib-tab-heading>
                                <span>Périodes de l'année académique</span>
                            </uib-tab-heading>


                  

                                        <table class="table table-striped">
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th>Code</th>
                                                    <th>Nom</th>
                                                    <th>Date de début</th>
                                                    <th>date de fin</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="sem in semesters"  >
                                                  <td ng-bind="sem.code"></td>
                                                  <td ng-bind="sem.name"></td>
                                                   <td ng-bind="formatDate(sem.startingDate) | date:'dd/MM/yyyy'"></td>
                                                  <td ng-bind="formatDate(sem.endingDate) | date:'dd/MM/yyyy'"></td>
                                                  <td style="width:20%">
                                                      <div class="btn-group" style="float:right">
                                                      <button  type="button" ng-click="showUpdateSemester(sem)" class="btn btn-default btn"><i class="fa fa-edit"></i></button>
                                                      <button  type="button" ng-click="semDelete(sem.id)" class="btn btn-default btn" ><i class="fa fa-trash-o"></i></button></td></span>
                                                  </div>
                                                  </td>
                                                </tr>
                                            </tbody>
                                        </table>
                        <a class="btn btn-primary" ng-click="showSemester(sem)">Ajouter un semestre</a>

                </uib-tab>                
                        <!--End tab-->
                <!--tabs widget-->
                
                        <uib-tab >
                            <uib-tab-heading>
                                <span>Sessions d'évaluation</span>
                            </uib-tab-heading>

                                        <table class="table table-striped">
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th>Type de session</th>
                                                    <th>Code session</th>
                                                    <th>Intitulé</th>

                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="session in examSessions"  >
                                                   <td ng-bind='session.sessionType==="RAT"?"Rattrapage":"Normale"'></td>
                                                  <td ng-bind="session.sessionCode"></td>
                                                  <td ng-bind="session.sessionName"></td>

                                                  <td style="width:20%">
                                                      <div class="btn-group" style="float:right">
                                                      <button  type="button" ng-click="showManageSessions(session)" class="btn btn-default btn"><i class="fa fa-edit"></i></button>
                                                      <button  type="button" ng-click="deleteExamSession(session)" class="btn btn-default btn" ><i class="fa fa-trash-o"></i></button></td></span>
                                                  </div>
                                                  </td>
                                                </tr>
                                            </tbody>
                                        </table>
                        <a class="btn btn-primary" ng-click="showManageSessions(session)">Ajouter une session d'évaluation</a>

                        </uib-tab> 
                <!--End tab-->
                <!--tabs widget-->
                        <uib-tab >
                            <uib-tab-heading>
                                <span>Associer les sessions aux semestres</span>
                            </uib-tab-heading>

                                        <table class="table table-striped">
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th>Intitulé Semestre</th>
                                                    <th>sessions</th>
                                                 
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr >
                                                    <td>
                                                        <div layout="row" layout-align="start" flex>
                                                        <md-input-container flex="100">
                                                            <label>Semestres</label>
                                                                <md-select ng-model='selectedSem' >
                                                                    <md-optgroup>
                                                                        <md-option ng-repeat="sem in semesters" ng-value ='sem.id'
                                                                                   
                                                                                   ng-click='loadSessionsBySem(sem.id)'
                                                                                   >
                                                                           {{sem.name}}
                                                                        </md-option>
                                                                    </md-optgroup>
                                                                </md-select>
                                                        </md-input-container> 
                                                        </div>
                                                    </td>
                                                  <td>
                                                      <div layout="row" layout-align="start" flex>
                                                        <md-input-container flex="100">
                                                            <label>Sessions d'examen</label>
      
                                                                <md-select placeholder="Taxes/Retenues applicables" ng-model="selectedSessions" multiple >
                                                                    <md-option ng-repeat="item in examSessions" ng-value="item.id" >
                                                                        {{item.sessionName}}</md-option>
                                                                </md-select>
                                                        </md-input-container>
                                                      </div>
                                                  </td>
                                                  <td >
                                                  <button  type="button" ng-click="toggleSessionSelection(selectedSessions,selectedSem)" class="btn btn-default btn-xs btn-danger" ><i class="fa fa-refresh"></i></button>   
                                                  </td>
                                                </tr>
                                            </tbody>
                                        </table>
                     

                        </uib-tab>
                    </uib-tabset>
                <!--End tab-->                
            </div>  
        </div>

