
<!------ Include the above in your HEAD tag ---------->

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="js/jquery-3.7.0.min.js" type="text/javascript"></script>
        <script src="js/bootstrap-4.1.0.min.js" type="text/javascript"></script>
        <link href="css/bootstrap-4.1.0.css" rel="stylesheet" type="text/css"/>
        <link href="css/login.css" rel="stylesheet" type="text/css"/>
        <title></title>
    </head>
    <body>
 <a href="home" class="btnForgetPwd" value="Login">[Retour]</a>
        <div class="container register">
            <div class="row">
                <div class="col-md-12">
                    <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Je suis étudiant</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Je suis enseignant</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active text-align form-new" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <h3 class="register-heading">Login étudiant</h3>
                            <div class="row register-form">
                                <div class="col-md-12">
                                    <form method="post">
                                        <div class="form-group">
                                            <input type="text" name="LGform1_user" class="form-control" placeholder="Votre matricule *" value="" required=""/>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="LGform1_pwd" class="form-control" placeholder="Date de naissance exp 18042004 *" value="" required=""/>
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" name="LGform1" class="btnContactSubmit" value="Login" />
                                            
                                        </div>
                                        <a href="ForgetPassword.php" class="btnForgetPwd" value="Login">Se rapprocher des services de  scolarité au cas où vous avez oublié votre mot de pass</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show text-align form-new" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            <h3  class="register-heading">Login enseignant</h3>
                            <div class="row register-form">
                                <div class="col-md-12">
                                    <form method="post">
                                        <div class="form-group">
                                            <input type="text" name="LGform2_user" class="form-control" placeholder="Votre numéro de téléphone *" value="" required="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="LGform2_pwd" class="form-control" placeholder="Mot de passe *" value="" required=""/>
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" name="LGform2" class="btnContactSubmit" value="Login" />
                                            
                                        </div>
                                        <a href="#" class="btnForgetPwd" value="Login">Se rapprocher des service de  scolarité au cas où vous avez oublié votre mot de passe</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>