<div class="container ">
  <div class="row">
      <div class="col-sm">
        <div class="card" style="width: 14rem;">
          <div class="card-body">
            <h5 class="card-title"></h5>
            <p class="card-text"> <i class="fa fa-user"></i></p>
            <a href="#" class=" txt-primary">Profile</a>
          </div>
        </div>
      </div>

      <div class="col-sm">
        <div class="card" style="width: 14rem;">
            <a href="lSubjects" class="text-dark" >
          <div class="card-body">
            <h5 class="card-title"></h5>
            <p class="card-text"><i class="fa fa-book-open"></i></p>
            <span>Unités d'enseignements</span>
          </div>
            </a>
        </div>
      </div>  
      <div class="col-sm">
        <div class="card" style="width: 14rem;">
        <a href="#" class="text-dark" >
          <div class="card-body">
            <h5 class="card-title"></h5>
            <p class="card-text"><i class="fa fa-calendar-days"></i></p>
            <span class="text-primary">Emploi de temps</span>
          </div>
        </a>
        </div>
      </div>       
      <div class="col-sm">
        <div class="card" style="width: 14rem;">
          <div class="card-body">
            <h5 class="card-title"></h5>
            <p class="card-text"><i class="fa fa-list-check"></i></p>
            <a href="#" class="txt-primary">Evaluations</a>
          </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card" style="width: 14rem;">
          <div class="card-body">
            <h5 class="card-title"></h5>
            <p class="card-text"><i class="fa fa-cart-plus"></i></p>
            <a href="#" class="txt-primary">Factures</a>
          </div>
        </div>
      </div>     
  </div>
</div>