

<nav  style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="goLecturer">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Unité d'enseignement</li>
  </ol>
</nav>

<h1 class="mt-4">Suivi du volume horaire</h1>
   <ol class="breadcrumb mb-4">
       <li class="breadcrumb-item active">Tableau de progression</li>
   </ol>




         
        <div  style="background-color: #dfe4ea;" >
            <div class="row">  
            <div ng-cloak  style="margin-top:25px;">

            <md-input-container class="column md-block" flex-gt-sm>
      
            <br />
                            <div flex-gt-sm flex="50">
                                <table class=" table table-bordered bordered table-striped table-condensed datatable" style="font-size:0.8em; background-color: #dfe4ea; color: #0c2461;" ui-jq="dataTable" ui-options="dataTableOpt">
                                    <thead>
                                        <tr style="background-color:#708090; text-align: center;">
                                        <th style="vertical-align: middle;" rowspan="2">#</th>
                                        <th style="vertical-align: middle;" rowspan="2">UE</th>
                                        <th style="vertical-align: middle;" rowspan="2">Sem</th>
                                        <th style="vertical-align: middle;" rowspan="2">Classe</th>
                                        <th style="vertical-align: middle; width: 30%;" colspan="4">Volume Horaire</th>
                                        
                                    </tr>
                                    <tr style="background-color:#708090; text-align: center;">

                                        <th style="vertical-align: middle;">Atrribué</th>
                                        <th style="vertical-align: middle;">Programmé</th>
                                        <th style="vertical-align: middle;">Réalisé</th>
                                        <th style="vertical-align: middle;">%Réalisation</th>
                                    </tr>                                    
                                    </thead>
                                    <tbody>
                                    <tr ng-repeat="teachingUnit in $ctrl.subjectsFollowUp" class="clickable teacher-item"
                                        ng-style="{'background-color': teachingUnit.id === selectedTeachingUnitId ? 'lightblue' : 'initial'}"
                                        ng-click="onSelectTeachingUnit(teachingUnit.id)">
                                        <td>{{$index+1}}</td>
                                        <td>{{teachingUnit.codeUe}}</td>
                                        <td>{{teachingUnit.semester}}</td>
                                        <td>{{teachingUnit.classe}}</td>
                                        <td class="bg-primary text-white">{{teachingUnit.totalHrs}}H</td>
                                        <td class="bg-warning text-white"></td>
                                        <td class="bg-success text-white">{{teachingUnit.totalHrsDone}}H</td>
                                        <td class="bg-danger text-white">{{(teachingUnit.totalHrsDone/teachingUnit.totalHrs)*100}}%</td>
                                       
                                    </tr>
                                    <tr style="text-align:center;font-weight : bold; color: #fff; background-color:#708090;"><td  colspan="4">Total Volume Horaire</td><td align="left">{{$ctrl.subjectsFollowUp|sumByKey:'totalHrs'}}H</td>
                                        <td></td>
                                    <td align="left">{{$ctrl.subjectsFollowUp|sumByKey:'totalHrsDone'}}H</td>
                                    <td></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
            </md-input-container>

            </div>

        </div>
        </div>
           
 

                
 

