<!DOCTYPE html>
<html lang="en">

<head>

 
        <?= $this->headTitle('W-Academy App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/shop-item.css'))
            ->prependStylesheet($this->basePath('../node_modules/@fortawesome/fontawesome-free/css/all.css'))
            ->prependStylesheet($this->basePath('../node_modules/bootstrap/dist/css/bootstrap.min.css'))
        
 
        

        ?>



</head>

<body style="background-color: #f7f7f7;">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">My Academy</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <!--<li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>-->
          <li class="nav-item">
            <span class="nav-link"> Bienvenue <?=$this->identity()?></span> 
          </li> 
          <li class="nav-item ">
              <a class="nav-link" href="logout"><i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Se Déconnecter</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container-fluid">

    <div class="row">
<!--
      <div class="col-lg-3">
          
        <div class="list-group mt-4">
          <a href="patientExams" class="list-group-item">Gérer les examens</a>
         
          <a href="#" class="list-group-item">Mes résultats</a>
          <a href="#" class="list-group-item">Mes paiements</a>
        </div>
      </div>
      <!-- /.col-lg-3 -->
      
      <div class="center-screen col-lg-12 mt-auto" ng-app="cpconlineApp" ng-controller="cpconlineCtrl" >
           
        <?= $this->content ?>
          
        <!-- /.card -->

      </div>
      <!-- /.col-lg-9 -->
      


    </div>

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer  >
    <div class="container-fluid py-5 bg-dark" style="margin-top: 150px;">
      <p class="m-0 text-center text-white">Copyright &copy; W-Tech 2024</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
        <?= $this->headScript()

        ->prependFile($this->basePath('../node_modules/@fortawesome/fontawesome-free/js/all.min.js'))
        ->prependFile($this->basePath('../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js'))
        ->prependFile($this->basePath('../node_modules/bootstrap/dist/js/bootstrap.min.js'))
        ->prependFile($this->basePath('../node_modules/jquery/dist/jquery.min.js'))
            
        ?>

</body>

</html>

