<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Academy Software By W-tech')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/angular-busy.min.css'))
        //->prependStylesheet($this->basePath('css/registration/bootstrap.min.css'))
        //->prependStylesheet($this->basePath('css/registration/style.css'))
        ->prependStylesheet($this->basePath('css/fas/css/fontawesome.css'))
        ->prependStylesheet($this->basePath('css/fas/css/brands.css'))
        ->prependStylesheet($this->basePath('css/fas/css/regular.css'))
        ->prependStylesheet($this->basePath('css/fas/css/solid.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/angular-material.css'))
        
        
        
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body ng-app="myApp" ng-cloak>

        <nav class="navbar navbar-expand-md navbar-dark " role="navigation">
            <div class="container">
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/logo.gif') ?>" alt="Agenla academy">
                </a>
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>

                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a
                                class="nav-link active"
                                aria-current="page"
                                href="home"
                            >Home
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
              <div class="col-md-8">
         
                <?= $this->content ?>
              </div>
            
                <div class="col-md-4">
                    <div class="alert alert-warning mt-5">
                        <p><i class="fa-solid fa-bell"></i> &nbsp; Vous avez soumis un dossier de candidature et vous souhaitez avoir un feeback sur son état de traitement, alors connectez vous en saisisant comme login votre adresse email et votre numéro de dossier come mot de passe . </p>
                    </div>

<?php
use Laminas\Captcha;
use Laminas\Captcha\Dumb;
use Laminas\Form\Element;
use Laminas\Form\Fieldset;
use Laminas\Form\Form;
use Laminas\InputFilter\Input;
use Laminas\InputFilter\InputFilter;



// Create a text element to capture the user email address:
$email = new Element\Email('email');
$email->setLabel('Your email address');
$email->setAttributes([
    'class'=>'form-control mb-3',
    'placeHolder' => 'Votre adresse email',

    
]);

// Create a text element to capture the message subject:
$subject = new Element('subject');
$subject->setLabel('Subject');
$subject->setAttributes([
    'type' => 'text',
    'class'=>'form-control mt-3',

]);



// Create a CAPTCHA:
// let's skip the captcha for now

// Create a CSRF token:

$csrf = new Element\Csrf('security');

$password = new Element\Password('numDossier');
$password->setLabel('Votre numéro de dossier ici');
$password->setAttributes([
    'class'=>'form-control',
    'required'=>true,
    'placeHolder' => 'Votre numéro de dossier ici',
    
]);
// Create a submit button:
$send = new Element('send');
$send->setLabel('Submit');
$send->setAttributes([
    'type' => 'submit',
    'class'=>'form-control mt-3 btn btn-primary',
    'value'=>"Connectez vous"

]);


// Create the form and add all elements:
$form = new Form('contact');

//$form->add($email);
$form->add($password);


$form->add($send);

$form->prepare();

// Assuming change the / to whatever framework you're using does for routes or app urls
$form->setAttribute('action', '');

// Set the method attribute for the form
$form->setAttribute('method', 'post');

$form->prepare();

if(isset($fileStatus))
    echo '<div class="alert alert-danger"> Numéro de dossier introuvable</div>';

// Render the opening tag
echo $this->form()->openTag($form);

// ...loop through and render the form elements...
foreach ($form as $element) {
    echo $this->formElement($element);
    echo $this->formElementErrors($element);
}

// Render the closing tag
echo $this->form()->closeTag();
?>


        </div>  
            </div>

            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="#"></a> 
                </p>
            </footer>
        </div>
        <?= $this->inlineScript()
        ->prependFile($this->basePath('js/angular-toastr.min.js'))
        ->prependFile($this->basePath('js/moment.min.js'))
        ->prependFile($this->basePath('bower_components/angular-material/angular-material.min.js'))
        ->prependFile($this->basePath('bower_components/angular-messages/angular-messages.min.js'))
        ->prependFile($this->basePath('bower_components/angular-animate/angular-animate.min.js'))
        ->prependFile($this->basePath('bower_components/angular-aria/angular-aria.min.js'))
        ->prependFile($this->basePath('bower_components/bower-angular-resource/angular-resource.js'))
        
        ->prependFile($this->basePath('js/angular-image-compress.js'))
        ->prependFile($this->basePath('js/angular-busy.min.js'))      
        ->prependFile($this->basePath('js/angular-toastr.min.js'))    
          ->prependFile($this->basePath('js/loading-bar.js'))   
          
        ->prependFile($this->basePath('js/ui-bootstrap-tpls-2.5.0.min.js'))
     
        ->prependFile($this->basePath('js/angular-route.js'))
        
        
        ->prependFile($this->basePath('js/app/onlinereg.js'))
       
        ->prependFile($this->basePath('js/app/app.js'))
         ->prependFile($this->basePath("js/app/onlinereg/student.component.js"))
        //->prependFile($this->basePath('js/registration/bootstrap.min.js'))
        ->prependFile($this->basePath('js/angular-image-compress.js'))
        ->prependFile($this->basePath('js/angular-busy.min.js'))
            ->prependFile($this->basePath('js/angular-material.min.js'))
        
        ->prependFile($this->basePath('js/angular-messages.min.js'))
        ->prependFile($this->basePath('js/angular-aria.min.js'))
        ->prependFile($this->basePath('js/angular-animate.min.js'))
        ->prependFile($this->basePath('js/angular.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.7.0.min.js'))
        ?>
    </body>
</html>
