<!DOCTYPE html>
<html lang="en">

<head>

 
        <?= $this->headTitle('W-Academy App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/shop-item.css'))
        ->prependStylesheet($this->basePath('css/sb-admin-2.css'))
            
            ->prependStylesheet($this->basePath('../node_modules/@fortawesome/fontawesome-free/css/all.css'))
            ->prependStylesheet($this->basePath('../node_modules/bootstrap/dist/css/bootstrap.min.css'))
        ?>

       


</head>

<body style="background-color: #f7f7f7;">

<div id="wrapper">
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">My Academy</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <!--<li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>-->
          <li class="nav-item">
            <span class="nav-link"> Bienvenue <?=$this->identity()?></span> 
          </li> 
          <li class="nav-item ">
              <a class="nav-link" href="logout"><i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Se Déconnecter</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container" ng-app="teacherApp" ng-controller="lecturerCtrl as $ctrl" >

    <div class="row">
        <div class="col-lg-3">
            
       
        <div class="navbar-default sidebar" role="navigation">
          
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="showResults" ><i class="fas fa-poll"></i>&nbsp;Mon profile</a>
                    </li>
                    <li>
     
                        <a href="#"><i class="fa fa-graduation-cap fa-fw"></i> Unités d'enseignements<span class="fa arrow"></span></a>
                   
                    
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="lSubjects">Enseignements attribués</a>
                            </li>
                            <li>
                                <a href="#!/admission">Suivi des enseignements</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" ><i class="fas fa-shopping-cart"></i>&nbsp;Emploi de temps</a>
                    </li>
                    <li>
                        <a href="#" ><i class="fas fa-shopping-cart"></i>&nbsp;Evaluation</a>        
                    </li>
                    <li>
                        <a href="#" ><i class="fas fa-shopping-cart"></i>&nbsp;Mes factures</a>        
                    </li>
                    <li>
                        <a href="#"><i class="fas fa-shopping-cart"></i>&nbsp;Documentation</a>  
                    </li>

               </ul>
            </div>
          
      </div>
        </div>
      <!-- /.col-lg-3 -->
      
      <div class="col-lg-9" ng-init="init()">
          <?=  $this->content ?>
        <div ng-view></div>
         
        <!-- /.card -->

      </div>
      
      <!-- /.col-lg-9 -->

    </div>

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="mt-5 py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Centre pasteur du Cameroun 2021</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
        <?= $this->headScript()

        ->prependFile($this->basePath('../node_modules/@fortawesome/fontawesome-free/js/all.min.js'))
        ->prependFile($this->basePath('../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js'))
        ->prependFile($this->basePath('../node_modules/bootstrap/dist/js/bootstrap.min.js'))
        ->prependFile($this->basePath('../node_modules/jquery/dist/jquery.min.js'))
        ->prependFile($this->basePath('js/angular-route.js'))
        ->prependFile($this->basePath('js/angular-1.6.7/angular.js'))            
        ?>
  
        <script src="js/app/onlinereg/student.component.js"></script>
        <script src="bower_components/angular-material/angular-material.min.js"></script>  
        <script src="bower_components/angular-animate/angular-animate.min.js"></script>
        <script src="bower_components/angular-messages/angular-messages.min.js"></script>
        <script src="bower_components/angular-aria/angular-aria.min.js"></script>
        <script src="bower_components/bower-angular-resource/angular-resource.js"></script>
        <script src="js/angular-image-compress.js"></script>
        <script src="js/angular-busy.min.js"></script>
        <script src="js/app/teacherApp.js"></script> 
        <script src="js/app/lecturer.js"></script>
</body>

</html>

