<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Academy Software By W-tech')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/angular-busy.min.css'))
        //->prependStylesheet($this->basePath('css/registration/bootstrap.min.css'))
        //->prependStylesheet($this->basePath('css/registration/style.css'))
        ->prependStylesheet($this->basePath('css/fas/css/fontawesome.css'))
        ->prependStylesheet($this->basePath('css/fas/css/brands.css'))
        ->prependStylesheet($this->basePath('css/fas/css/regular.css'))
        ->prependStylesheet($this->basePath('css/fas/css/solid.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/angular-material.css'))
        
        
        
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body ng-app="myApp" ng-cloak>

        <nav class="navbar navbar-expand-md navbar-dark " role="navigation">
            <div class="container">
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/logo.gif') ?>" alt="Agenla academy">
                </a>
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>

                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a
                                class="nav-link active"
                                aria-current="page"
                                href="home"
                            >Home
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
 
         
                <?= $this->content ?>
          
            
          

            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="#"></a> 
                </p>
            </footer>
        </div>
        
        <?= $this->inlineScript()
        ->prependFile($this->basePath('js/angular-toastr.min.js'))
        ->prependFile($this->basePath('js/moment.min.js'))
        ->prependFile($this->basePath('bower_components/angular-material/angular-material.min.js'))
        ->prependFile($this->basePath('bower_components/angular-messages/angular-messages.min.js'))
        ->prependFile($this->basePath('bower_components/angular-animate/angular-animate.min.js'))
        ->prependFile($this->basePath('bower_components/angular-aria/angular-aria.min.js'))
        ->prependFile($this->basePath('bower_components/bower-angular-resource/angular-resource.js'))
        
        ->prependFile($this->basePath('js/angular-image-compress.js'))
        ->prependFile($this->basePath('js/angular-busy.min.js'))      
        ->prependFile($this->basePath('js/angular-toastr.min.js'))    
          ->prependFile($this->basePath('js/loading-bar.js'))   
          
        ->prependFile($this->basePath('js/ui-bootstrap-tpls-2.5.0.min.js'))
     
        ->prependFile($this->basePath('js/angular-route.js'))
        
        
        ->prependFile($this->basePath('js/app/onlinereg.js'))
       
        ->prependFile($this->basePath('js/app/app.js'))
         ->prependFile($this->basePath("js/app/onlinereg/student.component.js"))
        //->prependFile($this->basePath('js/registration/bootstrap.min.js'))
        ->prependFile($this->basePath('js/angular-image-compress.js'))
        ->prependFile($this->basePath('js/angular-busy.min.js'))
            ->prependFile($this->basePath('js/angular-material.min.js'))
        
        ->prependFile($this->basePath('js/angular-messages.min.js'))
        ->prependFile($this->basePath('js/angular-aria.min.js'))
        ->prependFile($this->basePath('js/angular-animate.min.js'))
        ->prependFile($this->basePath('js/angular.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.7.0.min.js'))
        ?>
   

    </body>
</html>
