<?= $this->doctype() ?>

<html lang="en" >
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('UdM: Inscription en ligne')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/registration/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/font-awesome/css/font-awesome.css'))
            ->prependStylesheet($this->basePath('bower_components/angular-animate/angular-animate.min.css'))
            ->prependStylesheet($this->basePath('bower_components/angular-material/angular-material.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
        ->prependFile($this->basePath('js/angular-toastr.min.js'))
        ->prependFile($this->basePath('js/moment.min.js'))
        ->prependFile($this->basePath('bower_components/angular-material/angular-material.min.js'))
        ->prependFile($this->basePath('bower_components/angular-messages/angular-messages.min.js'))
        ->prependFile($this->basePath('bower_components/angular-animate/angular-animate.min.js'))
        ->prependFile($this->basePath('bower_components/angular-aria/angular-aria.min.js'))
        ->prependFile($this->basePath('bower_components/bower-angular-resource/angular-resource.js'))
        
        ->prependFile($this->basePath('js/angular-image-compress.js'))
        ->prependFile($this->basePath('js/angular-busy.min.js'))      
        ->prependFile($this->basePath('js/angular-toastr.min.js'))    
          ->prependFile($this->basePath('js/loading-bar.js'))   
          
        ->prependFile($this->basePath('js/ui-bootstrap-tpls-2.5.0.min.js'))
        ->prependFile($this->basePath('js/angular-animate.js'))
        ->prependFile($this->basePath('js/angular-route.js'))
           ->prependFile($this->basePath('js/angular-1.6.7/angular.js'))
        ->prependFile($this->basePath('js/registration/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
       
        ?>

       
        <script src="js/app/onlinereg.js"></script>
        <script src="js/app/app.js"></script>
        <script src="js/app/onlinereg/student.component.js"></script>
        

    </head>
   
    <body>
        <nav class="navbar navbar-default  navbar-fixed-top" role="navigation">
            
            
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/logo.gif') ?>" height="28" alt="AgenlaAcademy inscriprion en ligne"/>&nbsp;Inscription en ligne
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="home">Ré-iniscription</a></li>

                    </ul>
                    <ul class="nav navbar-nav pull-right">
                        <li>
                            <a href="logout">ID: <?=$this->identity()?>&nbsp;&nbsp;<i class="glyphicon glyphicon-log-in"></i>&nbsp;&nbsp;Se déconnecter</a>
                           
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->

                </div>                            
 
                </div>

            </div>
        </nav>
        <div class="container" style="background-color: #ffffff">
            <div class="col-lg-12 col-md-12">   
                <?= $this->content ?>
            </div> 
           <!-- <div class='col-lg-3 col-md-3'></div> -->

        </div>
        <div class="container" >
            <hr>
            <footer> 
                <p>&copy; 2018 - <?= date('Y') ?> by Service Iinformatique UdM.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
