

    
   

<div class=" bg-light  rounded-3 mt-5 p-3 "      );
            background-size: cover;
            color: #581845;
        >        
<div class='row'>
    <div class="col-md-8" >
        <h1 >Bienvenue à Agenla Academy </h1>
        <span style="font-size: 1.5em;  font-weight: normal; ">Inscription ou réiniscription défintive</span>
        <br /><br /><br /><br />
            <div class="accordion" id="accordionExample">
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                      <strong>Je me réinscris</strong>&nbsp; à Agenla &nbsp;
                    <span class='small'>// J'ai déjà un numéro de matricule</span>
                  </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                  <div class="accordion-body">

                      
                    Tous  les  étudiants de Agenla Academy sont  tenus  de   se  réinscrire  pour  le compte de l’année courrante. <br />
                    L’inscription administrative et  académique consite à : 
                    <ul>
                        <li>Paiement des frais  exigibles ;</li>  
                        <li>Remplissage en ligne du formulaire d'inscription,</li> 
                        <li>Téléchargement et dépôt d’une fiche d’inscription accompagnée de tout autre document exigé par l’UdM au Secrétariat de la Filière.</li> 
                    </ul>  
                    Votre ré-inscription sera définitive après réception et vérification par la scolarité de vos pièces et paiements dus. 
                    <div class='alert alert-success'>
                        <span class='fa fa-link'></span> <a href="login">Je me ré-inscris</a> 
                    </div>
                    <div class='alert alert-danger small' style='margin-top: 15px;'>
                        <span class='fa fa-warning'></span>Attention, une fois le paiement effectué, vous devez attendre au plus 48h (jour ouvrable) pour qu'il soit pris en compte dans la base de donnée.                   

                    </div>                     
                      
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingTwo">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      Je m'inscris pour la <strong> &nbsp;première fois à Agenla Academy</strong> 
                    <span class='small'>&nbsp;// Je suis nouveau</span>
                  
                  </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
Pour procéder à votre inscription définitive et au paiement des droits d'inscription, munissez-vous de votre

                 numéro d'admission que vous obtiendrez après soumission en ligne de votre candidature d'admission <a href="apply">en cliquant ici</a>. une fois ce numéro obtenu, vous devez:
        
                 <ul>
                     <li>Procéder au paiement de la somme d'au moins ....... pour confirmer votre admission;</li> 
                     <li>Scanner votre réçu de paiement au format pdf;</li>
                     <li>Remplir le formulaire d'inscription en ligne;</li> 
                     <li>Téléchargement et dépôt d’une fiche d’inscription accompagnée de tout autre document exigé au Secrétariat de la Filière.</li> 
                     <!--<li>Téléchargement de la fiche d'engagement sur l'honneuur: <a href="impressions/Engagement_honneur-sept2016.pdf">Cliquer Ici</a></li>--> 
                     
                 </ul>  



                <div class='alert alert-success'style='margin-top: 15px;'>
                      <span class='fa fa-link'></span> <a href="newstudentlogin">Je m'inscris</a> 
                </div>               
                <div class='alert alert-danger small text-justify' style='margin-top: 15px;'>
                    <span class='fa fa-warning'></span>
                    Votre inscription sera définitive après réception et vérification par la scolarité de l'ensemble de vos pièces et paiements dus.
                </div>                   
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingThree">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Accordion Item #3
                  </button>
                </h2>
                <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                  </div>
                </div>
              </div>
            </div>
    </div>
    <div class="col-md-4">

        <div class="panel panel-primary">
            <div class="panel-heading">pour vous <strong>inscrire,</strong> vous devez:</div>
          <div class="panel-body">
            <ul style="padding: 15px;">
                <li>Avoir <strong>vérifié</strong>  auprès des autorités académique que vous êtes bien admis à l'un des concours d'entrée ou admis sur titre</li>
                
                <li>Avoir  <strong>confirmé votre place</strong> en vous acquittant de du paiement de la somme de 150 000FCFA</li>
            </ul>
          </div>
        </div>
        <div class="panel panel-success">
            <div class="panel-heading">pour vous <strong>réinscrire,</strong> vous devez:</div>
          <div class="panel-body">
              <ul style="padding: 15px;">
                  <li>Avoir <strong>connaissance de vos résultats</strong> pour l'année en cours</li>
                  <li>Être <strong>admins à poursuivre</strong> ou à <strong>redoubler</strong></li>
                  <li>Avoir<strong> soldé la totalité des frais de scolarité des années académques antérieures.</strong></li>
                  <li>Avoir <strong> payé les frais de transport qui s'élèvents à 115 000FCFA</strong> </li>
              </ul>
          </div>
        </div>
    </div>
</div>
    </div>

