

<link rel="stylesheet" href="js/calendar/fullcalendar/dist/fullcalendar.css"/>
<?= $this->headScript()
        ->prependFile($this->basePath('js/calendar/fullcalendar/dist/gcal.js'))
        ->prependFile($this->basePath('js/calendar/fullcalendar/dist/fullcalendar.min.js'))
        ->prependFile($this->basePath('js/calendar/angular-ui-calendar/src/calendar.js'))
        ->prependFile($this->basePath('js/calendar/angular/angular.min.js'))
         ->prependFile($this->basePath('js/calendar/moment/min/moment.min.js'))
        ->prependFile($this->basePath('js/calendar/jquery/dist/jquery.min.js'))
        ?>

<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>


<div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">
        
            <div class="row">
                <div class='col-md-6'>
                    <div >
                    
                    <span> <a href="home">Annuler</a></span>
                    </div>

                    
                </div>
        


                
            </div>
</div>
<div class="row">
<div class="col-md-4"> 
     <div class="form-view">
         
        <md-content  >
            <h3>Gérer les campus</h3>
            <md-checkbox  ng-model="$ctrl.showCampusForm" ng-disabled="" aria-label="Checkbox Indeterminate" ng-

                ng-true-value="1"
                ng-false-value="0"             
                class="md-primary">

            </md-checkbox>
            <i ng-show="$ctrl.showCampusForm">Cacher le formulaire</i>  
            <i ng-hide="$ctrl.showCampusForm">Afficher le formulaire</i>             
            <form   name="classroomForm" ng-show="$ctrl.showCampusForm">
                
                    <md-input-container class="md-block" flex-gt-sm  >
                        <label>Nom du Campus:</label>
                        <input name="name" ng-model="$ctrl.campusName" required />
                            <div ng-messages="classroomForm.name.$error">
                                <div ng-message="required">le champ code de spécialité est obligatoire</div>
                                <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                            </div> 
                    </md-input-container>
                    <md-input-container class="md-block" flex-gt-sm  >
                        <label>Code campus:</label>
                        <input name="name" ng-model="$ctrl.campusCode" required />
                            <div ng-messages="classroomForm.code.$error">
                                <div ng-message="required">le champ code de spécialité est obligatoire</div>
                                <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                            </div> 
                    </md-input-container>                 

                <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('exam.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="addEvent()" class="btn btn-danger" ng-disabled="classroomForm.$invalid" ><i class="fa fa-plus"></i> &nbsp;Enrégistrer</button>

           



            </form>
        </md-content>  
    </div>
    
    <!-- comment --></div>

<div class=" col-md-4 ">
    <div class="form-view">

        
        
        <md-content  >
            <h3>Gérer les bâtiments</h3>
            <md-checkbox  ng-model="$ctrl.showBuilding" ng-disabled="" aria-label="Checkbox Indeterminate" ng-

                ng-true-value="1"
                ng-false-value="0"             
                class="md-primary">

            </md-checkbox>  
            <i ng-show="$ctrl.showBuilding">Cacher le formulaire</i>  
            <i ng-hide="$ctrl.showBuilding">Afficher le formulaire</i>  
            
            <form   name="classroomForm2" ng-show="$ctrl.showBuilding">

               
                    <md-input-container class="md-block" flex-gt-sm  >
                        <label>Nom du bâtiment:</label>
                        <input name="name" ng-model="$ctrl.buildingName" required />
                            <div ng-messages="classroomForm2.name.$error">
                                <div ng-message="required">le champ code de spécialité est obligatoire</div>
                                <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                            </div> 
                    </md-input-container>
                    <md-input-container class="md-block" flex-gt-sm  >
                        <label>Code bâtiment:</label>
                        <input name="name" ng-model="$ctrl.buildingCode" required />
                            <div ng-messages="classroomForm2.code.$error">
                                <div ng-message="required">le champ code de spécialité est obligatoire</div>
                                <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                            </div> 
                    </md-input-container>                

                <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('exam.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="addEvent()" class="btn btn-danger" ng-disabled="classroomForm2.$invalid" ><i class="fa fa-plus"></i> &nbsp;Enrégistrer</button>

           



            </form>
        </md-content>  
        

                
           
    </div>
</div>
<div class=" col-md-4 ">
    <div class="form-view">

        
         
        <md-content  >
            <h3>Gérer les salles de cours</h3>
            <md-checkbox  ng-model="$ctrl.showClassroomForm" ng-disabled="" aria-label="Checkbox Indeterminate" ng-

                ng-true-value="1"
                ng-false-value="0"             
                class="md-primary">

            </md-checkbox>
            <i ng-show="$ctrl.showClassroomForm">Cacher le formulaire</i>  
            <i ng-hide="$ctrl.showClassroomForm">Afficher le formulaire</i> 
            <form   name="classroomForm3" ng-show="$ctrl.showClassroomForm">
                    <md-input-container class="md-block" flex-gt-sm  >
                        <label>Nom due la salle de cours:</label>
                        <input name="name" ng-model="$ctrl.classroomName" required />
                            <div ng-messages="classroomForm3.name.$error">
                                <div ng-message="required">le champ code de spécialité est obligatoire</div>
                                <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                            </div> 
                    </md-input-container>
                    <md-input-container class="md-block" flex-gt-sm  >
                        <label>Code salle de cours:</label>
                        <input name="name" ng-model="$classroomCode" required />
                            <div ng-messages="classroomForm3.code.$error">
                                <div ng-message="required">le champ code de spécialité est obligatoire</div>
                                <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                            </div> 
                    </md-input-container>                 

                <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('exam.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="addEvent()" class="btn btn-danger" ng-disabled="classroomForm3.$invalid" ><i class="fa fa-plus"></i> &nbsp;Enrégistrer</button>

          



            </form>
        </md-content>  
        

                
           
    </div>
</div>