<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="p-5 mt-1 mb-4 bg-light  rounded-3 "      style="background-image: url('img/agenla.jpg');
            height: 60vh;
            background-size: cover;
            color: #581845;
">
    <br /><br />
    <h1 class="display-4"><strong>Agenla Academy</strong><br></h1><h1><span style="color: #fff;" >  La plateforme de gestion académique de l'Institut Supérieure Agenla </span></h1>



    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://github.com/laminas" target="_blank">
        Connectez vous
    </a>
</div>


<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
        <div class="card h-75 rounded-3 bg-light text-primary">
   
            <div class="card-body">
                <p>
                    Laminas Project is under active development. If you are
                    interested in following the development, you can check
                    <a href="https://getlaminas.org/blog/">Laminas dev blog</a>,
                    and <a href="https://github.com/issues?utf8=%E2%9C%93&amp;q=is:issue+org:laminas">Laminas issue tracker</a>
                    (link requires a GitHub account). This is a great resource
                    for staying up to date with the latest developments!
                </p>
            </div>

        </div>
    </div>

    <div class="col">
        <div class="card h-75  rounded-3 bg-light text-dark">
        
            <div class="card-body align-middle">
                <p>
                    Laminas MVC is a modular application.
                    You can find multiple compatible modules on packagist.
                </p>
            </div>

        </div>
    </div>

    <div class="col">
        <div class="card h-75 align-middle  rounded-3 bg-info text-white">
            
            <div class="card-body align-middle">
                <p>
                    If you need any help or support while developing with Laminas,
                    you may reach us via <a href="https://laminas.dev/chat">chat</a> or
                    <a href="https://discourse.laminas.dev">forum</a>.
                    We'd love to hear any questions or feedback you may have
                    regarding any release.
                </p>
            </div>

        </div>
    </div>
</div>
