<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="p-5 mt-1 mb-4 bg-light  rounded-3 "      style="background-image: url('img/agenla.jpg');
            height: 60vh;
            background-size: cover;
            color: #581845;
">
    <br /><br />
    <h1 class="display-4"><strong> Agenla Academy</strong><br></h1><h1><span style="color: #fff;" >  La plateforme de gestion académique de l'Institut Supérieure Agenla Academy </span></h1>



    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="#" >
        Connectez vous
    </a>
</div>


<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
        <div class="card h-75 rounded-3 bg-light text-primary">
   
            <div class="card-body">
                    <a class="btn btn-danger " href=""><i class="fa-solid fa-square-plus" > </i>&nbsp;Soumettre une candidature d'admission</a>
               
            </div>

        </div>
    </div>

    <div class="col">
        <div class="card h-75  rounded-3 bg-light text-dark">
        
            <div class="card-body align-middle">
                <a class="btn btn-danger "href=""><i class="fa-solid fa-pen-to-square"> </i> &nbsp;S'inscrire ou se réinscrire</a>
           
            </div>

        </div>
    </div>

    <div class="col">
        <div class="card h-75 align-middle  rounded-3 bg-info text-white">
            
            <div class="card-body align-middle">
                <p>
                    la plateforme Agenla Academy permet 
                </p>
            </div>

        </div>
    </div>
</div>
