<script src="js/app/department/department.component.js"></script>
<link rel="stylesheet" href='js/datatables-plugins/dataTables.bootstrap.css'>


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}

li.active a.ng-binding {
  color: #000 !important;
	background-color: #eeeeee !important;
	text-decoration: none;
}
.mt-50 {margin-top: 50px;}
.mt-25 {margin-top: 25px;}

</style>


<div class="well"  style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">
        
            <div class="row">
                <div class='col-md-6'>

                    
                    <span> <a href="#!/cycleFormation">Retour</a></span>
                </div>
                <div class="col-md-6" > <h4>Paramètres </h4></div>

                

                
            </div>
</div>

<div class="form-view-main">
    <div class="form-view">
        <div   ng-cloak class="md-inline-form">

   
    </div>
        

        
<p>&nbsp;</p>
              <!--tabs widget-->
              
    <uib-tabset>
      <uib-tab >
          <uib-tab-heading>
              <span>Synchronisation odoo</span>
          </uib-tab-heading>
        <div class="tab-container">              
            <div   ng-cloak class="md-inline-form">

                <md-content layout-padding >
                    <form   name="formSync">

                <md-checkbox class='md-primary' ng-model="odooSettings.activateStatus"  ng-checked="(odooSettings.activateStatus)"aria-label="Actif ?" md-no-ink > Activer la synchronisation avec odoo?</md-checkbox>
                <div class="md-dialog-content"  ng-init="init()" ng-show="odooSettings.activateStatus">

                     
                        <div layout layout-sm="column" style="padding-top: 20px;">
                            <md-input-container flex="flex" style="width: 60%" >
                                <label>Adresse URL:</label>
                                
                                <input type='text'  name='url' ng-model="odooSettings.url" width='80%' md-no-asterisk required />
                                    <div ng-messages="formSync.url.$error">
                                        <div ng-message="required">le champ URL est obligatoire</div>
                                    </div>                    

                            </md-input-container>
                            </div>
                        <div layout layout-sm="column">
                            <md-input-container flex="flex" style="width: 20%" >

                                <label>Nom de la base de données:</label>
                                <input type='text'  name="databaseName" ng-model="odooSettings.databaseName" width='80%' minlength="2" md-no-asterisk required />
                                    <div ng-messages="formSync.databaseName.$error">
                                        <div ng-message="required">le champ nom de la base de données est obligatoire</div>
                                        <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                                    </div>
                            </md-input-container> 
                        </div>
                        <div layout layout-sm="column">
                            <md-input-container flex="flex" style="width: 20%" >

                                <label>Login:</label>
                                <input type='text'  name="login" ng-model="odooSettings.login" width='80%' minlength="2" md-no-asterisk required />
                                    <div ng-messages="formSync.login.$error">
                                        <div ng-message="required">le champ login  est obligatoire</div>
                                        <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                                    </div>
                            </md-input-container> 
                        </div>
                        <div layout layout-sm="column">
                            <md-input-container flex="flex" style="width: 20%" >

                                <label>Mot de passe:</label>
                                <input type='password'  name="password" ng-model="odooSettings.password" width='80%' minlength="2" md-no-asterisk required />
                                    <div ng-messages="formSync.password.$error">
                                        <div ng-message="required">le champ password  est obligatoire</div>
                                        <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                                    </div>
                            </md-input-container> 
                        </div>                      
                    <button  ng-show=" <?=($this->access('global.system.admin', null))?true:false?> &&odooSettings.activateStatus " type="button" ng-click="$ctrl.updateOdooSettings(odooSettings)" class="btn btn-danger" ng-disabled="formSync.$invalid" ><span class="fa fa-plus-square"></span>&nbsp;Enregistrer </button>                     
                  </div>
                <button  ng-show=" <?=($this->access('global.system.admin', null))?true:false?> && !odooSettings.activateStatus" type="button" ng-click="$ctrl.updateOdooSettings(odooSettings)" class="btn btn-danger" ><span class="fa fa-plus-square"></span>&nbsp;Enregistrer </button>
                </form>
              </md-content>
         </div>
                <!--End tab-->
                
            </div>  
            </uib-tab>
            <uib-tab>
                <uib-tab-heading>
                    <span>Paramètres de facturation</span>
                </uib-tab-heading>
                <div class="tab-container"> 
                    
                <div   ng-cloak class="md-inline-form">

                    <md-content layout-padding >
                    <form   name="myTaxForm">


                        <div class="md-dialog-content"  ng-init="$ctrl.init()">

                            
                                <div layout layout-sm="row" style="padding-top: 30px;">
                                      <md-input-container class="md-block" flex-gt-sm  >
                                          <label>Description:</label>
                                          <input type='text'  name='name' ng-model="$ctrl.tax.description"  md-no-asterisk required />
                                              <div ng-messages="myTaxForm.name.$error">
                                                  <div ng-message="required">le champ nom de la filièreest obligatoire</div>
                                                  <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                                              </div>                    

                                      </md-input-container>
                                  
                                      <md-input-container  class="md-block" flex-gt-sm  >
                                          <label>Code:</label>
                                          <input type='text'  name='code' ng-model="$ctrl.tax.code"  md-no-asterisk required />
                                              <div ng-messages="myTaxForm.code.$error">
                                                  <div ng-message="required">le champ nom de la filièreest obligatoire</div>
                                                  <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                                              </div>                    

                                      </md-input-container><!-- comment --> 
                                      <md-input-container class="md-block" flex-gt-sm  >
                                          <label>Taux de retenue:</label>
                                          <input type='text'  name='rate' ng-model="$ctrl.tax.rate"  md-no-asterisk required />
                                              <div ng-messages="myTaxFormrate.$error">
                                                  <div ng-message="required">le champ nom de la filièreest obligatoire</div>
                                                  <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                                              </div>                    

                                      </md-input-container>   

                                </div>
                     
                            
                            <div layout="row" class="gap-1 mt-auto">
                                <md-checkbox class='md-primary' ng-model="$ctrl.tax.isRefundable"  "aria-label="Actif ?" md-no-ink > Est une retenue remboursable?</md-checkbox>
                            </div>
                            
                        <div layout="row " class="gap-1 mt-25">            
                        <button  ng-show=" <?=($this->access('global.system.admin', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="$ctrl.createTaxesOrWithholdings($ctrl.tax)" class="btn btn-danger" ng-disabled="myTaxForm.$invalid" ><span class="fa fa-plus-square"></span>&nbsp;Enregistrer </button>
                        <br \><br \><br \>
                        </div>
                            
                            
                        <div layout="row" class="gap-1 mt-50">
                            
                        <table id="tblfilieres"   class="table table-striped  table-hover table-condensed datatable">

                                        <thead>
                                            <tr>
                                                <th  > #</th>
                                                <th  > Description</th>
                                                <th >Code</th>
                                                <th >Taux</th>
                                                <th >Remboursable</th>

                                            </tr>
                                        </thead>
                                        <tbody>

                                            <tr ng-repeat="tax in $ctrl.taxes" style="cursor: pointer" ng-dblclick="$ctrl.updateTax(tax)">
                                                    <td >{{$index+1}}</td>
                                                  <td ng-bind="tax.description"></td>
                                                  <td ng-bind="tax.code"></td>
                                                  <td ng-bind="teach.value"></td>
                                                  
                                                  <td ng-bind='tax.refundable===true?"":"x"' ng-class="{'zf-green fa fa-check': tax.refundable,'zf-red': !tax.refundable }"></td>


                                                  <td>
                                                      <div class="btn-group">

                                                      <button  type="button" ng-click="deleteTeacher(teach)" class="btn btn-danger  btn-xs" ><i class="fa fa-trash-o"></i></button></td>
                                                      </div>

                                                 </tr>

                                        </tbody>
                            </table>
                        </div>
                        </div>
                    </form>
                        </md-content>
                </div>
                    </div>
            </uib-tab>
            <uib-tab>
                <uib-tab-heading>
                    <span>Poids des évaluations</span>
                </uib-tab-heading>
                <div class="tab-container"> 
                    
                <div   ng-cloak class="md-inline-form">

                    <md-content layout-padding >
                    <form   name="myForm">


                        <div class="md-dialog-content"  ng-init="init()">

                            <md-checkbox class='md-primary' ng-model="cycle.status"  ng-checked="(cycle.status)"aria-label="Actif ?" md-no-ink > Activer la retenue sur vacation?</md-checkbox>
                            <div layout layout-sm="column" style="padding-top: 30px;">
                                  <md-input-container  style="width: 50%;" >
                                      <label>Taux de retenue:</label>
                                      <input type='text'  name='name' ng-model="cycle.name" width='80%' md-no-asterisk required />
                                          <div ng-messages="myForm.name.$error">
                                              <div ng-message="required">le champ nom de la filièreest obligatoire</div>
                                              <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                                          </div>                    

                                  </md-input-container>
                                  </div>

                            <button  ng-show=" <?=($this->access('global.system.admin', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="$ctrl.newCycle(cycle)" class="btn btn-danger" ng-disabled="myForm.$invalid" ><span class="fa fa-plus-square"></span>&nbsp;Enregistrer </button>

                        </div>
                    </form>
                        </md-content>
                </div>
                    </div>
            </uib-tab>        
            <uib-tab>
                <uib-tab-heading>
                    <span>Frais d'inscritpion</span>
                </uib-tab-heading>
                <div class="tab-container"> 
                    
                <div   ng-cloak class="md-inline-form">

                    <md-content layout-padding >
                    <form   name="myForm">


                        <div class="md-dialog-content"  ng-init="init()">

                            <md-checkbox class='md-primary' ng-model="cycle.status"  ng-checked="(cycle.status)"aria-label="Actif ?" md-no-ink > Activer la vérification des frais d'inscription?</md-checkbox>
                            <div layout layout-sm="column" style="padding-top: 30px;">
                                  <md-input-container  style="width: 50%;" >
                                      <label>Montant:</label>
                                      <input type='text'  name='name' ng-model="cycle.name" width='80%' md-no-asterisk required />
                                          <div ng-messages="myForm.name.$error">
                                              <div ng-message="required">le champ nom de la filièreest obligatoire</div>
                                              <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                                          </div>                    

                                  </md-input-container>
                                  </div>

                            <button  ng-show=" <?=($this->access('global.system.admin', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="$ctrl.newCycle(cycle)" class="btn btn-danger" ng-disabled="myForm.$invalid" ><span class="fa fa-plus-square"></span>&nbsp;Enregistrer </button>

                        </div>
                    </form>
                        </md-content>
                </div>
                    </div>
            </uib-tab>        

